openshift/oc-mirror

- .github/workflows/ci.yaml
Added: 
- Added a simple workflow to run go vet, go build and go test. 
- No release or documentation actions included.
> chore: Added of CI config for GitHub Actions

- pkg/bundle/additional_test.go
This is just a holdover until a better solution is found.
> fix(mirror): use quay.io images in unit tests to avoid docker limits

- go.mod
- pkg/bundle/create/create.go
- pkg/operator/operator.go
> feat(mirror): mirror operator catalogs

- pkg/bundle/additional.go
- pkg/bundle/additional_test.go
- pkg/bundle/create/create.go
- pkg/bundle/image_test.go
- pkg/operator/operator.go
- Added a IsBlocked check for the operator catalogs
- Main caveat is that I need to edit a function that we had temporarily so I could have access to each image.
> feat: block operator images

- data/imageset-config.yaml
- go.mod
- go.sum
- pkg/bundle/additional.go
- pkg/bundle/create/create.go
- pkg/bundle/files_test.go
- pkg/bundle/release.go
- pkg/config/credentials.go
- pkg/config/load.go
- pkg/operator/operator.go
Features:
- Processes pullSecret for OCP, each catalog, and each user defined image
- If the pullSecret is not specified `oc mirror` will default for the docker config default place
> feat(mirror): handling pull secrets through imageset config

- Makefile
`-tags=json1` is needed for the sqlite CGo libs that operator-registry uses for handling sqlite-backed catalog indices.
> chore(build): add -tags=json1 so sqlite CGo compiles correctly

- pkg/bundle/additional.go
- pkg/bundle/release.go
- pkg/image/association.go
- pkg/operator/mirror.go
This PR adds a fix required to successfully add image associations for releases.
- Remove extra "src" from mapping destination path
- Used `oc` TargetFn to get the manifest location for the release image
> fix: changed path to remove extra src and added targetfn to release dest

- pkg/image/association.go
- pkg/operator/mirror.go
- Creates a custom error for "image missing mapping" because operator do not always have mapping information. This logs a warning instead.
> fix: create a custom error for image mapping

- .gitignore
- cmd/oc-bundle/create.go
- pkg/archive/archive.go
- pkg/archive/archive_test.go
- pkg/bundle/create/create.go
- pkg/bundle/files.go
- pkg/bundle/files_test.go
- pkg/bundle/init.go
- pkg/config/v1alpha1/metadata_types.go
- pkg/config/v1alpha1/testdata/metadata/valid.json
- pkg/image/association.go
- test/e2e-simple.sh
Featured added:
- No longer tracking duplicates blobs
- Replace pastFiles  with pastManifest and pastBlobs
- Created a creator struct for main create functions
- Reconciling blobs and manifests separately
> feat(create): layer and manifest tracking 

- pkg/operator/mirror.go
Fixed a bug when type casting an error in operator.go
> fix: added a check for err being nil when casting an error

- pkg/bundle/publish/publish.go
- pkg/bundle/release.go
Fixes release.go by providing accurate mapping information for releases to create associations.
> fix: changed release.go to get correct mapping information

- pkg/bundle/publish/publish.go
Fixed release mapping on publisher to only the top level association is processed
> fix: updated logic to only process top level release association

- pkg/archive/archive.go
- pkg/bundle/publish/publish.go
- pkg/bundle/release.go
- pkg/cli/options.go
- pkg/image/association.go
- pkg/operator/mirror.go
Problem: 
- For catalogs and release, we need to identify the top level association to pass to the `oc mirror` Run function.
Solution: 
- Created a new field in Association to include a TopLevel bool. This value is set based on whether the manifest is an index or by 
the operators and release packages.
Notes:
- Also adds an unarchiving function with the ability to exclude files and directories (not a follow on PR/issue for unit tests)
> feat(publish): feat/top level associations

- go.mod
- pkg/archive/archive.go
- pkg/archive/archive_test.go
- pkg/bundle/additional.go
- pkg/bundle/create/create.go
- pkg/bundle/publish/manifests.go
- pkg/bundle/publish/options.go
- pkg/bundle/publish/publish.go
- pkg/bundle/release.go
- pkg/image/association.go
- pkg/operator/mirror.go
- Changes to associations allow for process images and all of the associations values one at a time.
- Releases are kept together by updating the key to the release image after gathering the associations
- Added cleanup actions to archiver
> feat: multimap associations

- README.md
- pkg/bundle/additional.go
- pkg/bundle/create/create.go
- pkg/bundle/create/options.go
- pkg/bundle/publish/catalog_images.go
- pkg/bundle/publish/manifests.go
- pkg/bundle/publish/options.go
- pkg/bundle/publish/publish.go
- pkg/image/association.go
- pkg/operator/mirror.go
- test/e2e-simple.sh
- test/lib.sh
See #85 for details. An important implementation detail: catalog images themselves are no longer mirrored in `create`. Instead the images specified in the file-based catalog (DC) packaged into archive(s) are mirrored and treated as generic images, and `publish` will build and push catalog image directly using `docker buildx build --push`.
Closes #85
> feat(operators): rebuild, push catalog images during publish

- README.md
- pkg/bundle/publish/catalog_images.go
- pkg/bundle/publish/catalog_images_test.go
- pkg/bundle/publish/options.go
Made some stuff removed in #108 an optional feature, so those who do want multi-arch have an escape hatch.
> feat(publish): optionally use 'docker buildx build' for multi-arch

- Makefile
- test/e2e-prow.sh
- test/prow/lib.sh
- test/prow/setup-testdata.sh
**Tested:**
URL: https://prow.sfxworks.net/view/s3/prow-6664d1e2-4f1e-40ff-861c-047120830ff6/pr-logs/pull/sfxnet_bundle/1/presubmit-test-pull/1454222380447567872 note, shows failure due to permissionless mode configured for OpenShift CI
**What this contains:**
Make-e2e test modified for prow
- Prow sidecar builds and registries ref with terminating completion: ref https://kubernetes.io/docs/tasks/configure-pod-container/share-process-namespace/
- Test type: 'spc_t' for buildkitd rootless against OpenShift CI - ref Rootless on OpenShift without SELinux override moby/buildkit#1634 Note: This PR contains this test as privileged pods are not permitted in our CI environment.
**Planned:**
Split image registry into online & offline registries
Cleanup command/rerun command to adjust for new make …
> Prow initial test

- pkg/cli/mirror/create.go
- pkg/cli/mirror/mirror.go
- pkg/cli/mirror/publish.go
- pkg/cli/mirror/publish_test.go
- pkg/cli/options.go
Closes #124 
Blocked by #150 
Publishing uses a local backend
Publishing uses a registry backend
This has been tested using the e2e test and tested locally with an registry using auth.
The publishing unit test has been updated, but the UUID check has been removed since this will now be seen as an empty workspace.
> feat(publish): add registry as default backend for publishing

- README.md
- pkg/bundle/files.go
- pkg/cincinnati/cincinnati.go
- pkg/cincinnati/cincinnati_test.go
- pkg/cli/mirror/describe/describe.go
- pkg/cli/mirror/list/operators.go
- pkg/cli/mirror/list/releases.go
- pkg/cli/mirror/mirror.go
- pkg/cli/mirror/publish.go
- pkg/cli/mirror/release.go
This PR completes the implementation for the `oc-mirror describe` command and the release and operator discovery portions of `oc-mirror list`.
Closes #120
Closes #42
> UX implementation for list releases, operators, and describe

- pkg/cli/mirror/create.go
- pkg/cli/mirror/create_test.go
Only add OPM image when catalogs are configured and not previously added to metadata. Also minor refactoring
Fixes #111
Unit and e2e
* Hardware:
* Toolchain:
* SDK:
> fix(operator): only add OPM image when needed

- README.md
- pkg/bundle/files.go
- pkg/cincinnati/cincinnati.go
- pkg/cincinnati/cincinnati_test.go
- pkg/cincinnati/find.go
- pkg/cincinnati/find_test.go
- pkg/cli/mirror/create.go
- pkg/cli/mirror/list/updates.go
- pkg/cli/mirror/publish.go
- pkg/cli/mirror/publish_test.go
- pkg/cli/mirror/release.go
- pkg/config/v1alpha1/config_types.go
- pkg/metadata/storage/storage.go
This adds and refactors the functionality that processes release payloads. Along with downloading updates between the requested release and the current release, it also adds the ability to download the latest version in the channel on a differential run.
Note: This will only download releases between the latest version downloaded in a channel to the requested version. If the version exists in multiple channels, the target channel will be searched for that version as well.
Closes #119
> feat: add process release upgrades with cincinnati

- pkg/cincinnati/cincinnati.go
- pkg/cincinnati/cincinnati_test.go
- pkg/cli/mirror/release.go
This adds the target channel as the latest channel when `FindReleases` returns an `ErrNoPreviousRelease` error
Existing tests
> fix: add target channel as channel on new runs

- go.mod
- go.sum
- pkg/cli/mirror/operator.go
- pkg/config/v1alpha1/config_types.go
`IncludeAdditively: false` directs the differ to ignore all other operator packages/channels/versions except those specified in the config. `IncludeAdditively: true` gives the diff behavior prior to this PR.
Closes #65
/kind feature
> feat(operator): use newer catalog differ to prune content by omission

- .gitignore
- docs/imageset-config-ref.yaml
Switch example comment syntax to be yaml compliant without removing the comments. Ignore local copy of config file
I used yq to validate the example config yaml file. This failed originally due to the << and >> characters.
> Switch example comment syntax to be yaml compliant without removing the comments. Ignore local copy of config file

- pkg/cincinnati/cincinnati.go
- pkg/cincinnati/cincinnati_test.go
- pkg/cincinnati/find.go
- pkg/cincinnati/find_test.go
- pkg/cli/mirror/list/updates.go
- pkg/cli/mirror/release.go
- pkg/cli/mirror/release_test.go
This PR changes the way releases are queued up and processed to make unit testing easier. This allows for testing of what will be downloaded without actually having to contact an external API.
> refactor(releases): refactor GetReleases for easier unit testing

- docs/imageset-config-ref.yaml
- pkg/cli/mirror/options.go
- pkg/metadata/storage/registry.go
- pkg/metadata/storage/registry_test.go
This PR will clean up some of the logic for testing for the existence of metadata in the registry backend. It originally would create a new workspace on any HTTP error and now it will only create a new workspace for the `404` error code. Also clarified the `SkipTLS` description to explain that this means using plain HTTP.
> fix: fix logic for returning ErrMetadataNotExist for registry backend

- pkg/cincinnati/cincinnati_test.go
- pkg/cli/mirror/catalog_images.go
- pkg/cli/mirror/catalog_images_test.go
- pkg/cli/mirror/mirror.go
- pkg/cli/mirror/publish_test.go
- pkg/cli/mirror/release_test.go
- pkg/metadata/storage/registry_test.go
- pkg/metadata/storage/storage_test.go
This PR adds a push permissions check before publishing image to registry
Fixes #196 
> feat: adding permissions check before publishing to disconnected reg

- pkg/cli/mirror/mirror.go
- pkg/cli/mirror/mirror_test.go
- Unit test arg parsing in `mirror`
- Create dir for user
* Hardware:
* Toolchain:
* SDK:
/kind bug
> fix(mirror): add arg parse tests and create output dir for user

- pkg/cli/mirror/list/operators_test.go
- pkg/cli/mirror/list/releases_test.go
- pkg/cli/mirror/mirror.go
- pkg/cli/mirror/mirror_test.go
This PR changes the image reference passed to `oc-mirror` to add the user-defined namespace.
> fix: add namespace to check push permissions ref

- Makefile
- test/e2e-prow.sh
- test/prow/lib.sh
- test/prow/test-operator-catalog.sh
- test/prow/test-simple-image.sh
Amendments for https://github.com/openshift/oc-mirror/pull/207 based on prow job results
- Erroneous tests get captured and still exit 0 so CI job knows to end additional sidecars instead of timing out
- Syntax and pathing issues fixed
```
#prereqs installed &
podman run -p 5000:5000 registry:2 &
podman run -p 5001:5001 quay.io/samwalke/oc-mirror-registry &
make test-prow
```
> Prow PR fix

- Makefile
- test/lib.sh
This PR adds `-mod=mod` flag to `go install` command on our e2e test
N/A/, Must be tested in CI.
> chore: add mod flag to go install for crane

- pkg/archive/archive_test.go
- pkg/bundle/files_test.go
- pkg/bundle/image_test.go
- pkg/cincinnati/cincinnati_test.go
- pkg/cincinnati/find_test.go
- pkg/cli/mirror/additional_test.go
- pkg/cli/mirror/catalog_images_test.go
- pkg/cli/mirror/create_test.go
- pkg/cli/mirror/helm_test.go
- pkg/cli/mirror/manifests_test.go
- pkg/cli/mirror/publish_test.go
- pkg/cli/mirror/release_test.go
- pkg/image/association_test.go
- pkg/metadata/storage/local_test.go
- pkg/metadata/storage/registry_test.go
- pkg/metadata/storage/storage_test.go
This PR changes unit test function names that do not comply with Go convention for uniformity.
N/A
> chore: change all unit test names to comply with Go convention

- pkg/cli/mirror/additional.go
- pkg/cli/mirror/create.go
- pkg/cli/mirror/create_test.go
- pkg/cli/mirror/mirror.go
- pkg/cli/mirror/mirror_test.go
- pkg/cli/mirror/options.go
- pkg/cli/mirror/release.go
- pkg/cli/options.go
- pkg/metadata/storage/registry.go
This PR marks the `filter-by-os` flags as hidden temporarily so the default and be used and the OpenShift release architecture can be more thoroughly vetted.
> chore: mark filter-by-os flag as hidden temporarily

- Makefile
- go.mod
- go.sum
- pkg/bundle/image.go
- pkg/cli/mirror/additional.go
- pkg/cli/mirror/additional_test.go
- pkg/cli/mirror/catalog_images.go
- pkg/cli/mirror/catalog_images_test.go
- pkg/cli/mirror/create.go
- pkg/cli/mirror/helm.go
- pkg/cli/mirror/list/updates.go
- pkg/cli/mirror/mirror.go
- pkg/cli/mirror/operator.go
- pkg/cli/mirror/options.go
- pkg/cli/mirror/publish.go
- pkg/cli/mirror/release.go
- pkg/metadata/store.go
- test/lib.sh
This update incorporates changes from the operator-registry
upstream that allows the use of untrusted HTTPS. It also adds a
fix for empty packages from that repo.
Fixes #209
Fixes #272
The PR updates the `operator-registry` dependency to include the TLS disable support and empty package pruning. Update to `oc-mirror` flags include `dest-use-http` and `source-use-http`
> fix: adds ability to disable TLS uniformly throughout oc-mirror

- go.mod
- go.sum
- pkg/cli/mirror/catalog_images.go
- pkg/operator/doc.go
- pkg/operator/merge.go
- pkg/operator/merge_test.go
This PR adds merge functionality to `oc-mirror` for file-based catalogs. This had been implemented in a fork of `operator-registry` and it has been moved to `oc-mirror`.
> chore(catalog): add merge functionality for file-based catalogs

- pkg/archive/archive_test.go
- pkg/cli/mirror/manifests.go
- pkg/cli/mirror/manifests_test.go
- pkg/cli/mirror/mirror.go
- pkg/cli/mirror/operator.go
- pkg/cli/mirror/publish.go
- pkg/cli/mirror/release.go
- pkg/config/credentials.go
- pkg/config/v1alpha1/register.go
- pkg/image/association.go
This PR adds ICSPTypes to implement specific processing steps per type and to group ICSP objects by type. This fixes issues seen with incorrect OCP release ICSP.
To test:
```
apiVersion: mirror.openshift.io/v1alpha1
mirror:
ocp:
channels:
- name: stable-4.9
versions:
- 4.8.26
graph: true
```
The ICSP for the release will require the following source and mirror (example):
```
- mirrors: [example.com/openshift/release]
source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
- mirrors: [example.com/openshift/release]
source: quay.io/openshift-release-dev/ocp-release
```
> fix(publish): implements ICSPTypes for processing and grouping per type

- go.sum
- pkg/cli/mirror/catalog_images.go
- pkg/metadata/storage/registry.go
To achieve compatibility with quay, changes need to be made to account
for unauthorized errors when an image does not exist. A CheckPushPermission
check is done before querying for an image to ensure the user is authorized.
Fixes #273
This PR adds push permission checks before querying for existing images (during registry metadata and catalog building) to handle 401 responses from Quay. This should be a temporary fix.
> fix(storage): adds a pull permission check to respond to 401 errors

- images/cli/Dockerfile.ci
This PR adds a Dockerfile for CI image builds
Must backport to `release-4.10`
> chore: add Dockerfile for CI builds

- Makefile
Add mod vendor flag to Makefile to avoid downloading existing dependencies
> chore: set mod flag to vendor on Makefile

- pkg/cli/mirror/create.go
- pkg/cli/mirror/create_test.go
- pkg/cli/mirror/mirror.go
- test/lib.sh
- test/testcases.sh
Checks if there are any blob differences during the process. If there are no changes stop the process to avoid unnecessary sequence update / tar files with only the manifests in. 
Fixes #190
> Stopping the process when no changes are found between runs. [190]

- pkg/bundle/image.go
- pkg/cli/mirror/additional.go
- pkg/cli/mirror/additional_test.go
- pkg/cli/mirror/catalog_images.go
- pkg/cli/mirror/create.go
- pkg/cli/mirror/create_test.go
- pkg/cli/mirror/helm.go
- pkg/cli/mirror/helm_test.go
- pkg/cli/mirror/manifests.go
- pkg/cli/mirror/manifests_test.go
- pkg/cli/mirror/mirror.go
- pkg/cli/mirror/mirror_test.go
- pkg/cli/mirror/operator.go
- pkg/cli/mirror/options.go
- pkg/cli/mirror/pack.go
- pkg/cli/mirror/publish.go
- pkg/cli/mirror/publish_test.go
- pkg/cli/mirror/release.go
- pkg/cli/mirror/release_test.go
- pkg/cli/mirror/testdata/configs/test.yaml
- pkg/config/v1alpha1/storage_config_types.go
- pkg/image/association.go
- pkg/image/association_test.go
- pkg/image/image_types.go
- pkg/image/mapping.go
- pkg/image/mapping_test.go
- pkg/metadata/store.go
This PR adds a TypedImageMapping type that is used to decouple the Associations type from Imageset creation operators and ICSP creation from Imageset publishing operations to make it possible to use existing Imageset creation functionality without the requirement of storing images on disk.
Fixes #285 
> feat: remove disk space requirement for mirror to mirror transfer

- images/cli/Dockerfile.ci
This PR adds label  `LABEL io.openshift.release.operator=true` to Dockerfile to get into OCP release payload
> chore: add required operator label to Dockerfile

- Makefile
- go.mod
- pkg/cli/mirror/version/version.go
- pkg/cli/mirror/version/version_test.go
- vendor/modules.txt
This PR changes the Makefile and  `oc-mirror` version command to use generated version info during build time with LDFLAGS.
> chore: adds dynamic version info for version command with ldflags

- .gitignore
- Makefile
- docs/dev/getting-started.md
- test/integration/Makefile
- test/integration/ansible.cfg
- test/integration/connect.sh
- test/integration/hosts
- test/integration/requirements.txt
- test/integration/requirements.yml
- test/integration/vars.yml
This change brings the [oc-mirror-e2e](https://github.com/jharmison-redhat/oc-mirror-e2e) Ansible collection into an easy-to-execute target in the root Makefile.
Fixes #325 
```sh
export AWS_ACCESS_KEY_ID=<my actual AWS access key ID>
export AWS_SECRET_ACCESS_KEY=<my actual AWS secret access key>
export CONSOLE_REDHAT_COM_PULL_SECRET='<my actual pull secret, retrieved from console.redhat.com>'
make test-integration
```
Fedora 35 on amd64
Software relevant to test execution:
GNU Make 4.3
Python 3.10.2
curl 7.79.1
UnZip 6.0.0
> [CI] Add integration environment

- .github/ISSUE_TEMPLATE.md
- .gitignore
- pkg/cli/log.go
- pkg/cli/options.go
This change ensures logs from oc library calls make it
into the logfile as well as standard out.
This PR adds the `oc-mirror` log file as an output destination when calling `oc` libraries.
Fixes #22 
> chore: adds the log file to IOStream configuration for Out and ErrOut

- pkg/archive/archive.go
- pkg/cincinnati/cincinnati.go
- pkg/cincinnati/cincinnati_test.go
- pkg/cincinnati/client.go
- pkg/cincinnati/find.go
- pkg/cincinnati/find_test.go
- pkg/cli/mirror/list/releases.go
- pkg/cli/mirror/list/updates.go
- pkg/cli/mirror/pack.go
- pkg/cli/mirror/release.go
- pkg/cli/mirror/release_test.go
- pkg/config/credentials.go
- pkg/image/mapping.go
- pkg/image/resolve.go
- pkg/metadata/storage/local.go
OCP and OKD releases need to be handled by the same methods but require
different concrete types due to differences in API endpoints and query
parameters.
This PR refactors the Cincinnati package to add a Client interface to allow flexibility when mirroring multiple release types (e.g. OCP and OKD). The `list updates` command has been altered as well to provide an upgrade path from the last specified maximum version to the latest version in the currently requested channel.
Relates to #315 
> refactor(release): adds a Client interface for Cincinnati client types

- Makefile
- test/integration/Makefile
This undoes several temporary changes from #355 to get us through rehearsals on [the release PR](https://github.com/openshift/release/pull/26915).
> Enable CI rehearsals to hit the target

- Makefile
- go.mod
- pkg/cli/mirror/version/version.go
- pkg/cli/mirror/version/version_test.go
- vendor/modules.txt
This PR backports changes to the `oc-mirror` version command to the `release 4.10` branch to fix the Bugzilla issue below.
Related to #328 
Fixes Bugzilla issue 2056752
> Bug 2058267: Add clarifying information to oc-mirror version command and remove alpha.3 from semver

- go.mod
- pkg/bundle/image.go
- pkg/bundle/image_test.go
- pkg/cli/mirror/mirror.go
- pkg/cli/mirror/operator.go
- pkg/cli/mirror/publish.go
- pkg/cli/mirror/release.go
- pkg/image/association.go
- pkg/image/association_builder.go
- pkg/image/association_builder_test.go
- pkg/image/association_test.go
- pkg/image/credentials.go
- vendor/modules.txt
This PR adds methods to allow `AssociationSet` information to be gathered from local and remote sources.
Related to #302 
> feat(image): adds method to create Associations from remote sources

- pkg/operator/merge.go
- pkg/operator/merge_test.go
This PR fixes a bug in catalog merging which results in multiple channel heads. It also adds validation during catalog processing to verify the validity of FBCs during the mirroring process.
1. Spin up two registries 
2. Copy the older catalog to the connected registry
`skopeo copy docker://registry.redhat.io/redhat/redhat-operator-index:v4.9-1646041330 docker://localhost:5000/fake/redhat-operator-index:v4.9`
4. Run oc-mirror with below config
```
storageConfig:
local:
path: metadata
mirror:
operators:
- catalog: localhost:5000/fake/redhat-operator-index:v4.9
headsOnly: false # References latest version of each operator in catalog (true is the default value and can be omitted) …
```
> Bug 2060837: resolves multiple channel heads in merged catalogs

- pkg/cli/mirror/additional.go
- pkg/cli/mirror/mirror.go
- pkg/cli/mirror/options.go
- pkg/image/association_builder.go
- pkg/image/association_builder_test.go
This PR adds fixes for errors that occur when missing images are provided in the config (via catalog or additional/helm). This allows `continue-on-error` to log a warning about the missing images instead of throwing an error if specified.
Related to #359 
> Bug 2063955: fix(mirror): adds back continue-on-error use for missing images

- test/integration/scripts/common.sh
Simple fix for [permissions errors in CI](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/27189/rehearse-27189-pull-ci-openshift-oc-mirror-main-integration/1508459466041856000#1:build-log.txt%3A41) which is in line with what [some other projects do](https://github.com/openshift/release/blob/4b2ccd70ff5b1e7f689996d05d49339a7fc9253a/ci-operator/config/netobserv/network-observability-console-plugin/netobserv-network-observability-console-plugin-main.yaml#L29)
> Added HOME for CI

- pkg/archive/archive.go
- pkg/bundle/init.go
- pkg/cli/mirror/mirror.go
- pkg/cli/mirror/publish.go
- pkg/cli/mirror/release-configmap.yaml
- pkg/cli/mirror/release.go
- pkg/config/metadata.go
Fixes #125 
Each release now downloads its signature and creates a configmap from the signature. This is used during platform upgrades.
Still to do: 
- How should this be packaged for offline usage. I think it needs to go into the tar structure when using file:// or into the results directory if using publish. Similarily if you go from file to registry it should use the results directory. @jpower432 thoughts?
> Creating the release signature configmap for use during upgrades #125

- go.mod
- go.sum
- vendor/github.com/operator-framework/api/pkg/constraints/constraint.go
- vendor/github.com/operator-framework/api/pkg/validation/internal/csv.go
- vendor/github.com/operator-framework/api/pkg/validation/internal/good_practices.go
- vendor/github.com/operator-framework/operator-registry/alpha/action/diff.go
- vendor/github.com/operator-framework/operator-registry/alpha/action/testdata/foo-index-v0.2.0-declcfg/foo/index.yaml
- vendor/github.com/operator-framework/operator-registry/alpha/declcfg/declcfg.go
- vendor/github.com/operator-framework/operator-registry/alpha/declcfg/diff.go
- vendor/github.com/operator-framework/operator-registry/pkg/containertools/runner.go
- vendor/github.com/operator-framework/operator-registry/pkg/image/containerdregistry/resolver.go
- vendor/github.com/operator-framework/operator-registry/pkg/registry/registry_to_model.go
- vendor/github.com/operator-framework/operator-registry/pkg/registry/types.go
- vendor/github.com/operator-framework/operator-registry/pkg/sqlite/load.go
- vendor/modules.txt
This change updates the operator-registry dependency to
commit de36104087733013025629d80bf8445045a8a6e7 to resolve
a bug when processing cyclic dependencies in operator bundles.
Fixes BZ 2065832
> Bug 2069307: bump operator-registry dep v1.21.1

- test/operator/bundles/bar/bar-bundle-v1.0.0/metadata/annotations.yaml
- test/operator/bundles/foo/foo-bundle-v0.2.0/metadata/annotations.yaml
- test/operator/bundles/foo/foo-bundle-v0.3.1/metadata/dependencies.yaml
- test/operator/publish_images.py
- Forces publishing in docker image format instead of OCI image format
- Aligns bundle data and metadata with old hand-crafted indexes
Fixes #404 
Fixes #403 
- `make publish-catalog`
- `make test-e2e`
> Correct testdata publishing

- pkg/api/v1alpha2/types_include_config.go
- pkg/api/v1alpha2/types_include_config_test.go
- pkg/api/v1alpha2/types_metadata.go
- pkg/cli/mirror/catalog_images.go
- pkg/cli/mirror/create.go
- pkg/cli/mirror/create_test.go
- pkg/cli/mirror/mirror.go
- pkg/cli/mirror/operator.go
- pkg/cli/mirror/pack.go
- pkg/cli/mirror/pack_test.go
- pkg/cli/mirror/release.go
- pkg/config/metadata.go
- pkg/image/association_set.go
- pkg/image/mapping.go
- pkg/metadata/store.go
- pkg/metadata/store_test.go
- pkg/metadata/testdata/catalogs/test.registry/catalog/sha256:30c794a11b4c340c77238c5b7ca845752904bd8b74b73a9b16d31253234da031/index/index.yaml
- pkg/operator/catalog_dir.go
- pkg/operator/catalog_dir_test.go
- pkg/operator/declcfg_to_includecfg.go
- pkg/operator/declfg_to_includecfg_test.go
- test/testcases.sh
When merging the catalog, unintentional changes to the upgrade and pruned bundles can be created in the target FBC generated by oc-mirror.
To remove the requirement to merge FBCs, package ranges are being used in metadata for heads-only workflows to generate FBCs that are scoped per the configuration instead of generating differential FBCs and merging with previous FBCs. The OCP releases heads only workflow has been updated work in the same way. To achieve the same optimization in regards to downloaded images, all images in the image mapping during each run are validated against the metadata to make sure they do not exist in PastAssociations.
**Heads Only to Range**: Just the specified range will be downloaded the previous starting version between be erased.
**Range to Heads Only**: …
> refactor: heads only workflow to remove the requirement to merge FBCs

- .gitignore
- pkg/cincinnati/cincinnati.go
- pkg/cincinnati/cincinnati_test.go
Currently, the prefix for the target channels is being inferred from the source channel
when calculating Cincinnati graphs. This can cause an issue when the prefix of the channel
is different for the starting and target version. Now, the starting prefix is only
used when calculating upgrades through the channel until the target major and minor version
is reached.
Fixes #292 
```
storageConfig:
local:
path: metadatafake
mirror:
platform:
channels:
- name: stable-4.10
- name: fast-4.10 
```
`oc-mirror --config imageset-config.yaml file://archives`
> Bug 2075050: fix: adds handling for channel with different prefixes in cincinnati.go

- pkg/cli/mirror/list/releases.go
- pkg/cli/mirror/mirror.go
- pkg/cli/mirror/prune.go
- pkg/cli/mirror/prune_test.go
- pkg/cli/mirror/publish.go
- pkg/image/association_set.go
- pkg/image/builder/image_builder_test.go
- pkg/metadata/storage/registry.go
Adds image pruning based on metadata functionality to mirroring workflows 
Fixes #302
Blocked by #387 
* Hardware:
* Toolchain:
* SDK:
Notes: 
Overall docs updates are coming on a separate PR
> feat(mirror): image pruning from registry on mirroring workflows

- pkg/cli/mirror/describe/describe.go
- pkg/cli/mirror/describe/describe_test.go
- pkg/cli/mirror/list/list.go
- pkg/cli/mirror/list/updates.go
- pkg/cli/mirror/list/updates_test.go
…of other list commands
With updates to the oc-mirror list commands `list updates` is left disjointed with different
output styles. This also makes the config path an argument since it is a required input
to get updated information.
Adds unit tests for describe package
^^
Manually and updates unit tests
> refactor(ux): list updates ux and adds unit tests for describe command

- pkg/cli/mirror/mirror.go
- pkg/cli/mirror/options.go
- pkg/cli/mirror/pack.go
- pkg/cli/mirror/publish.go
- pkg/cli/mirror/publish_test.go
- pkg/metadata/storage/registry.go
Currently, if imagesets are published out of sequence, the metadata check
will fail. If used with an imageset generated with the --ignore-history flag,
--skip-metadata-check allows for metadata overwrites in the case that imageset
archives are lost or cannot be published.
Closes #408 
^^
```
storageConfig:
local:
path: metadata
mirror:
additionalimages:
```
```
oc-mirror --config imageset-config.yaml file://archives 
oc-mirror --config imageset-config.yaml file://archives --ignore-history
oc-mirror --config imageset-config.yaml file://archives --ignore-history
oc-mirror …
```
> feat(mirror): adds a skip-metadata-check flag to mirror command

- pkg/cli/mirror/publish.go
- test/e2e/lib/check.sh
- test/e2e/lib/util.sh
- test/e2e/lib/workflow.sh
- test/e2e/testcases.sh
This fixes a regression introduced by #412 to the ability to prune in disk
to mirror workflows
^^
* Hardware:
* Toolchain:
* SDK:
> fix(publish): adds back evaluation of current associations in publish.go

- Makefile
With the addition of build-machinery-go, the build is occurring
before the clean when running the all target. The clean has
been removed and will be optional when directly running the all target.
The clean prerequisite is staying on the hack-build target to maintain reproducible
builds.
> fix(makefile): remove clean from all target in Makefile

- pkg/cli/mirror/additional.go
- pkg/cli/mirror/catalog_images.go
- pkg/cli/mirror/operator.go
- pkg/image/association_builder.go
- pkg/image/builder/image_builder.go
- pkg/image/digest.go
- pkg/image/mapping.go
- pkg/image/mapping_test.go
- test/e2e/configs/imageset-config-full-digest.yaml
- test/e2e/lib/util.sh
- test/e2e/lib/workflow.sh
- test/e2e/testcases.sh
When reading the catalog reference provided by the configuration,
the run method in operator.go was modifying the reference in a way
that resulted in the reference differing from the mapping. The DockerClientDefaults
call has been removed and a SetDefaults method has been added to TypedImage as a way to set
fields in a standard way on this type.
Closes #423 
```
storageConfig:
local:
path: metadata
mirror:
operators:
- catalog: quay.io/redhatgov/oc-mirror-dev@sha256:f74bd3f08c971fafd64c9c95fe9839f54bf776d00ac363f2c3882c0e37c946ef
```
`oc-mirror --config imageset-config.yaml docker://localhost:5000/test`
This should not result in `error: repository name must have …
> fix(mapping): removes DockerClientDefaults from ctlgRef

- pkg/operator/declcfg_to_includecfg.go
- pkg/operator/declfg_to_includecfg_test.go
An error in the binary search method in the operator package
in declcfg_to_includecfg.go was causing a stack overflow
> fix: modifies binary search algorithm to keep from a stack overflow

- pkg/cli/mirror/release.go
Currently, the release images are being added as an additional key in the
mapping instead of overwriting the existing key pair. This is causing the
final release images to be written to the wrong repo.
Fixes #439
> fix: modifies release.go to remove and add release images to the mapping

- docs/dev/getting-started.md
- test/integration/Makefile
- test/integration/ansible.cfg
- test/integration/hosts
- test/integration/hosts.yml
- test/integration/requirements.yml
- test/integration/scripts/build-image.sh
- test/integration/scripts/ci-mock.sh
- test/integration/scripts/ci-prereqs.sh
- test/integration/scripts/common.sh
- test/integration/scripts/connect.sh
- test/integration/scripts/post-run.sh
- test/integration/scripts/pre-run.sh
- test/integration/scripts/run.sh
- test/integration/vars.yml
- Align mock environment permissions with CI environment permissions (writable non-secret volumes, writable repo, non-writable otherwise)
- Inherit updates to collection to improve behavior in CI on long-running tasks
- Collect oc-mirror and openshift-install logs from every phase of tests
Fixes #326 
The integration test slash command for ci-operator
> [CI] Correct CI Integration target

- pkg/cincinnati/cincinnati.go
- pkg/cincinnati/cincinnati_test.go
Currently, channels with the same major and minor version with different
prefixes are processed in a way that causes errors when entering a loop to
calculate for higher version channels. This change adds a check before
processing for prefix differences and handles them accordingly.
Backport changes from #411 for 4.10
```
apiVersion: mirror.openshift.io/v1alpha1
storageConfig:
local:
path: metadatafake
mirror:
ocp:
channels:
- name: stable-4.10
- name: fast-4.10 
```
`oc-mirror --config imageset-config.yaml file://archives`
Run again
`oc-mirror --config imageset-config.yaml file://archives`
> Bug 2075051: [release-4.10] fix: adds handling for channel with different prefixes in cincinnati.go

- docs/examples/imageset-config-filter-catalog.yaml
- docs/imageset-config-ref.yaml
- go.mod
- go.sum
- pkg/api/v1alpha2/types_include_config.go
- pkg/api/v1alpha2/types_include_config_test.go
- pkg/cli/mirror/initcmd/initcmd.go
- pkg/cli/mirror/initcmd/initcmd_test.go
- pkg/cli/mirror/operator.go
- pkg/config/load.go
- pkg/config/load_test.go
- pkg/config/testdata/config/valid.yaml
- pkg/config/validate.go
- pkg/metadata/store.go
- pkg/metadata/store_test.go
- pkg/operator/declcfg_to_includecfg.go
- pkg/operator/declfg_to_includecfg_test.go
- test/e2e/configs/imageset-config-filter-max.yaml
- test/e2e/configs/imageset-config-filter-multi.yaml
- test/e2e/configs/imageset-config-filter-range.yaml
- test/e2e/configs/imageset-config-filter-single.yaml
- test/e2e/testcases.sh
- vendor/github.com/operator-framework/operator-registry/alpha/action/diff.go
- vendor/github.com/operator-framework/operator-registry/alpha/declcfg/diff.go
- vendor/github.com/operator-framework/operator-registry/alpha/declcfg/diff_include.go
- vendor/github.com/operator-framework/operator-registry/alpha/declcfg/load.go
- vendor/modules.txt
This PR adds the ability to specify a `MaxVersion` when package filtering on operators.
It also changes the `MinVersion` and MaxVersion from `semver.Version` types to strings to allow for DeepCopy methods to be used on API types later.
(**Pointing to an operator-registry fork**)
Closes #302 
> feat(operator): allow ranges to be specified for package filtering

- test/integration/requirements.yml
- test/integration/vars.yml
Also update collection to inherit new Mirror Registry changes
This change in the collection makes it easier to test the OpenShift Mirror Registry with a full workflow, including installation of OpenShift from these sources. There are some extra changes exposing a few more variables to make it easier to test some alternate scenarios as well, including changes to the location of the release images for OSUS.
`/test integration`
> [CI] Set integration test to use mirror_registry

- docs/examples/imageset-config-release-alt-arch.yaml
- docs/imageset-config-ref.yaml
- pkg/api/v1alpha2/types_config.go
- pkg/cli/mirror/list/releases.go
- pkg/cli/mirror/list/updates.go
- pkg/cli/mirror/list/updates_test.go
- pkg/cli/mirror/mirror.go
- pkg/cli/mirror/mirror_test.go
- pkg/cli/mirror/options.go
- pkg/cli/mirror/release.go
- pkg/config/defaults.go
- pkg/config/defaults_test.go
- pkg/config/load.go
- pkg/config/validate.go
- pkg/config/validate_test.go
This PR moves the Platform architecture specifications from flags to the ImagesetConfigurationSpec. The default functionality remains unchanged ("amd64"). Since release architectures are handled in a separate manner from image architecture filtering, this has been moved to describe the Platforms in the configuration.
/kind feature
> feat(release): expose architecture filter options for Platforms

- pkg/operator/declcfg_to_includecfg.go
- pkg/operator/declfg_to_includecfg_test.go
In the current implementation, if a package is defined with multiple channels in the current (user-defined) include config, any channels without bundle information set will be recorded as is if another channels has bundle information. This will result in a "Version is empty" error on subsequent runs as the proper minimum bundle version is never set before reconciliation.
This changes processed package level version configuration and channel level version configuration separately so new channels will be processed properly.
Fixes #465
> Bug 2086964: fix(operators): adds better support for packages with multiple channel configurations

- config.yaml
- docs/usage.md
- pkg/cli/mirror/initcmd/initcmd.go
- pkg/cli/mirror/initcmd/initcmd_test.go
This PR removes the required prompting from the `oc-mirror init` command
> Bug 2088130: fix(init): bug/init cmd force prompting

- pkg/cli/mirror/list/releases.go
- pkg/cli/mirror/list/releases_test.go
Currently filter-options only supports filtering by architecture.
This PR changes flags name to filter-by-archs to better reflect
it's purpose and to be compatible with `oc release adm info`.
> Bug 2092887: Rename filter-options flag to filter-by-archs

- pkg/bundle/workspace.go
- pkg/cli/mirror/mirror.go
- pkg/cli/mirror/publish.go
- pkg/cli/mirror/publish_test.go
- pkg/cli/mirror/sequence.go
- pkg/cli/mirror/sequence_test.go
Currently, mirror to mirror operations do not check the sequence number
when publishing since there are no layer differential considerations.
However, sequence checking still needs to be done to ensure the
target namespace is not changed on a differentials run.
Fixes #468
> Bug 2087271: fix(mirror): adds sequence checks for mirror to mirror operations

- pkg/cli/mirror/mirror.go
- pkg/cli/mirror/prune.go
- pkg/cli/mirror/prune_test.go
The PR adds logic to ensure child manifests are deleted in the case the images have multi-arch manifests. The current associations will be evaluated to determine what manifest should be in each repo to allow pruning to work properly when switching from a fully disconnected environment to a partially disconnected one and vice versa.
> Bug 2094866: fix(pruning): handles child manifest deletion and tagged references

- pkg/cli/mirror/mirror.go
- pkg/cli/mirror/publish.go
This PR removes the creation of an extra results directory when using disk to mirror by specifying the output directory
before the unpacking process begins.
Fixes #481 
> Bug 2095347: removes extra results directories when mirroring disk to mirror

- pkg/cli/mirror/publish.go
- pkg/config/metadata.go
- pkg/metadata/storage/registry.go
- pkg/metadata/storage/registry_test.go
This change checks the registry endpoint before continuing `oc-mirror` operations on initial runs.
Fixes #249
> Bug 2098172: Adds validation for inaccessible registry endpoints

- pkg/cli/mirror/mirror.go
- pkg/cli/mirror/mirror_test.go
This PR removes the push permission check with the `manifests-only` flag and is used with a `docker` prefix destination argument.
Fixes Bug 2098610
> This is with a ready-made imageset archive
```
oc-mirror --from mirror_seq1_000000.tar docker://fakehost.com  --manifests-only  -v 9
```
Outcome: Manifests should be written with no registry check
> Bug 2098610: fix(mirror): removes push permission check with manifest-only is used

- pkg/cincinnati/cincinnati.go
- pkg/cli/mirror/list/releases.go
- pkg/cli/mirror/list/releases_test.go
- pkg/config/validate.go
- pkg/config/validate_test.go
This change removes the release architecture validation to allow error
in architecture to be handled by the respective Cincinnati API calls.
Fixes #500
Tested with this imageset config
```
storageConfig:
local:
path: ./
mirror:
platform:
architectures:
- arm64
channels:
- name: stable-4.10
```
> OCPBUGS-617: fix: remove release architecture validation at the config level

- pkg/cli/mirror/operator.go
- pkg/image/image.go
- pkg/image/image_test.go
This is the first part of the implementation described in [the design document](https://docs.google.com/document/d/1-TESqErOjxxWVPCbhQUfnT3XezG2898fEREuhGena5Q/edit#heading=h.mqgxt28qr45k)
It creates ParseReference function in the image package, that wraps around imagesource.ParseReference, adding support for `oci:` prefix
This new function is used instead of imagesource.ParseReference in pkg/cli/mirror/operator.go
Fixes # [WRKLDS-456](https://issues.redhat.com//browse/WRKLDS-456) - Partial
- pkg/image/image_test.go
- [NA] I have made corresponding changes to the documentation
> WRKLDS-456 - Wrapper function for ParseReference

- pkg/cincinnati/cincinnati.go
- pkg/cincinnati/client.go
In order to be able to mirror 4.next builds and the latest nightly
releases, it is handy to have an environment variable for CI/devs to
mirror from development registry graphs.
The two env variables that this defines are:
UPDATE_URL_OVERRIDE: URL to a release graph
VERSION_FILTER: A golang regular expression to filter out disconnected
graphs that are provided by the aforementioned URL.
Tested locally:
UPDATE_URL_OVERRIDE=https://{redacted}/graph oc-mirror -c imageset.yaml --dest-skip-tls docker://${HOSTNAME}:5000/
imageset:
```
archiveSize: 4
storageConfig:
registry:
imageURL: toni.openshift-agent.cloud:5000/mirror/cicandidate-oc-mirror-metadata
skipTLS: true
mirror:
platform: …
```
> updateURL: Allow overriding for CI builds

- pkg/cli/mirror/copy.go
- pkg/cli/mirror/copy_test.go
- pkg/cli/mirror/manifests.go
- pkg/cli/mirror/manifests_test.go
- pkg/image/image.go
- pkg/image/image_test.go
- pkg/image/mapping.go
- pkg/image/mapping_test.go
This PR contains fixes to multiple issues encountered by QE:
* ICSP generation: Fix the mirror destination of the catalog: The URL should contain the original namespace
* ICSP generation: Fix the source for relatedImages: the URL should contain the original image reference as found in the catalog
* This uses OriginalRef, which was added to TypedImage 
* Move parseImageName and trimProtocol to image package
Fixes # OCPBUGS-3414
Unit tests
* ImageSetConfig:
```yaml
mirror:
operators:
#rhop
- catalog: registry.redhat.io/redhat/redhat-operator-index:v4.12
originalRef: registry.redhat.io/redhat/redhat-operator-index:v4.12
packages:
```
* Command …
> OCPBUGS-3414: Fix: fixes issues encountered by QE

- pkg/cli/mirror/cincinnati_graph_image.go
move to the new endpoin hosted on redhat domain api.openshift.com 
to download the tarball for openshift update service (cincinnati) graph-data.
Also changes the existing logic and extracts the tarball before creating the 
container image.
As this is an init container or will be used with cincinnati plugin, we're using 
a stripped down ubi image (ubi-micro)
Fixes [OTA-831](https://issues.redhat.com//browse/OTA-831)
> [graph-data] use new cincinnati endpoint to download tarball

- imstcfg.yaml
- pkg/api/v1alpha2/types_config.go
- pkg/cli/mirror/additional.go
- pkg/cli/mirror/additional_test.go
- pkg/cli/mirror/catalog_images.go
- pkg/cli/mirror/cincinnati_graph_image.go
- pkg/cli/mirror/create.go
- pkg/cli/mirror/create_test.go
- pkg/cli/mirror/fbc_operators.go
- pkg/cli/mirror/fbc_operators_test.go
- pkg/cli/mirror/manifests_test.go
- pkg/cli/mirror/mirror.go
- pkg/cli/mirror/mirror_test.go
- pkg/cli/mirror/operator.go
- pkg/cli/mirror/publish.go
- pkg/image/association_builder_test.go
- pkg/image/builder/image_builder.go
- pkg/image/convert.go
- pkg/image/convert_test.go
- pkg/image/image.go
- pkg/image/image_test.go
- pkg/image/mapping.go
- pkg/image/mapping_test.go
- pkg/metadata/store.go
- test/e2e/artifacts/configs/index.yaml
- test/e2e/lib/util.sh
- test/e2e/lib/workflow.sh
This change allows for the the incremental and pruning functionality to work for the oci feature
- [x ] New feature (non-breaking change which adds functionality)
The update was tested as follows 
- Add an oci catalog in the imagesetconfig (i.e cincinnati-operator) and mirror to remote registry
- Update oci catalog in the imagesetconfig (remove cincinbati-operator and add openshift-logging) and mirror
- Verfiy the mapping.txt had correct entry
- Verify the .metatadat.json file sequence was bumped
- Verify the console logs for both oc-mirror and remote registry (see below)
```
Pruning 6 manifest(s) from repository test-lmz/openshift-update-service/openshift-update-service-rhel8-operator
Pruning 3 manifest(s) from repository …
```
> CFE-768: Update to allow for incremental and pruning for oci feature

- docs/design/workflows.md
- docs/examples/imageset-config-catalog-full.yaml
- docs/examples/imageset-config-catalog-headsonly.yaml
- docs/examples/imageset-config-filter-catalog.yaml
- docs/imageset-config-ref.yaml
This update imageset examples under `docs/examples` and updates the `imageset-config-ref.yaml` to provide valid catalog configuration examples.
N/A, docs PR
> docs: adds clarification to imageset reference and examples

- pkg/api/v1alpha2/types_config.go
- pkg/api/v1alpha2/types_config_test.go
- pkg/cli/mirror/fbc_operators.go
- pkg/cli/mirror/fbc_operators_test.go
- pkg/cli/mirror/manifests.go
- pkg/cli/mirror/mirror.go
- pkg/cli/mirror/operator.go
- pkg/metadata/store.go
TargetCatalog can contain several component-paths, allowing the user to set the namespace to which the catalog will be copied. 
It will later replace TargetName.
Changes to be committed:
modified:   pkg/api/v1alpha2/types_config.go
new file:   pkg/api/v1alpha2/types_config_test.go
modified:   pkg/cli/mirror/fbc_operators.go
modified:   pkg/cli/mirror/fbc_operators_test.go
modified:   pkg/cli/mirror/manifests.go
See https://issues.redhat.com/browse/CFE-764?filter=-1 for relevant motivation and context. 
Fixes # [CFE-764](https://issues.redhat.com//browse/CFE-764)
Changes in GetUniqueName and ICSP generation (determining namespace scope of mirrored images) have been changed for catalogs. This might have impacts on the way images are mirrored or …
> CFE-764 : Introduce v1alpha2.Operator.TargetCatalog 

- pkg/cli/mirror/mirror.go
- pkg/cli/mirror/options.go
- pkg/cli/mirror/prune.go
Add skip pruning flag that will globally skip all pruning functionality in oc-mirror
- [ x] New feature (non-breaking change which adds functionality)
Locally on docker server registry
- Mirrored an additional image `registry.redhat.io/ubi8/ubi:latest` (with so flag set i.e --skip-pruning)
- Update image set config with a `registry.redhat.io/ubi9/ubi:latest` and removed previous image
- Verified that the logs for both oc-mirror and registry showed that the ubi8 image was pruned/deleted
- Clean the registry and started the same process as aboved but with --skip-pruning flag set
- Verified message displayed that this feature is not supported
- Verified that no images were pruned or deleted
* Hardware:
* …
> CFE-739: Add skip pruning flag and logic

- TROUBLESHOOTING.md
- pkg/cli/mirror/fbc_operators.go
- pkg/image/image.go
OCPBUGS-9903 - docs: add information about unsupported scenario
The scenario is when a user copied a catalog to the same location more than once and try to mirror it.
The following commands were executed:
```skopeo copy docker://registry.redhat.io/redhat/redhat-operator-index:v4.11 oci:///home/aguidi/rhoc-ying  --remove-signatures ```
and 
```skopeo copy docker://registry.redhat.io/redhat/redhat-operator-index:v4.12 oci:///home/aguidi/rhoc-ying  --remove-signatures```
then I tried to mirror using the following command:
```./bin/oc-mirror --config ying.yaml  docker://localhost:5000  --use-oci-feature --dest-use-http --dest-skip-tls --dry-run ```
and the following ImageSetConfiguration:
```
storageConfig:
registry: …
```
> docs: add information about unsupported scenario

- pkg/image/image.go
There are some scenarios where an error is expected so it should not print the error message otherwise it will confuse the user.
fixes #576 
Using the command and image set config below:
```./bin/oc-mirror --config ocpbugs-8216.yaml  docker://localhost:5000  --use-oci-feature  --dest-use-http  --dest-skip-tls```
``` kind: ImageSetConfiguration
storageConfig:
local:
path: /home/aguidi/go/src/github.com/aguidirh/oc-mirror/ocpbugs-8216
mirror:
operators:
- catalog: oci:///home/aguidi/dev/catalogs/rhoc4.12
targetCatalog: mno/redhat-operator-index
targetTag: v4.12
packages:
- name: aws-load-balancer-operator 
```
> OCPBUGS-8216: fix: remove an unecessary error message

- pkg/cli/mirror/cincinnati_graph_image.go
we're changing the dir for extracting cincinnati-graph-data as we're mounting an empty volume to /var/lib/cincinnati/graph-data on the operator. this results in the dir getting overrided with an empty dir.
Solution:
Extract cincinnati-graph-data to a different directory and copy the contents to the required directory after the container is mounted by introducing an init command for the container.
Fixes [OCPBUGS-7888](https://issues.redhat.com/browse/OCPBUGS-7888)
use the graph-data created by this PR with OSUS operator v5.0.1
> OCPBUGS-7888: fix extract dir for cincinnati-graph-data container

- pkg/cli/mirror/mirror.go
- pkg/cli/mirror/mirror_test.go
- pkg/cli/mirror/options.go
This bug fix addresses the issue of nested path length in some registries that limit this.
A flag `--max-nested-paths` can be used to set the value (default is 2) 
As an example 
docker://registry.gitlab.com/xxx/yyy would be allowed
docker://registry.gitlab.com/xxx/yyy/zzz would not be allowed
However if the flag --max-nested-paths is used (default is set to 2) with the second example 
docker://registry.gitlab.com/xxx/yyy/zzz 
An error message would be shown before the main execution of oc-mirror (preventing time waste) in the form :
`the max-nested-paths value (2) for registry.gitlab.com/xxx/yyy/zzz exceeds the registry mirror paths setting (some registries limit the nested paths)`
Fixes # (OCPBUGS-8111)
- [x ] Bug fix (non-breaking change which fixes an issue)
Added unit test to verify …
> OCPBUGS-8111: Bugfix for destination registry nested paths length

- pkg/cli/mirror/mirror.go
ImageContentSourcePolicy.yaml should not include catalog reference since the CatalogSource.yaml already contains this information. 
Fixes #OCPBUGS-10051:
Using the following ImageSetConfig:
```
storageConfig:
local:
path: /home/aguidi/go/src/github.com/aguidirh/oc-mirror/ocpbugs-8216
mirror:
operators:
- catalog: oci:///home/aguidi/dev/catalogs/rhoc4.12
targetCatalog: mno/redhat-operator-index
targetTag: v4.12
packages:
```
And the following command:
```
./bin/oc-mirror --config …
```
> OCPBUGS-10051: fix: remove catalog from ImageContentSourcePolicy.yaml

- pkg/cli/mirror/manifests_test.go
- pkg/cli/mirror/mirror.go
- pkg/cli/mirror/options.go
- pkg/cli/mirror/prune.go
Add skip pruning flag that will globally skip all pruning functionality in oc-mirror
Fixes # (ocpbugs-863)
[x] Bug fix (non-breaking change which fixes an issue)
Locally on docker server registry
Mirrored an additional image registry.redhat.io/ubi8/ubi:latest (with so flag set i.e --skip-pruning)
Update image set config with a registry.redhat.io/ubi9/ubi:latest and removed previous image
Verified that the logs for both oc-mirror and registry showed that the ubi8 image was pruned/deleted
Clean the registry and started the same process as aboved but with --skip-pruning flag set
Verified message displayed that this feature is not supported
Verified that no images were pruned or deleted
* Hardware:
* Toolchain:
* SDK:
> [release-4.12] OCPBUGS-863: Add skip pruning flag and logic 

- pkg/cli/mirror/publish.go
- pkg/cli/mirror/publish_test.go
The previous error message was not telling the customer what was the real error so it was changed to be clear why the error happened.
The real error was that when the flag --continue-on-error is used, a tar file can be generated with missing layers. The mirroring of a tar file with missing layers will fail.
It is recommended to avoid using the --continue-on-error flag on production environments. 
A container image was pulled and then a layer was manually removed from the archive (.tar file). After that a new mirror process was triggered and it failed with the following message:
```
error: error occurred during image processing: error finding remote layer "sha256:c3036aa2b3e5e076041b8c1d2a239dd04d408306db78491177541c843bf538f4": …
```
> OCPBUGS-1060 fix: changes confusing error message

- pkg/image/resolve.go
Some related images does not include the registry path (as the example below). 
```
"relatedImages": [
    {
      "name": "",
      "image": "devopstales/trivy-operator:2.4.1"
    }
]
``` 
For scenarios like that docker.io should be the default registry. The code was changed to make sure this default is applied.
Fixes OCPBUGS-10348
ImageSetConfig
```
mirror:
operators:
- catalog: registry.redhat.io/redhat/community-operator-index:v4.11
packages:
- name: community-trivy-operator
channels:
- name: stable
``` …
> OCPBUGS-10348 fix: changes to include the registry path

- Makefile
- pkg/cli/mirror/version/version.go
This issue fix OCPBUGS-7845 by changing the way version is shown in oc-mirror. 
A new flag --info was added to keep the old mechanism responsible to show the entire version schema.
Fixes OCPBUGS-7845
To show the long version:
```
./bin/oc-mirror version
Client Version: v0.2.0-alpha.1-103-g6943ced
```
To show the short version:
```
./bin/oc-mirror version --short
Client Version: v0.2.0
```
To show the entire version schema:
```
./bin/oc-mirror version --info
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.2.0-alpha.1-103-g6943ced", GitCommit:"6943ced8", GitTreeState:"dirty", BuildDate:"2023-04-04T11:52:15Z", GoVersion:"go1.20.2", Compiler:"gc", Platform:"linux/amd64"}
```
* Hardware:
* …
> OCPBUGS-7845 fix: changes the way the version is shown

- pkg/cli/mirror/catalog_images.go
This temporary workaround will be required for versions of OPM, and catalogs based on them, until that longer term fix is cherry-picked and catalogs with the update are published.
Applied the relevant workaround from OCPBUGS-6741 to catalog images generated by oc-mirror
Fixes # OCPBUGS-11552
* Hardware:
* Toolchain:
* SDK:
> OCPBUGS-11552: work around OCPBUGS-6741 by explicitly setting --cache-dir on opm in catalog images

- pkg/cli/mirror/catalog_images.go
This PR reverts the change introduced in #604 . 
Since merge of https://github.com/openshift/operator-framework-olm/pull/435, public catalogs have --cache-dir and precomputed caches. Therefore adding --cache-dir to the cmd of operators later mirrored by oc-mirror causes a CrashLoopBackOff in clusters.
This was due to cache digest not matching the contents of the catalog.
Without the flag, oc-mirror writes catalog without --cache-dir in CMD
oc-mirror catalogs recompute cache, presumably in some other directory than the precomputed (you can tell this because the time to get to serving registry is much longer)
oc-mirror catalogs work .
> OCPBUGS-12236: Revert adding '--cache-dir /tmp/cache' to catalog images

- pkg/cli/mirror/mirror.go
- pkg/cli/mirror/mirror_test.go
- pkg/cli/mirror/options.go
- test/e2e/testcases.sh
Based on the decision with the PM on April 24, `--use-oci-feature` flag is replaced by `--include-local-oci-catalogs` 
The previous flag is marked deprecated in 4.13, and is to be removed completely in the 4.14 version.
Fixes # OCPBUGS-12458
* Unit tests pass
* E2E tests pass
* manual tests with both flags give expected results.
*
> OCPBUGS-12458: Deprecate --use-oci-feature in favor of --include-local-oci-catalogs

- pkg/cli/mirror/mirror.go
- pkg/cli/mirror/sequence.go
This bug fix addresses the issue for automation (i.e when running oc-mirror in a ci/cd pipeline or cronjob etc).
If the  mirror sequence has not changed from a previous run end gracefully with no error i.e exit 0 and print a releavnt message 
Fixes # OCPBUGS-4959
- [x ] Bug fix (non-breaking change which fixes an issue)
Ensures that the process ends without an error and print an appropriate message e.g _"No diff from previous run (seqeunce is the same), nothing to do"_ 
* Hardware:
* Toolchain:
* SDK:
> OCPBUGS-4959: oc-mirror error on second synchronisation with no change

- pkg/cli/mirror/manifests.go
This is a follow up of #623 
Handing the maxNestedPaths as argument all the way to GenerateICSP is not needed anymore. 
This is rather handled by passing the scope to the function, when maxNestedPaths is set, as done in https://github.com/openshift/oc-mirror/blob/5ae42b8e206e972d74b4fc2232bc0b82552915cc/pkg/cli/mirror/mirror.go#L552
Fixes # OCPBUGS-11922
> OCPBUGS-11922: paths not needed in ICSPBuilder interface

- pkg/cli/mirror/manifests.go
- pkg/cli/mirror/manifests_test.go
- pkg/cli/mirror/mirror.go
- pkg/cli/mirror/mirror_test.go
- pkg/cli/mirror/operator.go
- pkg/cli/mirror/options.go
- pkg/image/mapping.go
- pkg/image/mapping_test.go
This is a manual cherry-pick of #623 and #634 
It replaces #632 
/assign sherine-k
> [release-4.13] OCPBUGS-13591,OCPBUGS-13592: Limit the nested repository path while mirroring the images

- go.mod
- pkg/cli/mirror/fbc_operators.go
- pkg/cli/mirror/fbc_operators_test.go
- pkg/cli/mirror/operator.go
Currently execution of addRelatedImageToMapping when using `--oci-registries-config` flag explicitly or getting registries.conf from the environment is terribly slow and gets worse as the number of related images expands. This change makes this code multi threaded to improve performance. In my testing approximately 470 images took approximately 13 minutes. After the change it takes approximately 14 seconds.
- make execution of addRelatedImageToMapping multi threaded
- make addRelatedImageToMapping take a sync.Map to support concurrency
- convert sync.Map back to image.TypedImageMapping after processing
- fix bug so that we actually use the mirror value if we found one
Fixes # OCPBUGS-13762
Please describe the tests that you ran to verify your …
> OCPBUGS-13762: make addRelatedImageToMapping multithreaded

- pkg/cli/mirror/mirror.go
- pkg/cli/mirror/mirror_test.go
- pkg/cli/mirror/options.go
- pkg/image/mapping.go
- pkg/image/mapping_test.go
This fix is based on the fix created for 4.13 but only with essentials changes needed for 4.12
Based on #623 and #634 
Fixes # ([OCPBUGS-14065](https://issues.redhat.com/browse/OCPBUGS-14065))
> [release-4.12] OCPBUGS-14065: fix: Limit the nested repository path while mirroring the images

- pkg/cli/mirror/mirror.go
- pkg/cli/mirror/mirror_test.go
- pkg/cli/mirror/options.go
- pkg/image/mapping.go
- pkg/image/mapping_test.go
This is a fix for the change to --max-nested-paths implementation. The image reference was incorrect. This addresses the fix.
Fixes # OCPBUGS-14065
- [x ] Bug fix (non-breaking change which fixes an issue)
Tested locally
ImageSetConfig 
```
storageConfig:
local:
path: ./oc-mirror-metadata
mirror:
operators:
- catalog: registry.redhat.io/redhat/redhat-operator-index:v4.12
packages:
- name: local-storage-operator
channels:
- name: stable
```
Cli
```
oc-mirror --config isc-ocpbugs-14065.yaml docker://localhost:5000/lmz-test --max-nested-paths=2 --dest-use-http
```
Results 
- mapping.txt
```
registry.redhat.io/openshift4/ose-kube-rbac-proxy@sha256:116dbeb371324607d361d4f1a9daeb5890e44d29b96c9800b2b1d93d21635dec=localhost:5000 …
```
> [release-4.12] OCPBUGS-14065: Fix destination image reference

- pkg/cli/mirror/manifests.go
- pkg/cli/mirror/manifests_test.go
Create catalog source metadata.name values that are compliant with RFC 1035. The generated name is also suitable for naming the catalog source file as well.
Fixes # OCPBUGS-13332
1. Copy single architecture catalog in OCI format
```
skopeo --override-os linux copy --format v2s2 docker://icr.io/cpopen/ibm-zcon-zosconnect-catalog@sha256:6f02ecef46020bcd21bdd24a01f435023d5fc3943972ef0d9769d5276e178e76 oci:///tmp/611/oci-index
```
1. Create ISC in /tmp/611/oci-index/isc.yaml
```yaml
storageConfig:
local:
path: …
```
> OCPBUGS-13332: Create rfc 1035 compliant catalog source name

- pkg/cli/mirror/fbc_operators.go
- pkg/cli/mirror/mirror.go
When calling oc to mirror the contents of mappings.txt, ImageMirrorOptions is constructed: SecurityOptions rely now both on --source-skip-tls || --source-use-http || --dest-skip-tls || --dest-use-http
Fixes # OCPBUGS-14402
E2E tests and unit tests pass
> OCPBUGS-14402: fix

- pkg/cli/mirror/mirror.go
* Hardware:
* Toolchain:
* SDK:
> OCPBUGS-14194: fix oc-mirror should check metadata sequence when --include-local-oci-catalogs is used

- pkg/operator/diff/internal/diff_include.go
This PR addresses the problem with minVersion being ignored in the ImageSetConfiguration (for catalogs)
Fixes # OCPBUGS-588
ImageSetConfig used to verify
```
storageConfig:
local:
path: /tmp/lmz-images
mirror:
operators:
- catalog: registry.redhat.io/redhat/redhat-operator-index:v4.11
packages:
- name: servicemeshoperator
channels:
- name: stable
minVersion: '2.3.1'
- name: rhsso-operator
channels:
- name: stable
minVersion: '7.6.1-opr-005'
```
Before the fix an error message would be displayed 
```
error: error generating diff: error including items:
[package="servicemeshoperator" channel="stable"] bundles do not exist in channel: versions=["2.3.1"]
```
After this fix (using debug output we get this) - output is …
> OCPBUGS-588: minVersion in ImageSetConfiguration seems to be ignored

- pkg/cli/mirror/options.go
--help info was saying to use --oci-registries-config flag only with --use-oci-feature flag. As --use-oci-feature is deprecated this help info was wrong and it was changed with a correct message.
```oc-mirror --help```
* Hardware:
* Toolchain:
* SDK:
> OCPBUGS-13871: fix: changes on help info content

- .goreleaser.yaml
- Dockerfile
- Makefile
- test/e2e/e2e-simple.sh
- test/e2e/lib/util.sh
This PR enables multiarch support in the build and tests in this case ppc64le.
- Update the .goreleaser.yaml to include ppc64le
- Update the Dockerfile to include wget and pigz dependency
- Update the Dockerfile to consider arch it's built on
- Update the util.sh to be arch agnostic
- Update the cross build for ppc64le
Note, the [PR #1680](https://github.com/google/go-containerregistry/pull/1680#event-9120119057) builds go-containerregistry for ppc64le.  When a new release is cut for the go-containerregistry, this build will not be necessary.
opm requires a Power9 machine to run.
Fixes # [MULTIARCH-3440](https://issues.redhat.com//browse/MULTIARCH-3440)
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant …
> MULTIARCH-3440: refine multiarch support for test-unit and test-e2e using dockerfile and add ppc64le build to Makefile

- pkg/cli/mirror/cincinnati_graph_image.go
Adding graphDataMountPath varibale for "/var/lib/cincinnati/graph-data"
* Hardware:
* Toolchain:
* SDK:
> Replacing the hard coded path with graphDataMountPath

- docs/design/imageset-configuration.md
- docs/examples/imageset-config-release-alt-arch.yaml
- docs/imageset-config-ref.yaml
- pkg/cli/mirror/list/releases.go
- pkg/cli/mirror/release.go
Enable mirroring the 'multi' release payload.
Verified that I could mirror multi and single arch payloads to quay.io:
`./bin/oc-mirror --config mirror.yaml docker://quay.io/jeffdyoung`
mirror.yaml:
```
storageConfig: 
registry:
imageURL: quay.io/jeffdyoung/oc-mirror
mirror:
platform:
architectures:
- "multi"
- "arm64"
- "amd64"
channels:
- name: stable-4.13
type: ocp
- name: fast-4.13
type: ocp
```
> MIXEDARCH-265: Enable mirroring of the multi release image

- pkg/image/association_builder.go
…rt OCI indexes
Mirroring using the following imageSetConfig results in an error:
```bash
oc-mirror --config certified-operator-index-imageset-conf-v4.12.yaml file://tmp/operator/
```
```yaml
storageConfig:
local:
path: /tmp/mirror
mirror:
operators:
- catalog: registry.redhat.io/redhat/certified-operator-index:v4.12
targetName: certified-operator-index-06-20-2023-00-00-00
packages:
- name: kubeturbo-certified
channels:
- name: 'stable'
maxVersion: '8.9.2'
minVersion: '8.9.2'
```
Error message:
```
error: unable to retrieve source image icr.io/cpopen/kubeturbo-operator manifest sha256:cc6499b8c5c7a3dfd829d75d7bc73fca6c467bfb5e3235e62018e7ef18220a21: unknown: OCI index found, but accept header does not support OCI indexes …
```
> OCPBUGS-15329: Fix " OCI index found, but accept header does not suppo…"

- pkg/cli/mirror/options.go
It changes the help message since --include-local-oci-catalog is being removed on 4.14
```oc-mirror --help```
```--oci-registries-config string    Registries config file location (it works only with local oci catalogs)```
> OCPBUGS-13871 docs: changes the help message for oci-registries-config flag

- v2/pkg/cli/executor.go
- v2/pkg/mirror/options.go
Introducing the `-p` flag for the v2 mirroring command. 
`-p` or `--port` enables a user to specify the port that could be used by v2/oc-mirror for the local storage registry instance. 
Fixes # [CFE-905](https://issues.redhat.com/browse/CFE-905)
```bash
build/mirror --config isc.yaml file:///tmp/storage
```
```bash
build/mirror --config isc.yaml -p 22 file:///tmp/storage
```
* ImageSetConfig
```yaml
mirror:
- name: registry.redhat.io/ubi8/ubi:latest  
```
> CFE-905: Make local storage port configurable via command line

- pkg/cli/mirror/testdata/README.md
- pkg/image/testdata/README.md
- pkg/metadata/testdata/README.md
add go.mod files as workaround for "go get" failures on directories that contain colon characters. See example in issue for error that is generated. This is based on the workaround discussed in https://github.com/golang/go/issues/41402#issuecomment-832735435
Fixes # [344](https://github.com/openshift/oc-mirror/issues/344)
1. Create a go project
2. execute a go get command (e.g. `go get github.com/openshift/oc-mirror@97db160a1ac084c03c8266649c9e2fe140b631b8)
3. With the workaround in place you won't get `invalid char ':'` errors
* Hardware:
* Toolchain:
* SDK:
> add go.mod files to testdata directories

- pkg/cli/mirror/catalog_images.go
- pkg/cli/mirror/util.go
- pkg/config/metadata.go
This PR improves the way the opm binary is extracted from catalogs by leveraging the ENTRYPOINT from the container image config.
It also forces pulling the container image that matches the runtime architecture and OS.
Fixes # OCPBUGS-17545
This was tested both on amd64 and arm64 OSs with:
```bash
./bin/oc-mirror -c iscv2.yaml docker://localhost:5000/aws --dest-use-http --dest-skip-tls
```
and the following config:
```yaml
mirror:
operators:
- catalog: registry.redhat.io/redhat/redhat-operator-index:v4.13
packages:
```
> OCPBUGS-17545: Improve extracting opm binary from catalogs

- v2/pkg/cli/executor.go
- v2/pkg/mirror/unshare.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/cli/executor.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/mirror/unshare.go
This issue fixes subtask [CFE-906](https://issues.redhat.com/browse/CFE-906) as part of epic [CFE-896](https://issues.redhat.com/browse/CFE-896).
It configures the local storage registry to use `registries.log` file under the `logs` folder instead of stderr.
Unless logLevel is set to debug in the command arguments, the access logs will be disabled.
Manual test
> CFE-906: [V2]Enclave support - Separate log file for local storage

- README.md
As of now, the CLI command `list updates` doesn't take a `--config` argument, but rather use the mirror-config file as a positional argument.
> Update list updates CLI documentation

- pkg/cli/mirror/catalog_images.go
- pkg/image/builder/image_builder.go
- test/e2e/lib/check.sh
This PR fixes [OCPBUGS-17546](https://issues.redhat.com/browse/OCPBUGS-17546) by:
* Avoiding the whiteout of /tmp
* Replacing it by .wh.tmp/cache still failed on the cluster
* Creating a new layer with /cache folder, containing the cache
* Building layer for /configs based on the folder containing the fbc json instead of the fbc json file only
* E2E tests pass
* Run oc-mirror with the following command
```
$ ./bin/oc-mirror -c ~/oc-mirror-tests11/isc.yaml docker://localhost:5000/tests13 --dest-skip-tls --dest-use-http
```
* where isc.yaml is:
```
storageConfig:
local:
path: /home/skhoury/oc-mirror-tests13/oc-mirror-metadata
mirror:
operators:
- catalog: …
```
> OCPBUGS-17546: pod catalogsource generated by oc-mirror will crashloopBackOff randomly

- v2/pkg/additional/local_stored_collector.go
- v2/pkg/operator/local_stored_collector.go
- v2/pkg/release/local_stored_collector.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/additional/local_stored_collector.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/operator/local_stored_collector.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/release/local_stored_collector.go
It removes the registry DNS when storing the image on disk or mirroring to the destination.
[CFE-958](https://issues.redhat.com/browse/CFE-958)
ImageSetConfig:
```
mirror:
platform:
channels:
- name: stable-4.13
minVersion: 4.13.14
maxVersion: 4.13.14
operators:
- catalog: registry.redhat.io/redhat/redhat-operator-index:v4.13
packages:
- name: registry.redhat.io/ubi9/ubi@sha256:20f695d2a91352d4eaa25107535126727b5945bff38ed36a3e59590f495046f0
```
mirrorToDisk command:
```
oc-mirror -c /home/aguidi/go/src/github.com/aguidirh/oc-mirror/alex-isc/isc.yaml …
```
> CFE-899,CFE-958: feat: removes the registry dns

- v2/pkg/cli/executor.go
- v2/pkg/release/local_stored_collector.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/cli/executor.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/release/local_stored_collector.go
This issue fixes the panic that was happening during the use of prepare subcommand, because the graph image was getting generated, at a time where the subcommand does not create an `ImageBuilder` for the `CreateGraphImage` to use.
Fixes # OCPBUGS-22947
* Prepare subcommand
```
./bin/oc-mirror --v2 prepare -c cfe-969.yml --from file:///home/skhoury/release 
```
* Disk to mirror workflow
```
./bin/oc-mirror --v2 -c cfe-969.yml --from file:///home/skhoury/release docker://localhost:5000/cfe969
```
Both commands should succeed and not panic
> OCPBUGS-22947: Should not generate graph with prepare subcommand

- pkg/cli/mirror/prune.go
- pkg/cli/mirror/prune_test.go
The pruning image process during the mirror operation has the possibility of failing when using RedHat Quay. In Quay, when tags are deleted the manifests are automatically eligible for garbage collection. When pruning manifest lists `oc mirror` will attempt to delete the child manifests by digest as well as the parent manifest. Since the child manifests are automatically eligible for garbage collection, they return 404 when `oc mirror` attempts to delete them directly. Since the garbage collection process is already handled within Quay, this change prevents a failure if the manifest returns a 404 during the image prune.
Fixes # [(issue)](https://issues.redhat.com/browse/PROJQUAY-6345)
Reproduced through steps provided in the mentioned issue.
When `--skip-pruning-missing-manifests` is set …
> PROJQUAY-6345: Skipping mirror failure if manifest not found during prune

- v2/pkg/additional/local_stored_collector.go
- v2/pkg/archive/archive_test.go
- v2/pkg/archive/unarchive.go
- v2/pkg/cli/executor.go
- v2/pkg/cli/executor_test.go
- v2/pkg/operator/local_stored_collector.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/additional/local_stored_collector.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/archive/unarchive.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/cli/executor.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/operator/local_stored_collector.go
Integrates previous PRs #738  into the DiskToMirror workflow by
* calling unarchiver to extract the archive
* starting up the local storage based on the extracted content
Fixes # [CFE-992](https://issues.redhat.com/browse/CFE-992)
With the 3 imageSetConfigs below, several tests were done:
|Test #| Command   | Expected outcome | Pass/Fail |
|--------| -------- | ----------- |----------- |
| 1| `./bin/oc-mirror --v2 --config isc1.yml file:///home/skhoury/cfe992main` | `/home/skhoury/cfe992main/mirror_000001.tar` is created | :white_check_mark:Pass |
| 2|`mkdir ~/cfe922enc`<br>`mv ~/cfe992main/mirror_000001.tar ~/cfe922enc/`<br>`./bin/oc-mirror --v2 --config isc1.yml --from file:///home/skhoury/cfe992enc -p 6000 docker://localhost:5000` |`curl -v …
> CFE-977,CFE-992: Integrate all the building blocks together - Disk to Mirror

- pkg/cli/options.go
Hi all! [As part of a fix for running `oc-mirror` on a RO filesystem](https://github.com/openshift/oc-mirror/commit/97db160a1ac084c03c8266649c9e2fe140b631b8), a print statement was added to the codebase that runs on every invocation of `oc-mirror` as noted in https://github.com/openshift/oc-mirror/issues/710 
Looking throughout the rest of the codebase, I don't see any other `fmt.Println` statements, so I'm thinking this could be a development debugging line that inadvertently got left in.
This PR removes the "Logging to .oc-mirror" log line, but leaves the failure print statement, as that is probably a good one to have. I'm happy to update this PR to remove that print statement as well if desired.
This print statement interferes with some automation tasks, such as the (Open Shift …
> OCPBUGS-24243: remove unnecessary print statement from pkg/cli/options.go

- v2/pkg/clusterresources/clusterresources.go
- v2/pkg/clusterresources/clusterresources_test.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/clusterresources/clusterresources.go
This fixes the issue encountered when deploying the IDMS resource generated by oc-mirror v2 to a cluster by:
* replacing `:` and `_` in the name by `-`
Fixes # [OCPBUGS-23339](https://issues.redhat.com/browse/OCPBUGS-23339)
* Added a unit test to check for compliance with RFC1123
* Deployed the  IDMS generated from the below imagesetconfig (after mirrorToDisk + diskToMirror) to a 4.14.3 ROSA cluster successfully.
```yaml
mirror:
```
The IDMS generated from the command above deploys correctly on a cluster
```yaml
apiVersion: config.openshift.io/v1
kind: ImageDigestMirrorSet
metadata:
creationTimestamp: null
name: …
```
> OCPBUGS-23339: fix IDMS custom resource name

- OWNERS
This PR simply instates Alex as approver of the repository
Kudos to @aguidirh ! :+1:
> NO-ISSUE: Make A.Guidi approver on oc-mirror

- v2/pkg/archive/archive.go
- v2/pkg/archive/archive_test.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/archive/archive.go
When constructing the archive at the end of the MirrorToDisk workflow, oc-mirror v2 was only checking if the blob was already included in previous archives by comparing its digest to the history map.
This is not sufficient, as the blob might already be included in the current tar, as several images may include the same blob.
This change compares the blob's digest to both the map of digests from history AND the map of digests included so far in archive, before taking the decision to include it in the archive.
Fixes # [OCPBUGS-24359](https://issues.redhat.com/browse/OCPBUGS-24359)
Perform a MirrorToDisk with `./bin/oc-mirror --v2 -c isc_23236.yaml file:///home/skhoury/23236` and this imageSetConfig:
```yaml
apiVersion: …
```
> OCPBUGS-24359: Fix including duplicate blobs in archive

- .gitignore
- v2/pkg/batch/worker.go
- v2/pkg/batch/worker_test.go
- v2/pkg/cli/executor.go
- v2/pkg/operator/collector.go
- v2/pkg/operator/local_stored_collector.go
- v2/pkg/operator/new.go
- v2/pkg/release/collector.go
- v2/pkg/release/const.go
- v2/pkg/release/local_stored_collector.go
- v2/pkg/release/new.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/batch/worker.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/cli/executor.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/operator/collector.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/operator/local_stored_collector.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/operator/new.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/release/collector.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/release/const.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/release/local_stored_collector.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/release/new.go
This PR modifies the location of the logs folder used by V2: instead of it being created under the current directory, it will be created under the working directory. 
* Logs folder creation is centralized in `setupLogsLevelAndDir` method, instead of doing some in & `PrepareStorageAndLogs`.
* `PrepareStorageAndLogs` is now renamed `setupLocalStorage` 
* `cleanUp` is now renamed `closeAll` : if we remove the log folder at the end of the execution, the user will no longer have access to logs
* Modifications to collectors and batch workers, in order to copy the log lines in the right files.
Discussion needed around the logger: Do we want to keep this mechanism for logging to files? Is there a better way?
```yaml …
```
> OCPBUGS-24357: Move logs folder under workingDir

- pkg/cli/mirror/operator.go
- pkg/cli/mirror/operator_test.go
This fix ensures that the operator not found error exits with the correct error code and does not continue processing.
Fixes # OCPBUGS-23003
- [ x] Bug fix (non-breaking change which fixes an issue)
Verify as described in the JIRA Issue
Used this ImageSetConfig
```
mirror:
operators:
targetName: redhat-operator-index
targetTag: v4.14-n2-tst1
packages:
- name: cincinnati-operator
channels: 
- name: 'v1'
minVersion: '5.0.2'
maxVersion: '5.0.2'
- name: cluster-logging
channels: 
- name: 'stable'
minVersion: '5.7.7'
maxVersion: '5.7.7'
```
With command line
```
oc-mirror --config ocpbugs-23003.yaml …
```
> OCPBUGS-23003: Fix to ensure operator not found error exits with correct status

- pkg/cli/mirror/publish.go
Currently when the field archiveSize on imageSetConfig is set to 1 the mirroring fails for catalogs. 
It was happening because the code was not looping in all archives generated to extract all the catalog content. Also, the folder structure was being kept only in the first archive generated.
The fix is to loop in all archives and also to get all files related with the catalogs/ folder, even if the archive does not have the catalog folder structure inside.
Fixes # (OCPBUGS-16801)
```
archiveSize: 1
storageConfig:
local:
path: metadata
mirror:
operators:
- catalog: registry.redhat.io/redhat/redhat-operator-index:v4.11
packages:
- name: netobserv-operator
channels:
- name: stable …
```
> OCPBUGS-16801: fix: fixes the bug on catalog when using field archiveSize: 1

- v2/pkg/api/v1alpha3/types.go
- v2/pkg/clusterresources/clusterresources.go
- v2/pkg/clusterresources/const.go
- v2/pkg/manifest/oci-manifest.go
- v2/pkg/operator/const.go
- v2/pkg/release/local_stored_collector.go
- v2/pkg/release/local_stored_collector_test.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/api/v1alpha3/types.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/clusterresources/clusterresources.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/clusterresources/const.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/manifest/oci-manifest.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/operator/const.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/release/local_stored_collector.go
This PR introduces a `Type` for `CopyImageSchema`.
`Type` is following `v1alpha2.ImageType`, with possible values:
* `TypeOCPRelease`
* `TypeOCPReleaseContent`
* `TypeCincinnatiGraph`
* `TypeOperatorCatalog`
* `TypeOperatorBundle`
* `TypeOperatorRelatedImage`
* `TypeGeneric`
This enables us to later distinguish and exclude the graph image from the list of images passed to clusterresource Generator interface (responsible for IDMS/ITMS/UpdateService generation) when generating IDMS.
In this PR, we also switch to using the destination reference of the graph image in the `updateService.yaml` custom resource instead of the source reference (in oc-mirror cache).
Fixes # [OCPBUGS-26513](https://issues.redhat.com/browse/OCPBUGS-26513)
With the …
> OCPBUGS-26513: Add Type for CopyImageSchema; Skip graph for IDMS; Fix UpdateService

- pkg/api/v1alpha2/types_include_config.go
- pkg/cli/mirror/mirror.go
- pkg/cli/mirror/mirror_test.go
- pkg/operator/diff/diff.go
- pkg/operator/diff/internal/diff.go
- pkg/operator/diff/internal/diff_include.go
- pkg/operator/diff/internal/diff_test.go
This fix address the issues found [here](https://issues.redhat.com/browse/OCPBUGS-385) .
The TL;DR is that dev teams can change the default channel from one release to the next, this causes customers who have set CICD pipelines to have to change their ImageSetConfig each time a version changes.
This fix allow the use of a field in the ImageSetConfig to override the default channel and specify any channel and use the HEAD (latest version of that channel).
It means that the customer needs to be aware of the caveats not using the default channel when mirroring. This will mean we need to update our documents accordingly. We will work with the docs team as to find the appropriate wording and track (link) the docs issue to this.
Fixes # …
> [release-4.13] OCPBUGS-28899:  Capability to override default channel

- v2/pkg/archive/archive.go
- v2/pkg/archive/permissive_adder.go
- v2/pkg/cli/executor.go
- v2/pkg/cli/executor_test.go
- v2/pkg/clusterresources/clusterresources.go
- v2/pkg/mirror/options.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/archive/archive.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/archive/permissive_adder.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/cli/executor.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/clusterresources/clusterresources.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/mirror/options.go
This PR adds the --since flag for oc-mirror v2. 
```bash
./bin/oc-mirror --v2 --help
--v2 flag identified, flow redirected to the oc-mirror v2 version. PLEASE DO NOT USE that. V2 is still under development and it is not ready to be used. 
Create and publish user-configured mirrors with a declarative configuration input. used for authenticating to the registries.
--since string                          Include all new content since specified date (format yyyy-MM-dd). When not provided, new content since previous mirroring is mirrored
```
Fixes # [CLID-9](https://issues.redhat.com//browse/CLID-9) and [CLID-24](https://issues.redhat.com//browse/CLID-24)
With the following ImageSetConfig:
```yaml
apiVersion: …
```
> CLID-9,CLID-24: Support incremental mirroring using archives by date

- pkg/api/v1alpha2/types_include_config.go
- pkg/cli/mirror/mirror.go
- pkg/cli/mirror/mirror_test.go
- pkg/operator/diff/diff.go
- pkg/operator/diff/internal/diff.go
- pkg/operator/diff/internal/diff_include.go
- pkg/operator/diff/internal/diff_test.go
This fix address the issues found [here](https://issues.redhat.com/browse/OCPBUGS-385) .
The TL;DR is that dev teams can change the default channel from one release to the next, this causes customers who have set CICD pipelines to have to change their ImageSetConfig each time a version changes.
This fix allow the use of a field in the ImageSetConfig to override the default channel and specify any channel and use the HEAD (latest version of that channel).
It means that the customer needs to be aware of the caveats not using the default channel when mirroring. This will mean we need to update our documents accordingly. We will work with the docs team as to find the appropriate wording and track (link) the docs issue to this.
Fixes # …
> [release-4.12] OCPBUGS-29232: Capability to override default channel

- v2/pkg/cli/executor.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/cli/executor.go
Since v2 is using containers/image as the underlying go mod to mirror images, some of the flags were inherited because of this dependency but they are not necessary needed to be exposed to customers.
This PR hides all the unnecessary flags that are being used currently only internally.
Fixes # [CLID-9](https://issues.redhat.com/browse/CLID-9) and [CLID-23](https://issues.redhat.com/browse/CLID-23)
`./bin/oc-mirror --v2 --help`
```
Flags:
-c, --config string                Path to imageset configuration file
--dest-tls-verify              require HTTPS and verify certificates when talking to the container registry or daemon
--from string                  local storage directory for disk to mirror workflow
-h, --help                         help …
```
> CLID-9,CLID-23: feat: hide unnecessary flags

- v2/pkg/image/image.go
- v2/pkg/operator/local_stored_collector.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/image/image.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/operator/local_stored_collector.go
There was an issue on v2 when trying to mirroring multiple catalogs in the same mirroring flow (2 catalogs in the ImageSetConfiguration)
Fixes # [CLID-70](https://issues.redhat.com//browse/CLID-70)
mirrorToDisk and diskToMirror using the following ImageSetConfiguration:
```
mirror:
operators:
- catalog: registry.redhat.io/redhat/community-operator-index:v4.11
packages:
- name: 3scale-community-operator
packages:
```
Target registry:
```
{
"repositories": [
"3scale/3scale-operator",
"albo/aws-load-balancer-controller-rhel8",
"albo/aws-load-balancer-operator-bundle", …
```
> CLID-70: fix: issue when mirroring multiple catalogs

- .ci-operator.yaml
- images/cli/Dockerfile.ci
This PR cherry-picks the dockerfile changes in order to generate both rhel9 and rhel8 binaries, and adapts them to 4.15 context.
Fixes # OCPBUGS-25346
Through prow build and automated tests.
The docker image generated by the ci should contain 2 binaries: oc-mirror.rhel8 and oc-mirror.rhel9
From the logs of the ci job images, build02 cluster was used.
Login to that cluster ( see [instructions](https://docs.ci.openshift.org/docs/how-tos/use-registries-in-build-farm/)
then
```bash
oc registry login  
skopeo copy docker://registry.build02.ci.openshift.org/ci-op-zcqrt91z/pipeline:oc-mirror oci:///home/skhoury/rel415_mirror
Getting image source signatures
Copying blob 397bffd2f247 done   | 
Copying blob ca1636478fe5 done   | 
Copying blob …
```
> OCPBUGS-25346: Generate both oc-mirror binaries for rhel9 and rhel8

- v2/pkg/additional/const.go
- v2/pkg/additional/local_stored_collector.go
- v2/pkg/additional/local_stored_collector_test.go
- v2/pkg/api/v1alpha3/types.go
- v2/pkg/batch/worker.go
- v2/pkg/batch/worker_test.go
- v2/pkg/cli/executor.go
- v2/pkg/cli/executor_test.go
- v2/pkg/manifest/interface.go
- v2/pkg/manifest/oci-manifest.go
- v2/pkg/operator/local_stored_collector.go
- v2/pkg/operator/local_stored_collector_test.go
- v2/pkg/release/local_stored_collector_test.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/additional/const.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/additional/local_stored_collector.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/api/v1alpha3/types.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/batch/worker.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/cli/executor.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/manifest/interface.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/manifest/oci-manifest.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/operator/local_stored_collector.go
This PR contains changes required to allow the mirroring of multi-arch operator catalogs (manifest list / OCI image index).
The changes presented here take into account the case where the index.json contains a reference to a manifest list inside of blobs/sha256 folder and also when the index.json contains the platform information directly. 
[CLID-17](https://issues.redhat.com/browse/CLID-17)
```
skopeo copy --all docker://registry.redhat.io/redhat/redhat-operator-index:v4.15 oci:///home/aguidi/go/src/github.com/aguidirh/oc-mirror/alex-tests/redhat-operator-index --remove-signatures
```
Use this ImageSetConfiguration
```
mirror:
operators:
- catalog: …
```
> CLID-17: feat: docker v2s2 manifest list / oci image index implementation

- Makefile
- v2/pkg/cli/executor.go
- v2/pkg/version/version.go
- v2/pkg/version/version_test.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/cli/executor.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/version/version.go
- vendor/modules.txt
These are the required changes to have the version command retro compatible with v1
Fixes [OCPBUGS-31084](https://issues.redhat.com/browse/OCPBUGS-31084)
```
./bin/oc-mirror version 
```
```
./bin/oc-mirror version --v2
```
Both commands above should return the same output
> OCPBUGS-31084: feat: retro-compatible version cmd with v1

- v2/pkg/additional/local_stored_collector_test.go
- v2/pkg/batch/worker_test.go
- v2/pkg/manifest/interface.go
- v2/pkg/manifest/oci-manifest.go
- v2/pkg/operator/local_stored_collector.go
- v2/pkg/operator/local_stored_collector_test.go
- v2/pkg/release/local_stored_collector_test.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/manifest/interface.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/manifest/oci-manifest.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/operator/local_stored_collector.go
There was an issue when there were different versions of the same catalog present in the ImageSetConfiguration. In order to guarantee that each catalog is unique (even if it is a patch version or oci on disk), folders based on the digest are going to be created.
Fixes [OCPBUGS-31344](https://issues.redhat.com/browse/OCPBUGS-31344) 
1. First copy the oci operator index to disk:
```
skopeo copy docker://registry.redhat.io/redhat/redhat-operator-index:v4.12 oci:///home/aguidi/go/src/github.com/aguidirh/oc-mirror/alex-tests/app1/noo/redhat-operator-index  --remove-signatures
```
2. Create the following ImageSetConfiguration:
```
mirror:
operators:
- catalog: …
```
> OCPBUGS-31344: fix: issue when different versions of the same catalog

- v2/pkg/api/operator-framework/v1alpha1/catalogsource_types.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/api/operator-framework/v1alpha1/catalogsource_types.go
Fixes # OCPBUGS-31024
Unit tests pass. 
CatalogSource file generated doesn't contain `icon: {}`
> OCPBUGS-31024: Ommit icon from catalogSource if empty

- Makefile
- docs/enclave_support.md
- v2/Makefile
- v2/pkg/additional/local_stored_collector.go
- v2/pkg/cli/additional_integration_test.go
- v2/pkg/cli/executor.go
- v2/pkg/cli/executor_test.go
- v2/pkg/cli/release_integration_test.go
- v2/pkg/mirror/const.go
- v2/pkg/mirror/options.go
- v2/pkg/operator/local_stored_collector.go
- v2/pkg/release/graph.go
- v2/pkg/release/local_stored_collector.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/additional/local_stored_collector.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/cli/executor.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/mirror/const.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/mirror/options.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/operator/local_stored_collector.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/release/graph.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/release/local_stored_collector.go
This PR introduces support for MirrorToMirror workflow in the v2 of oc-mirror.
It also introduces the command argument `--workspace` that can be used with this workflow to point to the parent directory of the working-dir (if existing). 
Fixes # [CLID-54](https://issues.redhat.com//browse/CLID-54)
Perform a direct mirror to mirror workflow with:
```bash
cat isc.yaml
mirror:
platform:
channels:
- name: stable-4.13
operators:
packages:
- name: external-dns-operator
./bin/oc-mirror --v2 -c isc.yaml --workspace …
```
> CLID-54: Mirror to mirror workflow

- pkg/operator/diff/internal/diff.go
This fixes the problem on the new "defaultChannel" field. The problem arises when re-executing oc-mirror with packages that have this field set
Fixes # OCPBUGS-31466
Tested with this imagesetconfig.yaml
```
storageConfig:
local:
path: ./operator-images
mirror:
operators:
packages:
defaultChannel: stable-v0.2
channels:
- name: stable-v0.2
minVersion: 0.2.0
maxVersion: 0.2.0
- name: cluster-kube-descheduler-operator
defaultChannel: "4.13"
channels:
- name: "4.13"
```
First pass works perfectly, second pass failed with error about invalid package and default channel
Re-execute oc-mirror with the exact same imagesetconfig
It …
> OCPBUGS-31466: Fix for oc-mirror new defaultChannel override

- v2/pkg/additional/local_stored_collector.go
- v2/pkg/api/v1alpha2/types_config.go
- v2/pkg/api/v1alpha2/types_config_test.go
- v2/pkg/api/v1alpha3/types.go
- v2/pkg/clusterresources/clusterresources.go
- v2/pkg/config/validate_test.go
- v2/pkg/image/image.go
- v2/pkg/operator/local_stored_collector.go
- v2/pkg/operator/local_stored_collector_test.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/additional/local_stored_collector.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/api/v1alpha2/types_config.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/api/v1alpha3/types.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/clusterresources/clusterresources.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/image/image.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/operator/local_stored_collector.go
Ensure that the current v2 respects the v1 TargetCatalog and TargetTag fields (if set) for oci catalog and registry catalogs.
Also TargetCatalog and TargetTag should not be mutually exclusive.
Invalid example:
```
mirror:
operators:
targetCatalog: abc/def:v5.5
packages:
```
Valid example:
```
mirror:
operators:
targetCatalog: abc/def
targetTag: v4.4
packages:
```
Fixes # [CLID-47](https://issues.redhat.com//browse/CLID-47) …
> CLID-47,CLID-46: Use of TargetCatalog and TargetTag on all catalogs

- pkg/cli/mirror/mirror.go
- v2/pkg/cli/executor.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/cli/executor.go
This PR changes the --help for v2 (description, usage and examples).
```
./bin/oc-mirror --help --v2
```
A different --help output from the main branch
> CLID-66,CLID-81: refines v2 --help

- v2/pkg/release/signature.go
- v2/pkg/release/signature_test.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/release/signature.go
This is an addendum to PR #831 and exists execution in error if ocp release image is not signed
> CLID-53: Exit if release is unsigned

- v2/pkg/additional/local_stored_collector_test.go
- v2/pkg/archive/archive_test.go
- v2/pkg/archive/image-blob-gatherer.go
- v2/pkg/archive/image-blob-gatherer_test.go
- v2/pkg/batch/worker_test.go
- v2/pkg/cli/additional_integration_test.go
- v2/pkg/cli/delete.go
- v2/pkg/cli/delete_test.go
- v2/pkg/cli/dryrun_test.go
- v2/pkg/cli/executor.go
- v2/pkg/cli/executor_test.go
- v2/pkg/cli/release_integration_test.go
- v2/pkg/delete/delete_images_test.go
- v2/pkg/imagebuilder/builder.go
- v2/pkg/imagebuilder/builder_test.go
- v2/pkg/mirror/mirror_test.go
- v2/pkg/mirror/options.go
- v2/pkg/mirror/options_test.go
- v2/pkg/operator/local_stored_collector_test.go
- v2/pkg/release/cincinnati_test.go
- v2/pkg/release/graph_test.go
- v2/pkg/release/local_stored_collector_test.go
- v2/pkg/release/signature_test.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/archive/image-blob-gatherer.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/cli/delete.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/cli/executor.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/imagebuilder/builder.go
- vendor/github.com/openshift/oc-mirror/v2/pkg/mirror/options.go
This PR removes the field `TlsVerify` from the `CopyOptions.Global` which was bypassing TLS handshake completely for all registries involved. 
This field was added there when some code was copied from the skopeo code base, where it was already marked deprecated.
Fixes # [CLID-101](https://issues.redhat.com//browse/CLID-101)
Instead of a global `TlsVerify`, one should set tls verification under either `CopyOptions.SrcImage` or `CopyOptions.DestImage`. The exact field can be found under type `dockerImageOptions`, and its type is `commonFlag.OptionalBool`. 
This makes it impossible to set the field directly. Instead, we use the flags associated with the options to set the value. 
Example:
```
srcFlags, srcOpts := mirror.ImageSrcFlags(global, …
```
> CLID-101: Fix TlsVerify always set to false

- v2/internal/pkg/batch/worker.go
- v2/internal/pkg/release/cincinnati.go
- v2/internal/pkg/release/local_stored_collector.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/batch/worker.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/release/cincinnati.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/release/local_stored_collector.go
* Fix graph image mirroring during MirrorToDisk and MirrorToMirror: 
* The error that was encountered was because in the specific case of the graph image, src of the image is localhost:55000/graph:latest. Therefore we were attempting to mirror from the cache registry (tls-verify not forced to false) . 
* The graph image is already built and pushed to the destination registry during the collection phase (graph.go)
* destination registry is the cache for the case of mirrorToDisk
* destination registry is the remote mirror for the case of mirrorToMirror
* The fix is to exclude the graph image from the batch mirroring for the case of MirrorToDisk and MirrorToMirror.
* Fix the generation of UpdateService.yaml file for MirrorToMirror workflow. 
* The root cause was that the imageSetConfig …
> CLID-101: Fix graph image mirroring after TLS verification enabling

- v2/internal/pkg/cli/executor.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/cli/executor.go
Fixes # OCPBUGS-31083
unit tests and E2E tests pass.
```
$ ./bin/oc-mirror --v2 -h  | grep strict
2024/04/26 16:55:37  [WARN]   : ⚠️  --v2 flag identified, flow redirected to the oc-mirror v2 version. This is Tech Preview, it is still under development and it is not production ready.
--strict-archive         If set (default is false), generates archives that are strictly less than archiveSize (set in the imageSetConfig). Mirroring will exit in error if a file being archived exceed archiveSize(GB).
```
> OCPBUGS-31083: Fix help for --strict-archive flag

- pkg/cli/mirror/catalog_images.go
- pkg/cli/mirror/fbc_operators.go
- pkg/cli/mirror/mirror.go
- pkg/cli/mirror/operator.go
- pkg/cli/mirror/options.go
- pkg/cli/mirror/publish.go
- test/e2e/lib/workflow.sh
- test/e2e/testcases.sh
Introduces flag `--rebuild-catalogs` (default false). 
By default, oc-mirror v1 will not rebuild catalogs (nor generate their cache). 
When `--rebuild-catalogs` is explicitly set  in the command line, this rebuilding will be done, without changes to the current implementation. In other words, if the OS on which oc-mirror is running is not a match to the opm binary extracted from the catalog, the cache generation may fail during mirroring, or may fail during deployment of the catalogSource on the cluster. 
The user can also use the environment variable `OPM_BINARY` in order to force oc-mirror to use a custom opm binary for cache generation. See tests section below for samples of use. 
PS: you can download the opm binary from https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/o …
> OCPBUGS-31536: Change default behavior to not rebuild catalogs for V1

- v2/docs/delete-functionality.md
- v2/internal/pkg/batch/worker.go
- v2/internal/pkg/cli/const.go
- v2/internal/pkg/cli/delete.go
- v2/internal/pkg/cli/executor.go
- v2/internal/pkg/delete/delete_images.go
- v2/internal/pkg/log/logger.go
- v2/internal/pkg/mirror/mirror.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/batch/worker.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/cli/const.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/cli/delete.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/cli/executor.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/delete/delete_images.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/log/logger.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/mirror/mirror.go
This a fix addresses the bug raised for delete images generation for the mirror to mirror flow
Fixes # OCPBUGS-32547
Executed the following isc 
```
mirror:
platform:
channels:
- name: stable-4.14
minVersion: 4.14.22
maxVersion: 4.14.22
operators:
packages:
- catalog: oci:///home/lzuccarelli/go/src/github.com/openshift/oc-mirror/rhopi4-14
targetTag: "v14"
targetCatalog: "lmz/catalog"
packages:
- name: windows-machine-config-operator
- catalog: oci:///home/lzuccarelli/go/src/github.com/openshift/oc-mirror/rhopi4-14
packages:
- name: cincinnati-operator
```
Then ensured a mirror to mirror workflow using this command
``` …
```
> OCPBUGS-32547: Fix delete generation for mirror to mirror flow

- pkg/cli/mirror/fbc_operators.go
- pkg/cli/mirror/options.go
2 issues are fixed here:
* catalog images are mirrored as manifest lists
* catalog images are mirrored without signature verification by default
* to enable signature verification, one can use the new flag `--enable-operator-secure-policy`
* existing flag `oci-insecure-signature-policy` marked deprecated
Fixes # OCPBUGS-31536
```
$ ./bin/oc-mirror -c isc_31536.yaml file:///home/skhoury/31536 --enable-operator-secure-policy
```
Above test is no proof of fix: this needs to be tested on a fedora system
* with no /etc/containers/policy.json 
* AND without using the flag
to show that the mirroring is successful on systems that don't have the policy setup for checking image signatures from redhat.
> OCPBUGS-31536:OCPBUGS-33554: Fix mirroring operators on fedora systems - no sig verification

- v2/internal/pkg/operator/local_stored_collector.go
- v2/internal/pkg/operator/local_stored_collector_test.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/operator/local_stored_collector.go
Fixes # OCPBUGS-31622
This was specific to seldon-operator (community catalog)
Additional unit test covering the use case.
Successfully performed M2D + D2M with the following imagesetconfig
```yaml
mirror:
operators:
- catalog: oci:///home/skhoury/redhat-index-all
packages:
- catalog: registry.redhat.io/redhat/redhat-operator-index:v4.15
packages:
- name: elasticsearch-operator
- catalog: registry.redhat.io/redhat/redhat-marketplace-index:v4.15
packages:
- name: datadog-operator-certified-rhmp
- catalog: registry.redhat.io/redhat/certified-operator-index:v4.15
packages:
- name: portworx-certified
- catalog: …
```
> OCPBUGS-31622: Fix operator related image has empty reference

- v2/internal/pkg/additional/local_stored_collector_test.go
- v2/internal/pkg/batch/worker_test.go
- v2/internal/pkg/cli/const.go
- v2/internal/pkg/cli/dryrun.go
- v2/internal/pkg/cli/executor.go
- v2/internal/pkg/cli/executor_test.go
- v2/internal/pkg/clusterresources/clusterresources.go
- v2/internal/pkg/clusterresources/clusterresources_test.go
- v2/internal/pkg/mirror/mirror.go
- v2/internal/pkg/mirror/mirror_test.go
- v2/internal/pkg/operator/local_stored_collector_test.go
- v2/internal/pkg/release/local_stored_collector_test.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/cli/const.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/cli/dryrun.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/cli/executor.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/clusterresources/clusterresources.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/mirror/mirror.go
Fix source repository for IDMS/ITMS in case of empty namespace
This also clears the cluster-resources folder while setting up the working-dir, so that old itms , catalogsrouce files don't stay stale in the folder, and get dragged into the tar file.
It also fixes dry-run for mirror-to-disk mode which was checking and not finding any of the images in the cache due to the fact that it was using a srcImage context (tls enabled) instead of the destImage context (tls disabled for the cache registry)
Fixes # OCPBUGS-31608
Using the following imageSetConfig, perform a mirror to disk followed by disk to mirror as stated in the jira issue: 
```yaml
mirror:
operators:
- catalog: …
```
> OCPBUGS-31608:OCPBUGS-33775: Fix source repository for IDMS/ITMS in case of empty namespace

- v2/internal/pkg/additional/local_stored_collector.go
- v2/internal/pkg/image/image.go
- v2/internal/pkg/mirror/mirror.go
- v2/internal/pkg/operator/local_stored_collector.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/additional/local_stored_collector.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/image/image.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/mirror/mirror.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/operator/local_stored_collector.go
This addresses the issue when images being mirrored, having both tag and digest would cause the mirror execution to fail, the fix ensures these type images will be skipped with an appropriate warning message.
Fixes #  OCPBUGS-33196
I used the following imagesetconfig for testing
```
mirror:
- name: quay.io/cilium/cilium-etcd-operator:v2.0.7@sha256:04b8327f7f992693c2cb483b999041ed8f92efc8e14f2a5f3ab95574a65ea2dc
- name: quay.io/coreos/etcd:v3.5.4@sha256:a67fb152d4c53223e96e818420c37f11d05c2d92cf62c05ca5604066c37295e9
```
Executed the following mirror to disk workflow
```
bin/oc-mirror --config ocpbugs-33196.yaml file://taganddigest --v2
```
```
2024/05/14 14:18:35  [WARN]   : ⚠️  --v2 flag identified, …
```
> OCPBUGS-33196: skip images with both tag and digest

- v2/internal/pkg/release/cincinnati.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/release/cincinnati.go
When selecting the release nodes that correspond to the filtering, we were using a slice. duplicates nodes lead to mirroring the release content more than once. 
The fix consists of using a map in order to reduce the quantity of images.
PS: this is a practice that we should consider more overall for all collectors in the future, as some images (kube-rbac-proxy for one) is used in multiple components and operators. WDYT?
Fixes #OCPBUGS-33580
mirroring the following imagesetconfig with or without shortestPath: true should lead to the same number of mirrored images.
```yaml
archiveSize: 8
mirror:
platform:
channels:
- name: stable-4.15 …
```
> OCPBUGS-33580: Fix shortestPath returning 3 times the same imageSet

- test/e2e/lib/util.sh
- docker.io updated to a  manifest listed image.
- the code accounts for this change.
Fixes # https://issues.redhat.com/browse/OCPBUGS-34211
Bug fix (non-breaking change which fixes an issue)
Run on Z
e2e tests run on z/power
> OCPBUGS-34211: docker.io registry/2 is pulled with a platform argument

- pkg/cli/mirror/mirror.go
- pkg/cli/options.go
This fix addresses the issue faced in using the --v2 (used to invoke v2 of oc mirror) and accidentally using -v2 (used for verbose logging)
This fix will only be for 4.17 onwards until we deprecate v1
Fixes # OCPBUGS-33121
Locally and unit tests
console message should show 
```
error: detected a v2 ImageSetConfiguration, please use --v2 instead of -v2
```
> OCPBUGS-33121: Fix problems with versions and verbose flags

- v2/internal/pkg/clusterresources/clusterresources.go
- v2/internal/pkg/clusterresources/clusterresources_test.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/clusterresources/clusterresources.go
This PR skips the generation of an empty itms/idms/catalogsource when no images corresponding are available.
Fixes #OCPBUGS-33775
Using this imagesetconfiguration, only itms is generated
```yaml
mirror:
```
idms file is not generated
> OCPBUGS-33775: Do not generate idms & itms if nothing has been mirrored

- v2/internal/pkg/cli/delete.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/cli/delete.go
Fix spelling error in console message (delete functionality)
Fixes # OCPBUGS-35279
NA
Console log output for delete should show  the following (Rememeber changed to Remember)
```
2024/06/11 14:18:05  [INFO]   : === Results ===
2024/06/11 14:18:05  [INFO]   : All images deleted successfully 196 / 196 ✅
2024/06/11 14:18:05  [INFO]   : delete time     : 804.724285ms
2024/06/11 14:18:05  [INFO]   : 📝 Remember to execute a garbage collect (or similar) on your remote repository
2024/06/11 14:18:05  [INFO]   : 👋 Goodbye, thank you for using oc-mirror
```
> OCPBUGS-35279: Fix spelling error in delete console message

- v2/go.mod
- v2/internal/pkg/batch/error.go
- v2/internal/pkg/batch/worker.go
- v2/internal/pkg/batch/worker_test.go
- v2/internal/pkg/cli/additional_integration_test.go
- v2/internal/pkg/cli/delete.go
- v2/internal/pkg/cli/executor.go
- v2/internal/pkg/cli/executor_test.go
- v2/internal/pkg/cli/release_integration_test.go
- v2/internal/pkg/clusterresources/clusterresources.go
- v2/internal/pkg/delete/delete_images.go
- v2/internal/pkg/delete/delete_images_test.go
- v2/internal/pkg/mirror/mirror.go
- v2/internal/testutils/testutils.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/batch/error.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/batch/worker.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/cli/delete.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/cli/executor.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/clusterresources/clusterresources.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/delete/delete_images.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/mirror/mirror.go
This PR contains:
* A fix for the integration tests, which were failing to find test data
* Rebased after #864
* Modification of the way we log progress in batch mirroring:
* image reference is shown, 
* progress on release/operator/additional is only shown if there are images of that type in the imageset
* code: handling the counters for progress and logging it is deported to separate function
* Implementation of fail safe vs fail fast for batch workers:
* When calling `o.Mirror.Run`, the batch now evaluates the image type:
* For error on release images, the batch will immediately fail and return to the caller: no IDMS or ITMS or catalogSource are to be generated
* For error on any other type of image, the batch continues, reports a `SafeError` to caller. The executor will carry on …
> OCPBUGS-34020: Implement fail safe / fail fast in workers

- v2/internal/pkg/operator/local_stored_collector.go
- v2/internal/pkg/operator/local_stored_collector_test.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/operator/local_stored_collector.go
This PR fixes the errors encountered while DiskToMirror in a disconnected environment.
The issue arises because
* when in MirrorToDisk, the catalog image(working-dir/operator-images) and contents (working-dir/hold-images) are stored under a subfolder corresponding to the digest of the image. 
* Then, while doing diskToMirror, oc-mirror attempts to call the source registry to resolve the image tag to a digest in order to find the corresponding subfolder on disk.
When diskToMirror is happening on a fully disconnected environment, there is no access to the source registry. This is why the error was happening.
With this fix, oc-mirror interrogates the local cache in order to determine this digest.
Fixes # [OCPBUGS-36214](https://issues.redhat.com/browse/OCPBUGS-36214)
Please delete options …
> OCPBUGS-36214: Fix V2 DiskToMirror should not require internet access

- v2/internal/pkg/cli/executor.go
- v2/internal/pkg/manifest/oci-manifest.go
- v2/internal/pkg/operator/local_stored_collector.go
- v2/sonar-project.properties
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/cli/executor.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/manifest/oci-manifest.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/operator/local_stored_collector.go
This fix addresses the SIGSEGV violation error (casuing oc-mirror to crash). 
The root cause is the handling of invalid catalogs for oc-mirror v2 (only oci file base catalogs are valid and not SQLite (database) type catalogs
Fixes # OCPBUGS-36445
Verified locally using the following imagesetconfig (from case 03862148)
```
mirror:
operators:
- catalog: icr.io/cpopen/noi-operator-catalog@sha256:ae39015ec2161a982c85d66456f23883dc19f85c00d5f3b2058f385fc5eacd50
packages:
- name: noi
- catalog: icr.io/cpopen/ibm-netcool-integrations-operator-catalog@sha256:f913349f3c05f02fb48b2faaa9959927266947b64be5884e49e64f8d1e0788a5
packages:
- name: netcool-integrations-operator
- catalog: …
```
> OCPBUGS-36445: Fix to ensure invalid catalogs are skipped

- v2/internal/pkg/manifest/oci-manifest.go
- v2/internal/pkg/operator/local_stored_collector.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/manifest/oci-manifest.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/operator/local_stored_collector.go
If a catalog is non existing oc-mirror should log a warning to the console  , skip the catalog and continue
Fixes # OCPBUGS-36548
Use the following imagesetconfig
```
mirror:
operators:
- catalog: registry.redhat.io/redhat/redhat-operator-index:v4.17
packages:
- name: windows-machine-config-operator
```
Console output 
```
2024/07/04 12:30:51  [WARN]   : ⚠️  --v2 flag identified, flow redirected to the oc-mirror v2 version. This is Tech Preview, it is still under development and it is not production ready.
2024/07/04 12:30:51  [INFO]   : 👋 Hello, welcome to oc-mirror
2024/07/04 12:30:51  [INFO]   : ⚙️  setting up the environment for you...
2024/07/04 12:30:51  [INFO]   : 🔀 workflow mode: mirrorToDisk 
2024/07/04 12:30:51 …
```
> OCPBUGS-36548: Skip catalogs that are non existing

- v2/internal/pkg/additional/local_stored_collector.go
- v2/internal/pkg/batch/worker.go
- v2/internal/pkg/cli/executor.go
- v2/internal/pkg/manifest/oci-manifest.go
- v2/internal/pkg/operator/local_stored_collector.go
- v2/sonar-project.properties
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/additional/local_stored_collector.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/batch/worker.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/cli/executor.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/manifest/oci-manifest.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/operator/local_stored_collector.go
This fix addresses the SIGSEGV violation error (causing oc-mirror to crash). 
The root cause is the handling of invalid catalogs for oc-mirror v2 (only oci file base catalogs are valid and not SQLite (database) type catalogs
Fixes # reference to OCPBUGS-36445 
Verified locally using the following imagesetconfig (from case 03862148)
```
mirror:
operators:
- catalog: icr.io/cpopen/noi-operator-catalog@sha256:ae39015ec2161a982c85d66456f23883dc19f85c00d5f3b2058f385fc5eacd50
packages:
- name: noi
- catalog: icr.io/cpopen/ibm-netcool-integrations-operator-catalog@sha256:f913349f3c05f02fb48b2faaa9959927266947b64be5884e49e64f8d1e0788a5
packages:
- name: netcool-integrations-operator
- catalog: …
```
> [release-4.16] OCPBUGS-36498:  Fix to ensure invalid catalogs are skipped

- v2/internal/pkg/release/signature.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/release/signature.go
This fixes the error encountered when running oc-mirror behind proxy for mirroring releases: signature API was called without respecting proxy setup
Fixes #OCPBUGS-37055
1. Install tinyproxy (`sudo dnf install tinyproxy -y`)
2. Create tinyproxy.conf
```
Port 8888
Listen 127.0.0.1
Timeout 600
Allow 127.0.0.1
```
3. run tinyproxy (`tinyproxy -d -c tinyproxy.conf`)
4. in separate window, run oc-mirror with proxy env vars set:
```
export http_proxy=localhost:8888
export HTTP_PROXY=localhost:8888
export HTTPS_PROXY=localhost:8888
export https_proxy=localhost:8888
./bin/oc-mirror --v2 -c ec2-demo/isc_resources.yaml file:///home/skhoury/demo1
```
5. look at logs of tinyproxy, call to `mirror.openshift.com` (as well as quay.io for images, and …
> OCPBUGS-37055: Use proxy for HTTP request release signatures

- pkg/cli/mirror/catalog_images.go
- pkg/cli/mirror/mirror.go
- pkg/cli/mirror/operator.go
- pkg/cli/mirror/options.go
- test/e2e/lib/check.sh
- test/e2e/testcases.sh
According to OCPBUGS-35386, when the user mirrors operators and specifies a maxVersion < channel's jead, without catalog rebuild, the full catalog is sent to cluster. On cluster, when installing the operator without specifically selecting maxVersion , the OLM will attempt to install bundle at channel head and fail because that head version was never mirrored.
- `--rebuild-catalogs` is still here for backwards compatibility (so --rebuild-catalogs=false means we don't rebuild and still send the catalog as is, just in case anybody wants this?)
- it is marked deprecated, so that in the next release we can remove the flag if no one is using "full" catalogs
- the default value is true: so if omitted, catalog will be rebuilt, with following behavior
- But we don't regenerate the internal cache
- …
> OCPBUGS-37667: Rebuild catalogs -- without cache generation

- v2/internal/pkg/release/local_stored_collector.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/release/local_stored_collector.go
This fix addresses the issue when a kubeVirtContainer flag is set to true in the imagesetconfig but no image is found in the release metatdata yaml files.
Fixes # OCPBUGS-37950
Tested locally using the following imagesetconfig
```
mirror:
platform:
channels:
- name: stable-4.12
minVersion: 4.12.61
maxVersion: 4.12.61
kubeVirtContainer: true
```
Execute the following command line
```
bin/oc-mirror --config simple.yaml file://ocpbugs-37950 --v2
```
The execution should show a warning in the console log and continue (not stop execution)
```
bin/oc-mirror --config simple.yaml file://ocpbugs-37950 --v2
2024/08/05 11:56:34  [WARN]   : ⚠️  --v2 flag identified, flow redirected to the oc-mirror v2 version. This is Tech Preview, …
```
> OCPBUGS-37950: Bug fix when kubevirt image not found

- v2/internal/pkg/release/cincinnati.go
- v2/internal/pkg/release/cincinnati_test.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/release/cincinnati.go
When using oc-mirror v2 with the kubeVirtContainer field (set to true), it calls the cincinnati api and uses the channels (name) with min/max version to downlaod the correct platform release, however in a CI/CD pipeline (pre prod) e2e testing of oc-mirror with channels, the version under test has not been productized and pushed, meaning it will never be picked up via the cincinnati api.
Fixes # OCPBUGS-38396
Tested locally with the following imagesetconfig
```
mirror:
platform:
graph: true
release: quay.io/openshift-release-dev/ocp-release:4.17.0-ec.3-x86_64 
kubeVirtContainer: true
```
Use the following command line
```
bin/oc-mirror --config kube-virt.yaml file://test-kubevirt  --v2
```
The console (truncated) should …
> [v2] OCPBUGS-38396: use platform.release when set

- v2/internal/pkg/cli/delete.go
- v2/internal/pkg/cli/executor.go
- v2/internal/pkg/release/cincinnati.go
- v2/internal/pkg/release/cincinnati_test.go
- v2/internal/pkg/release/client.go
- v2/internal/pkg/release/client_test.go
- v2/internal/pkg/release/core-cincinnati.go
- v2/internal/pkg/release/core-cincinnati_test.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/cli/delete.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/cli/executor.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/release/cincinnati.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/release/client.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/release/core-cincinnati.go
This uses the v2 logger instead of klog for logging things during cincinnati processing of release collection
Fixes # [OCPBUGS-35824](https://issues.redhat.com/browse/OCPBUGS-35824)
```
export UPDATE_URL_OVERRIDE=https://localhost.localdomain:3443/graph
go run test/e2e/graph/main.go & 
./bin/oc-mirror --v2 -c ec2-demo/isc_resources.yaml file:///home/skhoury/demo
```
with an imagesetconfig requesting  mirroring of 4.15.17 release
Successful mirroring with logs:
```
2024/08/08 11:58:08  [WARN]   : ⚠️  --v2 flag identified, flow redirected to the oc-mirror v2 version. This is Tech Preview, it is still under development and it is not production ready.
2024/08/08 11:58:08  [INFO]   : 👋 Hello, welcome to oc-mirror
2024/08/08 11:58:08  [INFO]   : ⚙️ …
```
> OCPBUGS-35824: Log warning UPDATE_URL_OVERRIDE correctly

- v2/internal/pkg/cli/executor.go
- v2/internal/pkg/cli/executor_test.go
This fix avoid oc-mirror v2 going into panic, when an invalid log-level flag is used.
**NB** The loglevel flag has been changed to log-level to comply with other tools such a Podman etc
Fixes # OCPBUGS-37740
Locally , executing binary
```
bin/oc-mirror --config simple.yaml file://test-lmz --v2 --log-level -v
2024/09/04 12:36:30  [WARN]   : ⚠️  --v2 flag identified, flow redirected to the oc-mirror v2 version. This is Tech Preview, it is still under development and it is not production ready.
2024/09/04 12:36:30  [INFO]   : 👋 Hello, welcome to oc-mirror
2024/09/04 12:36:30  [INFO]   : ⚙️  setting up the environment for you...
2024/09/04 12:36:30  [ERROR]  : log-level has an invalid value -v , it should be one of (info,debug,trace)
```
> OCPBUGS-37740: Should not panic when invalid log-level flag is used

- v2/internal/pkg/cli/executor.go
- v2/internal/pkg/cli/executor_test.go
- v2/internal/pkg/operator/local_stored_collector.go
- v2/internal/pkg/operator/local_stored_collector_test.go
Delete feature simulates a DiskToMirror mode for operator collector.
Since the catalogs are saved in the working-dir under a folder whose name corresponds to the catalog digest, the collector first tries to translate the catalog tag into a digest.
For doing so, it assumes that the catalog is in the local cache. It also assumes the local cache is TLS enabled ([OCPBUGS-37948](https://issues.redhat.com/browse/OCPBUGS-37948)).
For catalogs mirrored in MirrorToMirror, catalog images will not exist in the local cache: Failing to determine the catalog digest from the catalog tag leads to failure in collecting images from catalog. The detele-images.yaml file is therefore empty.
The fix consists in 3 actions:
* Startup the cache registry during mirror to mirror workflow
* During operator …
> OCPBUGS-37948,CLID-196: Fix deletion of operators mirrored in M2M

- v2/internal/pkg/cli/executor.go
- v2/internal/pkg/cli/executor_test.go
- v2/internal/pkg/clusterresources/clusterresources.go
- v2/internal/pkg/clusterresources/clusterresources_test.go
- v2/internal/pkg/operator/local_stored_collector.go
- v2/internal/pkg/operator/local_stored_collector_test.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/cli/executor.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/clusterresources/clusterresources.go
- vendor/github.com/openshift/oc-mirror/v2/internal/pkg/operator/local_stored_collector.go
This is a manual cherry-pick of #920 (OCPBUGS-37948) and #923(OCPBUGS-41608) for release 4.17
Delete feature simulates a DiskToMirror mode for operator collector.
Since the catalogs are saved in the working-dir under a folder whose name corresponds to the catalog digest, the collector first tries to translate the catalog tag into a digest.
For doing so, it assumes that the catalog is in the local cache. It also assumes the local cache is TLS enabled ([OCPBUGS-37948](https://issues.redhat.com/browse/OCPBUGS-37948)).
For catalogs mirrored in MirrorToMirror, catalog images will not exist in the local cache: Failing to determine the catalog digest from the catalog tag leads to failure in collecting images from catalog. The detele-images.yaml file is therefore empty.
The fix consists in 3 …
> OCPBUGS-41503: [release-4.17] oc-mirror throws error when performing delete operation with --generate

- go.work.sum
- v2/internal/pkg/release/cincinnati.go
- v2/internal/pkg/release/cincinnati_test.go
- v2/internal/pkg/release/interface.go
- v2/internal/pkg/release/local_stored_collector.go
- v2/internal/pkg/release/local_stored_collector_test.go
This fix addresses the issue when the API call to cincinnati (or any error regarding cincinnati)  should be severe and fail immediately
Fixes # OCPBUGS-38461
Locally
Use the following imagesetconfig
```
mirror:
platform:
channels:
- name: stable-4.16
minVersion: 4.16.0
maxVersion: 4.16.5
```
Before doing a mirror-to-disk workflow set the following envar (to any non functioning url)
```
export UPDATE_URL_OVERRIDE=https://a-site-that-does-not-work
```
Execute mirror-to-disk workflow
unset the UPDATE_URL_OVERRIDE
Execute mirror-to-disk workflow
oc-mirror should complete the mirror-to-disk successfully
```
2024/09/25 16:05:06  [WARN]   : ⚠️  --v2 flag identified, flow redirected to the oc-mirror v2 version. This is Tech …
```
> OCPBUGS-38461: oc-mirror should fail when the cincinnati API has errors

- v2/internal/pkg/clusterresources/clusterresources.go
This fix ensures that the siagnature configmap yaml and json files created in clusterresource does not have duplicates
Fixes # OCPBUGS-42428
Locally
Use the following imagesetconfig
```
mirror:
platform:
channels:
- name: stable-4.16
minVersion: 4.16.0
maxVersion: 4.16.0
- name: stable-4.15
minVersion: 4.15.0
maxVersion: 4.15.0
```
Execute mirror-to-disk 
Then execute disk-to-mirror
There should be no duplicate entries in the yaml or json config maps created in working-dir/cluster-resources
yaml configmap output (in this case only 3 entries ) with no duplicates 
i.e sha256-xxxx-id where "xxxx" is not duplicated 
```
apiVersion: v1
binaryData: …
```
> OCPBUGS-42428: Fix duplication of binary data in signature config map

- v2/internal/pkg/archive/image-blob-gatherer.go
- v2/internal/pkg/cli/delete.go
- v2/internal/pkg/cli/executor.go
- v2/internal/pkg/helm/local_stored_collector.go
- v2/internal/pkg/helm/local_stored_collector_test.go
- v2/internal/pkg/helm/new.go
- v2/internal/pkg/mirror/options.go
- v2/internal/pkg/mirror/options_test.go
This PR changes the tlsVerify default to true and adds helm tls support.
Fixes # ([CLID-247](https://issues.redhat.com/browse/CLID-247))
Run all the workflows (mirrorToDisk, diskToMirror and mirrorToMirror) for releases, operators, additional images and helm charts.
When doing the mirrorToMirror or diskToMirror `--dest-tls-verify=false` should be included in case the target registry does not have the TLS enabled
All the flows (mirrorToDisk, diskToMirror and mirrorToMirror) should continue working for releases, operators, additional images, helm charts.
Also the delete should continue working (except for helm which is not implemented yet)
> CLID-247: changes the tlsVerify default to true and adds helm tls support

- v2/internal/pkg/api/v2alpha1/type_internal.go
- v2/internal/pkg/batch/concurrent_worker.go
- v2/internal/pkg/cli/delete.go
- v2/internal/pkg/cli/delete_test.go
- v2/internal/pkg/delete/delete_images.go
- v2/internal/pkg/helm/new.go
This PR implements the code necessary to take into account the helm images in the delete feature.
This PR also change the batch worker to the same being used in the mirroring (concurrent_worker.go)
Fixes # [CLID-253](https://issues.redhat.com/browse/CLID-253)
```
mirror:
helm:
repositories:
- name: podinfo
url: https://stefanprodan.github.io/podinfo
charts:
- name: podinfo
version: 5.0.0
- name: sbo
url: https://redhat-developer.github.io/service-binding-operator-helm-chart/
```
Step 1 - Run `MirrorToDisk`
```
./bin/oc-mirror -c ./alex-tests/alex-isc/clid-28-v2.yaml file:///home/aguidi/go/src/github.com/aguidirh/oc-mirror/alex-tests/cli …
```
> CLID-253: adds helm images to delete feature

- .github/dependabot.yml
Dependabot is enabled in oc-mirror repo, but it is not opening PRs automatically yet. 
Adding the config file as an attempt to enable the creation of PR automatically.
Fixes # [CLID-269](https://issues.redhat.com/browse/CLID-269)
Currently Dependabot alerts are visible for maintainers.
Dependabot alers are visible
> CLID-269: adds dependabot.yml config file for dependabot

- v2/internal/pkg/api/v2alpha1/type_image.go
- v2/internal/pkg/api/v2alpha1/type_internal.go
- v2/internal/pkg/cli/const.go
- v2/internal/pkg/cli/executor.go
- v2/internal/pkg/image/image.go
- v2/internal/pkg/imagebuilder/interface.go
- v2/internal/pkg/imagebuilder/rebuild_catalog.go
- v2/internal/pkg/operator/common.go
- v2/internal/pkg/operator/const.go
- v2/internal/pkg/operator/filtered_collector.go
- v2/internal/pkg/release/graph_test.go
This PR generates the folders based on the digest of the operator catalog filtered. Using the digest of the filtered catalog allows oc-mirror to identify if the operator catalog was already rebuilt previously, avoiding in this way rebuilding again unnecessarily.
With this approach will be also possible to filter a catalog based on the original catalog saved on the local cache.
The operator collector currently is a little complex and the refactorings to make it easier to understand and maintain will be handled in a separated PR.
Fixes [CLID-265](https://issues.redhat.com/browse/CLID-265)
```
mirror:
operators:
- catalog: …
```
> CLID-265,CLID-259,CLID-262: generates folders based on the filtered catalog digest

- pkg/cli/mirror/mirror.go
This PR adds a warning for the deprecation of oc-mirror v1 (starting in 4.18)
Fixes # [CLID-272](https://issues.redhat.com/browse/CLID-272)
With the following command:
```
./bin/oc-mirror -c /home/aguidi/go/src/github.com/aguidirh/oc-mirror/alex-tests/alex-isc/clid-28.yaml file:///home/aguidi/go/src/github.com/aguidirh/oc-mirror/alex-tests/clid-28
```
The following message should appear right in the beginning of the logs:
```
⚠️  oc-mirror v1 is deprecated (starting in 4.18 release) and will be removed in a future release - please migrate to oc-mirror --v2
```
> CLID-272: adds a deprecated message for oc-mirror v1

- v2/internal/pkg/imagebuilder/rebuild_catalog.go
This PR removes some unnecessary zero values definition on the BuildOptions struct.
Fixes [CLID-264](https://issues.redhat.com/browse/CLID-264)
MirrorToDisk and DiskToMirror
Both workflows above should pass and the rebuilt catalog should be in the destination registry.
> CLID-264: removes the default values from the struct definition

- v2/internal/pkg/cli/executor.go
- v2/internal/pkg/imagebuilder/rebuild_catalog.go
- v2/internal/pkg/mirror/options.go
This update adds an optional flag to override the rootless container storage path (usually set in /etc/containers/storage.conf)
Create a directory i.e 
```
mkdir -p /home/lzuccarelli/buildah/share/containers/storage
```
Locally using the following  imagesetconfig and cli
imagesetconfig 
```
mirror:
operators:
packages:
- catalog: registry.redhat.io/redhat/certified-operator-index:v4.16
targetCatalog: other/certified-operator-index
packages:
- name: gitlab-operator-kubernetes
- catalog: registry.redhat.io/redhat/certified-operator-index:v4.15
targetCatalog: other/certified-operator-index
targetTag: v4.15.0 …
```
> CLID-273: Override default container rootless storage path

- v2/internal/pkg/cli/delete.go
This PR changes the collector for the delete feature so it uses the same collector as mirrorToDisk, diskToMirror and mirrorToMirror.
Fixes [CLID-276](https://issues.redhat.com/browse/CLID-276)
```
mirror:
operators:
- catalog: registry.redhat.io/redhat/redhat-operator-index:v4.15 
packages:
- name: 3scale-operator
```
The following commands were run:
m2d
```
./bin/oc-mirror -c /home/aguidi/go/src/github.com/aguidirh/oc-mirror/alex-tests/alex-isc/isc.yaml file:///home/aguidi/go/src/github.com/aguidirh/oc-mirror/alex-tests/clid-276 --v2
```
d2m
```
./bin/oc-mirror -c …
```
> CLID-276: changes the delete feature to use the new collector

- v2/internal/pkg/cli/executor.go
- v2/internal/pkg/operator/common.go
- v2/internal/pkg/operator/common_test.go
- v2/internal/pkg/operator/filtered_collector.go
- v2/internal/pkg/operator/filtered_collector_test.go
- v2/internal/pkg/operator/interface.go
This PR get catalog rebuilding to be done only once in mirror to mirror workflow.
Fixes # [CLID-275](https://issues.redhat.com/browse/CLID-275)
With the following imagesetconfig, Mirror to disk + disk to mirror as well as mirror to mirror are performed.
All catalogs mirrors should be the filtered ones.
```
podman pull docker://sherinefedora:5000/275d/redhat/redhat-operator-index:v4.14
podman pull docker://sherinefedora:5000/275d/other/certified-operator-index:v4.16
podman pull docker://sherinefedora:5000/275d/other/certified-operator-index:v4.15.0
podman pull docker://sherinefedora:5000/275d/redhat/community-operator-index:v4.15.0-c
podman run podman pull docker://sherinefedora:5000/275d/redhat/community-operator-index:v4.15.0-c &
podman ps …
```
> CLID-275: Fix Catalog rebuild in Mirror To Mirror workflow

- v2/go.sum
- v2/internal/pkg/batch/concurrent_worker.go
- v2/internal/pkg/cli/executor.go
- v2/internal/pkg/imagebuilder/catalog_builder.go
- v2/internal/pkg/imagebuilder/interface.go
- v2/internal/pkg/imagebuilder/rebuild_catalog.go
- v2/internal/pkg/operator/filtered_collector.go
- v2/internal/pkg/spinners/spinners.go
* In order to inform the user why Operator Collector is taking long, # [CLID-274](https://issues.redhat.com/browse/CLID-274) adds spinners ( :warning: without adding concurrency) to both:
* the for loop around operator catalog collection
* the for loop around operator catalog rebuild
* In order for catalog rebuild not to be done when `--dry-run`, [CLID-261](https://issues.redhat.com/browse/CLID-261) moves the logic of catalog rebuild away from the `CollectAll` method and into its own separate method within the executor
Mirror to Disk with the following ImageSetConfig passes:
```
mirror:
operators:
packages:
- …
```
> CLID-261,CLID-274: rebuild independently of collect

- v2/internal/pkg/operator/filtered_collector.go
Fixes # [CLID-278](https://issues.redhat.com/browse/CLID-278)
Mirror to mirror twice with same catalog 
pass
> CLID-278: Fix M2M of operator already built

- v2/pkg/cli/cli_wrapper.go
This PR removes the Tech Preview warning from v2.
Fixes [CLID-279](https://github.com/aguidirh/oc-mirror/pull/new/clid-279)
In all workflows (m2d, d2m and mirrorToMirror) the Tech Preview warning should not be showed.
Tech Preview warning should not be showed in the workflows.
> CLID-279: removes the tech preview warning from v2

- v2/internal/pkg/operator/filtered_collector.go
The catalog reference used for oci catalogs should remain the original one for multiple reasons:
* firstly, this reference is the one found in the ISC , and that executor.RebuildCatalogs will use to find the filtered catalog from map CatalogToFBCMap
* secondly, because the OCI image copied into the working-dir is transformed into a single arch one! so when batch is going to mirror from that location, we will start mirroring mono-arch instead of multi-arch
Fixes # OCPBUGS-44789
m2d + d2m as well as m2m multiple times for the imagesetconfig shared in OCPBUGS-44789
no errors
> OCPBUGS-44789: Fix mirroring OCI catalogs multiple times

- v2/internal/pkg/cli/executor.go
This fix addresses the issue when an mirroring using "_internal oc-mirror reserved or key words_" as an example **release-images** in the destination or --from paths
Fixes # OCPBUGS-42862
Use the following cli 
```
bin/oc-mirror --config ocpbugs-42862.yaml file://ocpbugs-42862/release-images --v2
```
If somehow the client does a m2d and then copies the tar to a directory in the enclave and calls it with a keyword (as an example below - it should also fail)
```
bin/oc-mirror --config ocpbugs-42862.yaml --from file:///home/lzuccarelli/some-new-directory/release-images docker://localhost:5000/ocpbugs-42862 --dry-run --v2
```
Should fail (in both cases indicated above)
```
2024/11/28 16:10:34  [INFO]   : 👋 Hello, welcome to oc-mirror
2024/11/28 16:10:34  [INFO]   : ⚙️  setting up the …
```
> OCPBUGS-42862: oc-mirror fails to find the image-references

- v2/internal/pkg/api/v2alpha1/type_internal.go
- v2/internal/pkg/cli/executor.go
- v2/internal/pkg/operator/filtered_collector.go
* Also fixes the spinner staying stuck when errors happen during collection of operators. Introduces a `ToRebuild`(bool) to the `CatalogFilterResult` struct, which is used to handover catalogs between the collection phase and the rebuild phase.
* With this flag, the catalogs in full:true (no need for rebuild) will be skipped at the rebuild phase. 
* A benefit from this commit is to save time by not rebuilding catalogs that are already rebuilt in a previous mirroring.
Fixes # [OCPBUGS-44818](https://issues.redhat.com/browse/OCPBUGS-44818)
M2D + D2M / M2M with 
```yaml
mirror:
operators: 
- catalog: quay.io/skhoury/light-catalog:latest
full: true
```
Success
> OCPBUGS-44818: Fix mirroring catalogs with full:true

- go.work.sum
- v2/go.mod
- v2/go.sum
- v2/internal/pkg/additional/local_stored_collector.go
- v2/internal/pkg/additional/local_stored_collector_test.go
- v2/internal/pkg/cli/delete.go
- v2/internal/pkg/cli/delete_test.go
- v2/internal/pkg/cli/executor.go
- v2/internal/pkg/helm/local_stored_collector.go
- v2/internal/pkg/helm/local_stored_collector_test.go
- v2/internal/pkg/operator/catalog_handler_test.go
- v2/internal/pkg/operator/common.go
- v2/internal/pkg/operator/common_test.go
- v2/internal/pkg/operator/filtered_collector.go
This PR attempts to provide a way forward for customers who are looking to use oc-mirror v2 delete functionality for cleaning up artifacts previously mirrored with oc-mirror v1.
For images referenced by digest, and not by tag, v1 and v2 both attribute a tag to prevent the mirrored image from being deleted because it's not referenced. But they do so in a different way:
* for **operator images** 
* v1 uses oc underneath, which [applies a hash](https://github.com/openshift/oc/blob/bdce85daf64eda40dd1b604270b85c67a296bc93/pkg/cli/admin/catalog/mirrorer.go#L176-L185) on the complete image reference
* v2 uses the digest as the hash
* for **release images**: both v1 and v2 use the tagging convension for release components
* for **helm charts**
* v1 uses `latest`
* v2 uses a combination of digest …
> OCPBUGS-43731,OCPBUGS-44836:Ability to generate delete-images.yaml with v1 tags

- v2/internal/pkg/release/local_stored_collector.go
This bugfix addresses the issue when mirroring a release that use a digest rather than a tag
Fixes # OCPBUGS-44033
Use the following isc
```
mirror:
platform:
release: registry.ci.openshift.org/ocp/release@sha256:a29a109f286c77aecb71906696830c2f48c9b6ba0df77b88a7fb5c4399f3334a
```
1. Execute a simple m2m command
```
bin/oc-mirror --config ocpbugs-44033.yaml --workspace file://ocpbugs-44033 docker://localhost:5000/ocpbugs-44033 --v2 --dest-tls-verify=false
```
2. Execute a disk to mirror 
```
bin/oc-mirror --config ocpbugs-44033.yaml --from file://ocpbugs-44033 docker://localhost:5000/ocpbugs-44033 --v2 --dest-tls-verify=false
```
3. Repeat for mirror to disk and then disk to mirror
Mirroring should pass for all scenarios
> OCPBUGS-44033: Failed to mirror ocp payload using digest

- v2/internal/pkg/mirror/options.go
- v2/internal/pkg/release/local_stored_collector.go
Fixes # OCPBUGS-43825
Performed the scenario described in the bug: M2M with graph = true, followed by delete workflow
No warnings appear during `delete --generate`
delete-images.yaml contains the graph image
> OCPBUGS-43825: Fix graph image not deletable if mirrored by m2m

- v2/internal/pkg/clusterresources/clusterresources.go
- v2/internal/pkg/clusterresources/clusterresources_test.go
- v2/internal/pkg/clusterresources/const.go
Fixes # OCPBUGS-42849
Unit test added
M2M produces confimap containing name
unit tests pass
> OCPBUGS-42849: Assign a static name to the release signature configmap

- v2/internal/pkg/additional/local_stored_collector.go
- v2/internal/pkg/additional/local_stored_collector_test.go
- v2/internal/pkg/operator/common.go
- v2/internal/pkg/operator/common_test.go
- v2/internal/pkg/operator/filtered_collector_test.go
- v2/internal/pkg/operator/local_stored_collector_test.go
This issue addresses the standard for all mirrored images on digest for both additonalImages and operators
They will follow the tag as "algorithm-digest" i.e 
If I mirrored this additionalimage 
```
quay.io/openshifttest/hello-openshift@sha256:61b8f5e1a3b5dbd9e2c35fd448dc5106337d7a299873dd3a6f0cd8d4891ecc27
```
I should expect the tag to be in the form of
```
destination-registry/openshifttest/hello-openshift/sha256-61b8f5e1a3b5dbd9e2c35fd448dc5106337d7a299873dd3a6f0cd8d4891ecc27
```
And the same applies to operators. The standard has already been applied to release images and helm chart images
Fixes # OCPBUGS-44901
Use the following isc 
```
mirror: …
```
> OCPBUGS-44901: Align tag format for additionalImages and operators

- v2/internal/pkg/cli/executor.go
`error` is a valid log level but it was not being considered during level validation.
Github / Jira issue: OCPBUGS-45215
```bash
$ ./bin/oc-mirror --config /dev/null file:///dev/null --v2 --log-level banana
2025/01/08 12:41:08  [INFO]   : 👋 Hello, welcome to oc-mirror
2025/01/08 12:41:08  [INFO]   : ⚙️  setting up the environment for you...
2025/01/08 12:41:08  [ERROR]  : log-level has an invalid value banana , it should be one of (info,debug,trace,error)
$ ./bin/oc-mirror --config /dev/null file:///dev/null --v2 --log-level error
2025/01/08 12:41:20  [INFO]   : 👋 Hello, welcome to oc-mirror
2025/01/08 12:41:20  [INFO]   : ⚙️  setting up the environment for you...
2025/01/08 12:41:20  [ERROR]  :  config GVK not recognized: /, Kind=
```
"error" …
> OCPBUGS-45215: cli: fix log level validation

- v2/internal/pkg/cli/executor.go
- v2/internal/pkg/cli/executor_test.go
The manifests which are generated under working-dir/cluster-resources (IDMS,ITMS etc) shouldn't be deleted automatically.
Github / Jira issue: OCPBUGS-44714
```bash
$ touch /mirror-v2-data/working-dir/cluster-resources/do-not-delete-me.txt
$ ./bin/oc-mirror delete --generate --v2 -c /tmp/disc.yaml docker://example.com --workspace file:///mirror-v2-data
$ test -e /mirror-v2-data/working-dir/cluster-resources/do-not-delete-me.txt
```
Files under working-dir/cluster-resources are not deleted.
> OCPBUGS-44714: don't clear cluster-resources dir on `delete --generate`

- test/e2e/lib/util.sh
`go install` ignores go.mod, so it's possible to install a version not compatible with the system Golang version when using `@latest`.
This should fix the following error in CI for older branches:
```
/go/src/github.com/openshift/oc-mirror/test/e2e/operator-test.17343 /go/src/github.com/openshift/oc-mirror
go: downloading github.com/google/go-containerregistry v0.20.3
go: github.com/google/go-containerregistry/cmd/crane@latest: github.com/google/go-containerregistry@v0.20.3 requires go >= 1.23.0 (running go 1.22.9; GOTOOLCHAIN=local)
/go/src/github.com/openshift/oc-mirror/test/e2e/lib/util.sh: line 17: PID_DISCONN: unbound variable
```
Please describe the tests that you ran to verify your changes. Provide instructions so …
> OCPBUGS-48537: [release-4.17] e2e: use same version of crane as in go.mod

- test/e2e/lib/util.sh
`go install` ignores go.mod, so it's possible to install a version not compatible with the system Golang version when using `@latest`.
This should fix the following error in CI for older branches:
```
/go/src/github.com/openshift/oc-mirror/test/e2e/operator-test.17343 /go/src/github.com/openshift/oc-mirror
go: downloading github.com/google/go-containerregistry v0.20.3
go: github.com/google/go-containerregistry/cmd/crane@latest: github.com/google/go-containerregistry@v0.20.3 requires go >= 1.23.0 (running go 1.22.9; GOTOOLCHAIN=local)
/go/src/github.com/openshift/oc-mirror/test/e2e/lib/util.sh: line 17: PID_DISCONN: unbound variable
```
Please describe the tests that you ran to verify your changes. Provide instructions so …
> OCPBUGS-48559: [release-4.13] e2e: use same version of crane as in go.mod

- v2/internal/pkg/api/operator-framework/v1/clustercatalog_types.go
- v2/internal/pkg/cli/executor.go
- v2/internal/pkg/cli/executor_test.go
- v2/internal/pkg/clusterresources/clusterresources.go
- v2/internal/pkg/clusterresources/clusterresources_test.go
- v2/internal/pkg/clusterresources/interface.go
Generate ClusterCatalog resources as needed when managing operators with OLM v1.
Github / Jira issue: OCPBUGS-45161
```bash
$ ./bin/oc-mirror --v2 --config ~/Downloads/isc.yaml file://~/Downloads/mirror-v2-data
$ ./bin/oc-mirror --v2 --config ~/Downloads/isc.yaml --from file://~/Downloads/mirror-v2-data docker://localhost:5000/mirror-v2-data
[...]
2025/01/22 16:18:09  [INFO]   : 📄 Generating CatalogSource file...
2025/01/22 16:18:09  [INFO]   : ~/Downloads/mirror-v2-data/working-dir/cluster-resources/cs-redhat-operator-index-v4-16.yaml file created
2025/01/22 16:18:09  [INFO]   : 📄 Generating ClusterCatalog file...
2025/01/22 16:18:09  [INFO]   : ~/Downloads/mirror-v2-data/working-dir/cluster-resources/cc-redhat-operator-index-v4-16.yaml file …
```
> OCPBUGS-45161: Generate ClusterCatalog resources for operator catalogs

- v2/docs/delete-functionality.md
- v2/internal/pkg/cli/delete_test.go
- v2/internal/pkg/cli/executor.go
- v2/internal/pkg/cli/executor_test.go
- v2/internal/pkg/mirror/options.go
This should be easier for users to find since it's shown in the output of `--help` compared to the `OC_MIRROR_CACHE` env var.
Github / Jira issue: [CLID-301](https://issues.redhat.com//browse/CLID-301)
```bash
$ ./bin/oc-mirror --v2 --help
[...]
Flags:
--authfile string                path of the authentication file. Default is ${XDG_RUNTIME_DIR}/containers/auth.json
--cache-dir string               oc-mirror cache directory
-c, --config string                  Path to imageset configuration file
$ OC_MIRROR_CACHE=/home/ ./bin/oc-mirror --v2 --cache-dir /tmp/ -c ~/Downloads/isc.yaml file:///tmp/banana
2025/01/23 13:31:44  [INFO]   : 👋 Hello, welcome to oc-mirror
2025/01/23 13:31:44  [INFO]   : ⚙  setting up the environment for you...
2025/01/23 …
```
> CLID-301: add --cache-dir command line option

- v2/internal/pkg/api/v2alpha1/type_internal.go
- v2/internal/pkg/operator/common.go
- v2/internal/pkg/operator/filtered_collector.go
When an operator catalog was mirrored with v1 and the catalog was on disk (oci:// on the ImageSetConfiguration) the delete feature was not working properly. The changes on this PR is to fix this bug.
Github / Jira issue: [OCPBUGS-45059](https://issues.redhat.com/browse/OCPBUGS-45059)
With the following ImageSetConfiguration from oc-mirror v1
```
mirror:
operators:
- catalog: oci:///home/aguidi/go/src/github.com/aguidirh/oc-mirror/alex-tests/testying/redhat-operator-index
targetCatalog: "ocicatalog73452"
targetTag: "v16"
packages:
- name: cluster-kube-descheduler-operator
```
Run mirror to mirror (m2m):
```
./bin/oc-mirror -c ./alex-tests/alex-isc/ocpbugs/ocpbugs-45059-v1.yaml …
```
> OCPBUGS-45059: fixes the delete when catalog mirrored  with v1 from disk (oci://)

- v2/internal/pkg/cli/delete.go
- v2/internal/pkg/cli/executor.go
This is a fallout of 41c0161728e1b0ed1a63172f36bcc53424dbb09c
```
$ ./bin/oc-mirror --v2 delete --generate --cache-dir /tmp/ -c ~/Downloads/disc.yaml --workspace file://~/Downloads/mirror-v2-data docker://localhost:5000
2025/01/24 12:30:47  [INFO]   : 👋 Hello, welcome to oc-mirror
2025/01/24 12:30:47  [INFO]   : ⚙  setting up the environment for you...
2025/01/24 12:30:47  [INFO]   : 🔀 workflow mode: diskToMirror / delete
2025/01/24 12:30:47  [INFO]   : 🕵  going to discover the necessary images...
2025/01/24 12:30:47  [INFO]   : 🔍 collecting release images...
[...]
```
> CLID-301: add --cache-dir to delete command

- v2/internal/pkg/clusterresources/clusterresources.go
- v2/internal/pkg/clusterresources/clusterresources_test.go
It is a cluster-wide resource, so we don't need to set the namespace.
Github / Jira issue: OCPBUGS-49723
> OCPBUGS-49723: v2/clusterresources: remove ClusterCatalog namespace

- v2/internal/pkg/batch/concurrent_chan_worker.go
- v2/internal/pkg/cli/executor.go
- v2/internal/pkg/emoji/const.go
There was a bug with an infinite loop when there was no images to mirror.
Github / Jira issue: [OCPBUGS-49730](https://issues.redhat.com/browse/OCPBUGS-49730)
With the following ImageSetConfiguration (where the catalog path on disk does not exist)
```
mirror:
operators:
- catalog: oci:///home/aguidi/go/src/github.com/aguidirh/oc-mirror/openshift-tests-private/redhat-operator-index
targetCatalog: "ocicatalog73452"
targetTag: "v16"
packages:
- name: cluster-kube-descheduler-operator
```
Run the m2d
```
./bin/oc-mirror -c ./alex-tests/alex-isc/ocpbugs/ocpbugs-49730.yaml file:///home/aguidi/go/src/github.com/aguidirh/oc-mirror/alex-tests/ocpbugs-49730 --v2
```
The flow should stop …
> OCPBUGS-49730: fixes the infinite loop when no images to mirror

- v2/internal/pkg/cli/executor.go
This PR adds the flag parallel-layers to the `--help` 
Github / Jira issue: [OCPBUGS-49798](https://issues.redhat.com/browse/OCPBUGS-49798)
```
oc-mirror --v2 --help
```
```
oc-mirror delete --v2 --help
```
The `parallel-layers` flag should be show in both commands above.
> OCPBUGS-49798: exposes the parallel-layers flag

- v2/internal/pkg/release/core-cincinnati.go
* If we save the graph data to disk before checking it's valid, we can run into unmarshaling errors later like:
```
2025/02/05 02:14:36  [ERROR]  : [GetReleaseReferenceImages] error list [APIRequestError: channel "stable-4.16": ResponseInvalid: invalid character 'a' after top-level value]
```
*  Just returning unmarshaling errors is not very useful information:
```
ResponseInvalid: invalid character 'a' after top-level value
```
Let's add more context to that error when reading graph data from the
working dir so we know which is the offending file. …
> NO-JIRA:  only save graph data if it's valid json

- v2/internal/pkg/operator/catalog_handler.go
- v2/internal/pkg/operator/filtered_collector.go
This PR fixes the bug where a bundle related image could be skipped during the collection. The operator would not work as expected because of missing related images.
Github / Jira issue: [OCPBUGS-49991](https://issues.redhat.com/browse/OCPBUGS-49991)
```
mirror:
operators:
- catalog: registry.redhat.io/redhat/community-operator-index:v4.13
packages:
- name: openshift-nfd-operator
- name: kuadrant-operator
- name: argocd-operator
```
Run `m2d`
Only the `argocd-operator` will be mirrored. The `openshift-nfd-operator` and `kuadrant-operator` will be skipped on the collector phase because of issues on its related images.
NOTE: this PR does …
> OCPBUGS-49991: fixes bundle related images being skipped

- v2/go.mod
- v2/internal/pkg/batch/concurrent_chan_worker.go
- v2/internal/pkg/batch/concurrent_worker.go
- v2/internal/pkg/cli/executor.go
- v2/internal/pkg/mirror/options.go
- v2/internal/pkg/operator/filtered_collector.go
If oc-mirror is run behind a CI/CD pipeline or if output is redirected to a file/pipe, the spinners' output is not shown and it looks like oc-mirror is not making any progress. By using a regular log line instead, we can still show some progress logs in those cases.
m2d with `| grep ''` to force a non-tty output.
Log lines are printed as images are copied (or fail to copy).
> OCPBUGS-50559: v2: disable spinners when not running in a tty

- v2/internal/pkg/batch/concurrent_chan_worker.go
Before this fix the spinner was being triggered before the semaphore was locked. 
Because of that the output was giving the wrong feeling that even when `--parallel-images=1`, two images were being triggered.
Github / Jira issue: [OCPBUGS-50685](https://issues.redhat.com/browse/OCPBUGS-50685)
m2d with `--parallel-images=1`
```
./bin/oc-mirror -c ./alex-tests/alex-isc/ocpbugs/ocpbugs-50685.yaml file:///home/aguidi/go/src/github.com/aguidirh/oc-mirror/alex-tests/ocpbugs-50685 --v2 --parallel-images=1
````
Only one go-routine triggered at a time.
> OCPBUGS-50685: fix: make the spinner trigger after semaphore is released

- v2/internal/pkg/archive/archive_test.go
- v2/internal/pkg/release/local_stored_collector.go
- v2/tests/working-dir-fake/hold-release/ocp-release/v4.13.10/release-manifests/0000_50_installer_coreos-bootimages.yaml
- v2/tests/working-dir-fake/hold-release/ocp-release/v4.13.9/release-manifests/0000_50_installer_coreos-bootimages.yaml
If requested by users in the ImageSetConfiguration and these resources are not found, either in the mirror or in the local cache, `oc-mirror` should error out instead of just printing a warning and continuing.
> OCPBUGS-49990: v2/release: error out for kubevirt/graph image errors

- go.mod
- go.sum
- go.work.sum
The bumped version can now handle the `ocischema.DeserializedImageIndex` manifest type.
Without this fix, oc-mirror v1 fails with:
```
oc-mirror failed with error: the manifest type *ocischema.DeserializedImageIndex is not supported
```
Github / Jira issue: OCPBUGS-44103
```
$ yq e /tmp/isc.yaml
mirror:
operators:
- catalog: registry.redhat.io/redhat/redhat-operator-index:v4.16
packages:
- name: openstack-operator
channels:
- name: stable-v1.0
minVersion: 1.0.4
maxVersion: 1.0.4
$ ./bin/oc-mirror --config /tmp/isc.yaml file:////oc-mirror-ocpbugs-49990-2
```
No `DeserializedImageIndex` errors.
> OCPBUGS-44103: bump oc fork version

- v2/internal/pkg/cli/executor.go
The --dry-run mode implies no changes to existing resources like previously generated cluster-resources.
Github / Jira issue: OCPBUGS-50963
```
$ touch oc-mirror-data/working-dir/cluster-resources/DONOTDELETEME
$ ./bin/oc-mirror --v2 --config isc.yaml --from file:///oc-mirror-data/ docker://localhost:5000/ocpbugs-50963 --dry-run
$ test -f oc-mirror-data/working-dir/cluster-resources/DONOTDELETEME
$ echo $?
0
$ ./bin/oc-mirror --v2 --config isc.yaml --from file:///oc-mirror-data/ docker://localhost:5000/ocpbugs-50963
$ test -f oc-mirror-data/working-dir/cluster-resources/DONOTDELETEME
$ echo $?
1
```
working-dir/cluster-resources are not deleted when in `--dry-run` mode.
> OCPBUGS-50963: v2: don't clean cluster resources on dry-run mode

- v2/internal/pkg/archive/archive_test.go
- v2/internal/pkg/release/local_stored_collector.go
- v2/tests/working-dir-fake/hold-release/ocp-release/v4.13.10/release-manifests/0000_50_installer_coreos-bootimages.yaml
- v2/tests/working-dir-fake/hold-release/ocp-release/v4.13.9/release-manifests/0000_50_installer_coreos-bootimages.yaml
If requested by users in the ImageSetConfiguration and these resources are not found, either in the mirror or in the local cache, `oc-mirror` should error out instead of just printing a warning and continuing.
> OCPBUGS-50981: [release-4.18] v2/release: error out for kubevirt/graph image errors

- go.mod
- go.sum
- go.work.sum
This PR fixes mholt/archiver: path traversal vulnerability by replacing `github.com/mholt/archiver/v3` with `github.com/aguidirh/archiver/v3 v3.5.0-ocmirror1` which contains an [additional commit](https://github.com/mholt/archiver/compare/master...aguidirh:archiver:CVE-2024-0406) on [CVE-2024-0406](https://github.com/aguidirh/archiver/tree/CVE-2024-0406) branch (based on v3.5.0) to fix the CVE.
Github / Jira issue: [CLID-203](https://issues.redhat.com/browse/CLID-203) / [OCPBUGS-26771](https://issues.redhat.com/browse/OCPBUGS-26771)
`govulncheck ./...`
No vulnerability found.
> CLID-203,OCPBUGS-26771: fixes CVE-2024-0406 

- go.mod
- go.sum
- go.work.sum
This PR fixes mholt/archiver: path traversal vulnerability by replacing `github.com/mholt/archiver/v3` with `github.com/aguidirh/archiver/v3 v3.5.0-ocmirror1` which contains an [additional commit](https://github.com/mholt/archiver/compare/master...aguidirh:archiver:CVE-2024-0406) on [CVE-2024-0406](https://github.com/aguidirh/archiver/tree/CVE-2024-0406) branch (based on v3.5.0) to fix the CVE.
Github / Jira issue: [OCPBUGS-51386](https://issues.redhat.com/browse/OCPBUGS-51386)
`govulncheck ./...`
No vulnerability found.
> [release-4.18] OCPBUGS-51386: fixes CVE-2024-0406

- Makefile
- cmd/oc-mirror/main.go
- v2/hack/run_and_pprof.sh
- v2/internal/pkg/cli/executor.go
- v2/internal/pkg/mirror/options.go
This PR removes the `-race` from the build target on the Make file to improve the performance.
Also this PR adds the cpu and memory profiling. Both profiles are enabled by using `--cpu-prof` and `--mem-prof` flags during the workflows (m2m/d2m/m2m).
Two new profile files are generated at the same place where the command line was run named `cpu.prof` and `mem.prof`. Both files will be used by the new bash script command `run_and_pprof.sh` added under `v2/hack/`.
The bash script will launch a web browser on `127.0.0.1:6775` for cpu profiling, `127.0.0.1:6776` for mem profiling and `127.0.0.1:6775` for diff profiling, where the graphs can be analysed. 
In the web browser it is possible to filter the graphs, for example by `focus`, `ignore` or `show_from`. These filters the graph only for …
> CLID-325: adds cpu and memory profiling / removes the race from build target

- v2/.golangci.yaml
We just want to check for error wrapping in errors coming from external libs, not our own code (for now).
This should avoid unnecessary around wrapping our own errors.
No `wrapcheck` lint errors from our own code.
> no-jira: stop `wraperr` linter from treating our code as external lib

- v2/internal/pkg/api/v2alpha1/type_internal.go
- v2/internal/pkg/operator/common.go
- v2/internal/pkg/operator/common_test.go
- v2/internal/pkg/operator/filtered_collector.go
- v2/internal/pkg/operator/filtered_collector_test.go
Refactor the FilteredCollector for Operators so we can return errors in case we fail to collect some operator. We still try to collect all operators but we return all errors found at the end of collection.
Github / Jira issue: OCPBUGS-50680
> OCPBUGS-50680: v2/operator: refactor operator FilteredCollector

- v2/internal/pkg/operator/catalog_handler.go
- v2/internal/pkg/operator/catalog_handler_test.go
If no related was found for a catalog, the collection for this catalog should fail instead of passing as it is currently happening.
Github / Jira issue: [OCPBUGS-52588](https://issues.redhat.com/browse/OCPBUGS-52588)
With the following ImageSetConfiguration (which contains only one invalid operator):
```
mirror:
operators:
- catalog: registry.redhat.io/redhat/redhat-operator-index:v4.17
packages:
- name: netscaler-operator 
```
`m2d` should fail:
```
aguidi@fedora:~/go/src/github.com/aguidirh/oc-mirror$ ./bin/oc-mirror -c ./alex-tests/alex-isc/ocpbugs/ocpbugs-52588.yaml file://alex-tests/ocpbugs-52588 --v2
2025/03/10 17:21:52  [INFO]   : 👋 Hello, welcome to oc-mirror …
```
> OCPBUGS-52588: fix: error when no related image was found

- pkg/cli/mirror/options.go
- v2/internal/pkg/cli/executor.go
As of 4.18, oc-mirror --v2 is GA.
```
$ oc-mirror --help
$ oc-mirror --v2 --help
```
No mentions of v2 being TechPreview.
> OCPBUGS-52969: remove TechPreview mentions of v2 in --help

- v2/internal/pkg/cli/delete.go
s/cahce/cache
Github / Jira issue: OCPBUGS-52978
```fish
❯ ./bin/oc-mirror --v2 delete --help
[...]
--generate                  Used to generate the delete yaml for the list of manifests and blobs , used in the step to actually delete from local cache and remote registry
```
The output says "cache" instead of "cahce"
> OCPBUGS-52978: delete: fix typo in --help output

- Makefile
We were specifying the wrong path to the `version` pkg during build, resulting in the `oc-mirror --v2 version` command having no version info:
```
❯ ./bin/oc-mirror --v2 version
2025/03/11 13:27:13  [INFO]   : 👋 Hello, welcome to oc-mirror
2025/03/11 13:27:13  [INFO]   : ⚙️  setting up the environment for you...
WARNING: This version information is deprecated and will be replaced with the output from --short. Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-unknown", GitCommit:"", GitTreeState:"", BuildDate:"", GoVersion:"go1.23.6", Compiler:"gc", Platform:"linux/amd64"}
```
Github / Jira issue: OCPBUGS-52960
```
oc-mirror --v2 version
```
Version info in the output:
```
❯ …
```
> OCPBUGS-52960: v2: fix setting version during build

- go.work.sum
- v2/go.mod
- v2/go.sum
This is a manual bug fix for OCPBUGS-54727/[OCPBUGS-52471](https://issues.redhat.com/browse/OCPBUGS-52471).
A [cherry pick](https://github.com/sherine-k/catalog-filter/commits/v0.0.3%2B1/) of the exact fix based on the v0.0.3 version of catalog-filter for 4.18 release + [v0.0.3+1](https://github.com/sherine-k/catalog-filter/releases/tag/v0.0.3%2B1) tag is created.
on the oc-mirror side, the fix is to use this new tag v0.0.3+1.
Perform a mirror to disk with the ISC from the original bug:
```
mirror:
operators:
- catalog: registry.redhat.io/redhat/community-operator-index:v4.16
packages:
- name: assisted-service-operator
```
No OOM
> [release-4.18] OCPBUGS-54727: oc-mirror process gets killed abrutply

- v2/internal/pkg/api/kubernetes/core/type_configmap.go
- v2/internal/pkg/clusterresources/clusterresources.go
- v2/internal/pkg/clusterresources/clusterresources_test.go
This PR helps add an annotation to all cluster resources generated by oc-mirror.
Right now the annotation is `author: oc-mirror` , but let's discuss what is the right annotation to use. 
This way, on a cluster, when users need to remove/update/view IDMS/ITMS/CatalogSource generated by oc-mirror they could use:
```bash
oc get idms jsonpath='{.items[?(@.metadata.annotations.author=oc-mirror)].metadata.name}'
```
Github / Jira issue: [CLID-321](https://issues.redhat.com/browse/CLID-321)
I tested this only for additionalImages.
```yaml
mirror:
- name: registry.redhat.io/ubi9/ubi-micro:latest
```
```yaml
---
apiVersion: config.openshift.io/v1
kind: …
```
> CLID-321: Add annotations to resources generated by oc-mirror v2

- v2/.golangci.yaml
- v2/Makefile
- v2/internal/pkg/cli/delete.go
- v2/internal/pkg/cli/executor.go
- v2/internal/pkg/release/cincinnati.go
- v2/internal/pkg/release/cincinnati_test.go
- v2/internal/pkg/release/local_stored_collector_test.go
This fix addresses the issue in signature verification for rc (release-candidate) images but skips engineering candidate images (this will be updated once we have the full cosign feature implemented in oc-mirror refer to [OCPSTRAT-1869](https://issues.redhat.com/browse/OCPSTRAT-1869) ) 
An update to this issue is check if we can get a digest from the image by tag
Github / Jira issue:  [OCPBUGS-50617](https://issues.redhat.com/browse/OCPBUGS-50617)
Verified locally using the following imagesetconfig
```
mirror:
platform:
graph: true
release: quay.io/openshift-release-dev/ocp-release@sha256:e0907823bc8989b02bb1bd55d5f08262dd0e4846173e792c14e7684fbd476c0d
```
Then with the following imagesetconfig
```
kind: …
```
> OCPBUGS-50617: oc-mirror does not create signature files

- v2/internal/pkg/cli/delete.go
- v2/internal/pkg/cli/executor.go
- v2/internal/pkg/delete/delete_images.go
This change makes the delete command work on a best-effort basis: it will generate a file and delete the images it can and return all errors found at the end instead of stopping on the first error.
Github / Jira issue: OCPBUGS-54653
See PR comments.
`oc-mirror --v2 delete` doesn't stop at the first failure.
> OCPBUGS-54653: delete: continue on errors

- go.work.sum
- v2/go.mod
- v2/internal/pkg/imagebuilder/builder.go
Right now the go-containerregistry lib is using the default docker+podman locations. If oc-mirror is run with `--authfile` pointing to a custom location, it will be used for other images except the graph image.
This change adds a custom keychain with the contents of --authfile so it is picked up by go-containerregistry.
Fixes #1122
Github / Jira issue: OCPBUGS-54220
m2m with `--authfile` set
```
unset DOCKER_CONFIG
unset REGISTRY_AUTH_FILE
rm -f ~/.docker/config.json ~/.config/containers/auth.json ${XDG_RUNTIME_DIR}/containers/auth.json
❯ ~/prjs/github.com/openshift/oc-mirror-return-values/bin/oc-mirror --v2 --config gisc.yaml --workspace file://data/pull-secret --authfile ~/prjs/oc-mirror/pull-secret.json docker://quay.io/<user>/<namespace> …
```
> OCPBUGS-54220: v2/imgbuilder: use --authfile when set

- v2/internal/pkg/api/v2alpha1/type_internal.go
- v2/internal/pkg/cli/executor.go
- v2/internal/pkg/registriesd/error.go
- v2/internal/pkg/registriesd/registriesd.go
- v2/internal/pkg/registriesd/types.go
This PR implements the signature mirroring mechanism as specified in the [containers/image docs](https://github.com/containers/image/blob/main/docs/containers-registries.d.5.md), which allows a more granular way of disabling/enabling signature mirroring by transport, registry, namespace and image.
Github / Jira issue: [OCPBUGS-55100](https://issues.redhat.com/browse/OCPBUGS-55100)
```
mirror:
platform:
channels:
- name: stable-4.18
minVersion: 4.18.1
maxVersion: 4.18.1
graph: true
operators:
- catalog: registry.redhat.io/redhat/redhat-operator-index:v4.18
packages:
- name: …
```
> OCPBUGS-55100: implements registries.d file as specified in containers/image docs

- v2/internal/pkg/cli/executor.go
Changes the signature mirroring default to disabled.
Fixes [OCPBUGS-56088](https://issues.redhat.com/browse/OCPBUGS-56088)
```
./bin/oc-mirror --v2 --help
```
```
--remove-signatures              Do not copy image signature (default true)
```
> OCPBUGS-56088: changes the signature mirroring default to disabled

- v2/internal/pkg/cli/executor.go
This issue aligns functionality for `blockedImages` with v1, allowing the use of regular expressions for the selection of the images to exclude.
This alignment is important for [OCPSTRAT-1874](https://issues.redhat.com/browse/OCPSTRAT-1874), where the intention is to filter out from the release any components that are irrelevant to the use case such as cloud provider components. 
Because release components are referenced by digest, and that the destination image reference tag is the only one to contain the component name, the logic in `excludeImages` is checking both the origin and the destination references. 
Github / Jira issue: [OCPBUGS-56117](https://issues.redhat.com/browse/OCPBUGS-56117)
With the imageSetConfig below , I performed a …
> OCPBUGS-56117: Make v2 blockedImages use regular expressions

- v2/internal/pkg/archive/archive.go
- v2/internal/pkg/archive/archive_test.go
- v2/internal/pkg/cli/executor.go
We were cleaning up past archives only when strict archiving was set. This could generate a situation where, after a first run when X archive files were created, the second run with a diff of Y archives, Y < X, would just overwrite the first Y archives but leave the remaining X-Y in the working dir. Running d2m would copy all the X archives, causing weird failures.
Github / Jira issue: OCPBUGS-54443
1. Run m2d
2. Copy `mirror_000001.tar` into `mirror_00000[2-5].tar`
3. Run m2d again and check that the tar files were deleted. 
Archive files are deleted before m2d runs.
> OCPBUGS-54443: v2/cli: always remove past archives before m2d

- v2/internal/pkg/archive/unarchive.go
- v2/internal/pkg/archive/unarchive_test.go
- v2/internal/pkg/cli/executor.go
Populating the cache registry takes 2 hours for 300GBs of container content. This means oc-mirror v2 has no output on the CLI for 2 hours. Users see this as a stuck process.
Github / Jira issue: OCPBUGS-55966
```
❯ ~/prjs/github.com/openshift/oc-mirror-return-values/v2/build/oc-mirror --config isc.yaml --from file://data/untar-progress docker://localhost:5000 --log-level debug
2025/05/09 02:08:27  [INFO]   : 👋 Hello, welcome to oc-mirror
2025/05/09 02:08:27  [INFO]   : ⚙️  setting up the environment for you...
2025/05/09 02:08:27  [INFO]   : 🔀 workflow mode: diskToMirror 
2025/05/09 02:08:27  [DEBUG]  : helm.New opts.SrcImage.TlsVerify false
2025/05/09 02:08:27  [DEBUG]  : local storage registry will log to …
```
> OCPBUGS-55966: v2/archive: print unarchive progress

- v2/internal/pkg/operator/filtered_collector.go
Currently the signature verification for operator catalog image during collection is failing. This is happening because during the collection phase the operator catalog image is converted to OCI format, so the signature verification will fail because it does not match the original image. 
This PR disables the signature verification of the operator catalog image during the collection phase.
Github / Jira issue: [OCPBUGS-56378](https://issues.redhat.com/browse/OCPBUGS-56378)
With the following ImageSetConfiguration
```
mirror:
operators:
- catalog: registry.redhat.io/redhat/redhat-operator-index:v4.18
packages:
- name: 3scale-operator
```  
Run `m2d` …
> OCPBUGS-56378: disables the signature verification on operator catalog collection

- Dockerfile
Testing with Dockerfile failed on Power.
We had to update the Dockerfile to use 1.23
Github / Jira issue: https://issues.redhat.com/browse/OCPBUGS-56642
> OCPBUGS-56642: update the Dockerfile to work with the 1.23 go.mod

- v2/internal/pkg/cli/executor.go
- v2/internal/pkg/mirror/options.go
- v2/internal/pkg/release/signature.go
This fix addresses the issue when no signature is found (or published) for a specific release image (typical use case is in prow build piplines)
Github / Jira issue:  OCPBUGS-56009
Locally using the following isc 
```
mirror:
platform:
release: quay.io/oc-mirror/release/test-release-index@sha256:f81792339c8b5934191d18a53b18bc1d584e01a9f37d59c0aa6905b00200aa1b
```
And using the oc-mirror  with the flag --ignore-release-signature (for all flows  mirror-to-disk, disk-to-mirror, mirror-to-mirror)
No signature error's expected
> OCPBUGS-56009: Bug fix for no release signature found

- v2/go.mod
- v2/internal/pkg/imagebuilder/builder.go
This is a manual cherry-pick of https://github.com/openshift/oc-mirror/pull/1136 due to merge conflicts.
Right now the go-containerregistry lib is using the default docker+podman locations. If oc-mirror is run with `--authfile` pointing to a custom location, it will be used for other images except the graph image.
This change adds a custom keychain with the contents of --authfile so it is picked up by go-containerregistry.
Github / Jira issue: OCPBUGS-55701
> [release-4.19] OCPBUGS-55701: v2/imgbuilder: use --authfile when set

- v2/internal/pkg/archive/archive.go
- v2/internal/pkg/archive/archive_test.go
- v2/internal/pkg/archive/error.go
- v2/internal/pkg/archive/image-blob-gatherer.go
- v2/internal/pkg/archive/image-blob-gatherer_test.go
When running `m2d` with `--remove-signatures=false`, failing to add a release signature (except the graph image which does not have a signature) to the archive should stop the workflow.
Github / Jira issue: [OCPBUGS-55076](https://issues.redhat.com/browse/OCPBUGS-55076)
Developed unit tests for each scenario.
Unit tests should pass.
> OCPBUGS-55076: adds code to handle signature errors in the archive pkg

- v2/internal/pkg/archive/unarchive.go
- v2/internal/pkg/archive/unarchive_test.go
Without special consideration, `--workdir .` will cause path sanitization to fail because of how Golang handles `.` after `filepath.Clean`.
Github / Jira issue: OCPBUGS-57387
No unarchive errors when `--workdir .` is used.
> OCPBUGS-57387: v2/archive: fix sanitization of `.`

- v2/internal/pkg/operator/filtered_collector.go
We always want to use the filtered catalog tag, unless the catalog is not being filtered.
This fixes a regression introduced by https://github.com/openshift/oc-mirror/pull/1093
Github / Jira issue: OCPBUGS-57461
> OCPBUGS-57461,OCPBUGS-56718: v2/operator: add rebuilt catalog to tar file

- go.work.sum
- v2/go.mod
- v2/internal/pkg/imagebuilder/builder.go
Manual cherry-pick of https://github.com/openshift/oc-mirror/pull/1170
Right now go-containerregistry lib is using the default docker+podman locations. If oc-mirror is run with `--authfile` pointing to a custom location, it will be used for other images except the graph image.
This change adds a custom keychain with the contents of --authfile so it is picked up by go-containerregistry.
> OCPBUGS-57068: [release-4.18]: v2/imgbuilder: use --authfile when set

- v2/internal/pkg/cli/executor.go
From discusssions with our PM and the creator of the issue, we have agreed to add a warning message if a umask setting other than 0022 is detected
Github / Jira issue:  OCPBUGS-55374
Set umask to 0077
Console output should show warning message
```
$ bin/oc-mirror --config test.yaml file://ocpbugs-51157 --v2
2025/06/19 09:48:54  [WARN]   : ⚠️  Detected bad umask 0077 (oc-mirror requires a umask of 0022)
```
> OCPBUGS-55374: Add console warning if bad umask is detected

- v2/internal/pkg/mirror/mirror.go
This change makes use of a custom error check function to extend the checks made by containers/common on whether to retry a copy operation or not.
Github / Jira issue: OCPBUGS-57362
`--retry-times` settings is respected in case of 50x errors and `ContextDeadlineExceeded`
> OCPBUGS-58186: v2/mirror: retry in case of ContextDeadlineExceeded

- v2/internal/pkg/cli/executor.go
- v2/internal/pkg/operator/common.go
- v2/internal/pkg/operator/filtered_collector.go
When an operator catalog is referenced by digest only in the ImageSetConfiguration, the tag on the destination will be the digest of the original one instead of the digest of the rebuilt operator catalog (more details on [OCPBUGS-52470](https://issues.redhat.com/browse/OCPBUGS-52470) 
This PR was created based on PR #1130. 
This PR fixes this scenario for `d2m` and `m2m`. 
- [OCPBUGS-52470](https://issues.redhat.com/browse/OCPBUGS-52470)
With the following ImageSetConfiguration: 
```
mirror:
operators:
- catalog: registry.redhat.io/redhat/redhat-operator-index@sha256:e3368fb4222d7586a1505748f383fa711b2a2baa231dd02c02b974fd19ade942
packages:
- name: rhods-operator
defaultChannel: fast
channels:
- …
```
> OCPBUGS-52470: Fixes the tag when rebuilt catalog by digest only

- v2/internal/pkg/cli/const.go
- v2/internal/pkg/mirror/options.go
This PR fixes rate limiting issues that occur during mirror operations when oc-mirror sends too many requests to container registries, resulting in "too many requests" errors.
The change sets the default `--retry-delay` to 0 seconds to force the containers/image library to use its built-in exponential backoff retry strategy instead of fixed 1-second delays. This provides smarter retry timing that adapts to rate limiting responses from container registries.
This change works in conjunction with:
- Increased `--retry-times` for more retry attempts
- Reduced `maxParallelLayerDownloads` and `maxParallelImageDownloads` to limit concurrent requests
Github / Jira issue: [OCPBUGS-57370](https://issues.redhat.com/browse/OCPBUGS-57370)
Since this is not an issue that is always happening, it is not …
> OCPBUGS-57370: v2/defaults Fix rate limiting issues by enabling exponential backoff retries

- v2/internal/pkg/archive/unarchive.go
- v2/internal/pkg/archive/unarchive_test.go
- v2/internal/pkg/cli/executor.go
- v2/internal/pkg/cli/executor_test.go
If we don't error out right away, the error message returned gives no clue about the actual reason for the failure:
```
2025/06/27 10:21:45  [ERROR]  : [Executor] collection error: collect catalog "registry.redhat.io/redhat/redhat-operator-index:v4.18": get manifest: error when creating a new image source: reading manifest v4.18 in localhost:55000/redhat/redhat-operator-index: manifest unknown
```
Github / Jira issue: OCPBUGS-58193
```fish
❯ ~/prjs/github.com/openshift/oc-mirror/bin/oc-mirror --v2 --config catalog-isc.yaml --from file://data/catalog-filter-fail docker://localhost:5000/data --dest-tls-verify=false --log-level=debug
2025/06/27 14:31:30  [INFO]   : 👋 Hello, welcome to oc-mirror
2025/06/27 14:31:30  [INFO]   : ⚙️  setting up the …
```
> OCPBUGS-58193: v2/archive: error d2m when no tar files found

- v2/internal/pkg/cli/delete.go
Showing `delete` is enough and less confusing than `diskToMirror / delete` which is just an implementation detail.
Github / Jira issue: OCPBUGS-54622
Check output of `oc-mirror --v2 delete`
"workflow mode" shows `delete` instead of `diskToMirror / delete`
> OCPBUGS-54622: cli/delete: fix workflow mode name output

- v2/Makefile
- v2/go.mod
This change adds `build-machinery-go` as a tool dependency in the oc-mirror v2. The modification ensures that the build machinery is properly managed as a tool dependency rather than a regular dependency, which prevents it from being included in the final binary and keeps the dependency tree cleaner.
The changes include:
- Updated the Makefile to use the `-tool` flag when fetching build-machinery-go
- Added build-machinery-go as a tool dependency in go.mod
This change improves the build process by properly categorizing build-time dependencies.
The changes were tested by:
1. Running `go mod tidy` to ensure the tool dependency is properly managed
2. Verifying that the build process still works correctly with the updated Makefile
The build process should continue to work as expected, but …
> NO-JIRA: adds build-machinery-go as a tool dependency

- cmd/oc-mirror/main.go
It seems /home must also be mounted `noexec` [1]. So let's go back to extracting to /tmp since overriding it with the `TMPDIR` envvar is less disruptive than overriding `HOME`.
[1] https://stigviewer.com/stigs/red_hat_enterprise_linux_9/2025-02-27/finding/V-257852
Github / Jira issue: OCPBUGS-59646
```
$ podman run --rm -it --tmpfs /tmp:noexec docker.io/redhat/ubi9:latest
[root@68107d25fc95 /]# mount | grep '/tmp'
tmpfs on /tmp type tmpfs (rw,nosuid,nodev,noexec,relatime)
$ CGO_ENABLED=0 make build
$ podman cp bin/oc-mirror <container>:/root
[root@c8c6ec9d1700 /]# /root/oc-mirror --v2 --help
failed to run oc-mirror: fork/exec /tmp/oc-mirror-1960038340/oc-mirror: permission denied
The tmp dir "/tmp" might be mounted as `noexec`. Please set …
```
> OCPBUGS-59646: revert #1220 and print a warning instead

- v2/internal/pkg/helm/local_stored_collector.go
This PR prevents the panic to happen when the helm chart is nil (bug introduced on PR #1172).
Github / Jira issue: [OCPBUGS-59913](https://issues.redhat.com/browse/OCPBUGS-59913)
With the following ImageSetConfig:
```
mirror:
helm:
local:
- name: test-mirror-helm
path: data/test-mirror-helm-0.3.0.tgz
imagePaths:
- "{.spec.template.spec.containers[*].env[*].value}"
```
I ran `m2d` without 3 times with the following scenarios:
* does not have data directory 
* does not have the data/test-mirror-helm-0.3.0.tgz file
* the data/test-mirror-helm-0.3.0.tgz file size is 0
All the 3 `m2d` should not panic, it should show only an error message like below:
```
2025/08/01 11:03:43  [ERROR]  : [Executor] collection error: failed to …
```
> OCPBUGS-59913: prevents panic when helm chart is nil

- v2/internal/pkg/cli/executor.go
- v2/internal/pkg/cli/executor_test.go
Check that we can authenticate against the destination registry with the given credentials.
Github / Jira issue: [CLID-389](https://issues.redhat.com//browse/CLID-389)
* Innaccessible registry:
```
❯ ~/prjs/github.com/openshift/oc-mirror/bin/oc-mirror --v2 --config catalog-isc.yaml --from file://data/catalog-filter-fail docker://localhost:6000/data --log-level=debug --dest-tls-verify=false
2025/06/30 16:00:13  [INFO]   : 👋 Hello, welcome to oc-mirror
2025/06/30 16:00:13  [INFO]   : ⚙️  setting up the environment for you...
[...]
2025/06/30 16:00:13  [ERROR]  : [Executor] checking registry "localhost:6000/data" access: failed to authenticate: pinging container registry localhost:6000: Get "http://localhost:6000/v2/": dial tcp [::1]:6000: …
```
> CLID-389: v2: validate access to destination registry

- cmd/oc-mirror/main.go
Manual cherry-pick of https://github.com/openshift/oc-mirror/pull/1228
Github / Jira issue: OCPBUGS-59760
> [release-4.19] OCPBUGS-59760: warn if tmp is `noexec`

- pkg/cli/mirror/mirror.go
The warning message was changed to let customers know that starting in 4.21 the use of --v1 or --v2 flag is mandatory..
Github / Jira issue: [OCPBUGS-61800](https://issues.redhat.com/browse/OCPBUGS-61800)
```
./bin/oc-mirror --help
```
Second and third message should be in yellow color.
```
W0919 11:49:26.494821  222595 mirror.go:88] ⚠️  oc-mirror v1 is deprecated (started in 4.18 release) and will be removed in a future release - please migrate to oc-mirror --v2
W0919 11:49:26.494843  222595 mirror.go:89] ⚠️  starting with oc-mirror 4.21, the use of the flag --v1 or --v2 is mandatory, please use --v2 to use the supported oc-mirror version or --v1 to continue using the oc-mirror deprecated version
W0919 11:49:26.494848  222595 mirror.go:90] ⚠️  the sub-commands list, describe and init are …
```
> OCPBUGS-61800: changes the warning message of 4.21

- v2/internal/pkg/archive/archive.go
- v2/internal/pkg/archive/archive_test.go
- v2/internal/pkg/cli/executor.go
This fix is to avoid creating a tarball of 0kb in the beginning of the workflow. With this fix the archive will be generated only after the mirroring if there is NO batch errors.
Github / Jira issue: [OCPBUGS-60929](https://issues.redhat.com/browse/OCPBUGS-60929)
Scenario 1: Run m2d and let it finish with success.
Scenario 2: Run m2d and cut off the internet so it will finish with failures.
Scenario 1: should generate a tarball
Scenario 2: should NOT generate a tarball (not even with 0kb).
> OCPBUGS-60929: generate the archive only after mirroring

- pkg/cli/mirror/mirror.go
This is an manual backport of https://github.com/openshift/oc-mirror/pull/1271
/assign aguidirh
> [release-4.18] OCPBUGS-62432: changes the warning message of 4.21
