openshift/oc-mirror

.gitignore, go.mod, pkg/bundle/additional.go, pkg/bundle/additional_test.go, pkg/bundle/create/create.go, pkg/bundle/image.go, pkg/bundle/image_test.go
Features Added:
- User defined image mirroring
- Simple image blocking
- Tests added
=> User-defined images mirroring feature with simple blocking

go.mod, go.sum
=> chore(deps): pin to latest estroz/operator-registry commit

go.mod, go.sum, pkg/bundle/create/create.go, pkg/metadata/storage/git.go, pkg/metadata/storage/local.go, pkg/metadata/storage/storage.go, pkg/metadata/store.go
I'm going to add an integration tests in a follow-up since there's already enough code in this PR. Will also follow up with configurable storage.
=> feat(storage): git-based storage Backend, Committer interface

cmd/oc-bundle/create.go, cmd/oc-bundle/main.go, cmd/oc-bundle/publish.go, go.mod, pkg/archive/archive.go, pkg/bundle/additional.go, pkg/bundle/additional_test.go, pkg/bundle/create/create.go, pkg/bundle/create/options.go, pkg/bundle/publish/options.go, pkg/bundle/publish/publish.go, pkg/bundle/release.go, pkg/cli/log.go, pkg/cli/options.go, pkg/metadata/storage/local.go, pkg/operator/mirror.go
Some quality-of-life refactoring.
=> chore(cli,create): refactor create functions around CLI options

.github/workflows/ci.yaml, .goreleaser.yaml, README.md, data/imageset-config.yaml, pkg/archive/archive.go, pkg/bundle/create/create.go, pkg/bundle/init.go, pkg/bundle/publish/publish.go, pkg/image/association.go, pkg/metadata/storage/local.go, pkg/metadata/storage/local_test.go, pkg/metadata/storage/storage.go, pkg/metadata/store.go
Features added:
- Publish processes one archive or archive is a directory
- Publish will process one image in the association at a time and prep the directory for the image validation and push
- Publish will compares metadata from disk and archive
=> feat(publish): initial publish work

pkg/archive/archive.go, pkg/bundle/publish/publish.go
- Set flag to allow archiver to overwrite files
- Added usage of skip cleanup flag on publisher
- Cleanup some comments
=> fix(publish): changed overwrite option to true and comment cleanup

pkg/bundle/publish/publish.go, pkg/image/association.go
=> fix(create): use lstat to detect image tag symlinks

.github/workflows/ci.yaml, .goreleaser.yaml
- Updated workflow step relations and workflow triggers
- Removed darwin and arm64 release options
=> chore: workflow update

.goreleaser.yaml
- Enabled CGO on goreleaser.yml for sqlite3 library.
=> fix: enabled CGO on goreleaser.yml

go.mod, go.sum, test/operator/testdata/indices/latest/index/index.yaml
=> chore(deps): use upstream operator-registry

README.md, pkg/bundle/create/create.go, pkg/bundle/publish/catalog_images.go, pkg/bundle/publish/manifests.go, pkg/bundle/publish/publish.go, pkg/operator/mirror.go
Follows up on https://github.com/RedHatGov/bundle/pull/88#discussion_r713079992.
=> fix(publish): dedupe and correctly construct ICSP's for all image types

pkg/bundle/publish/catalog_images.go, pkg/bundle/publish/manifests.go
=> fix(publish): do not return an error when no catalogs are present

pkg/bundle/publish/manifests.go
=> fix(operators): prefer tags over digests when generating CatalogSources

pkg/bundle/create/create.go, pkg/operator/mirror.go
- Handles errors when pinning images in catalog mirror when bundles have images with no tags
=> fix(create): Bug/issue 106

pkg/bundle/create/create.go, pkg/bundle/files.go, pkg/bundle/files_test.go, pkg/bundle/publish/publish.go, pkg/config/v1alpha1/metadata_types.go
=> fix: fix ref passed to registry client

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, docs/dev/getting-started.md, docs/dev/styleguides.md
- Added to Contributing guide
- Added `getting-started`
- Added issue and pull request templates
- Started a style guide doc
=> chore: docs update

CONTRIBUTING.md, README.md, pkg/archive/doc.go, pkg/bundle/doc.go, pkg/cli/mirror/additional.go, pkg/cli/mirror/additional_test.go, pkg/cli/mirror/catalog_images.go, pkg/cli/mirror/cincinnati.go, pkg/cli/mirror/cincinnati_test.go, pkg/cli/mirror/create.go, pkg/cli/mirror/doc.go, pkg/cli/mirror/helm.go, pkg/cli/mirror/helm_test.go, pkg/cli/mirror/mirror.go, pkg/cli/mirror/operator.go, pkg/cli/mirror/options.go, pkg/cli/mirror/publish.go, pkg/cli/mirror/release.go, pkg/cli/options.go, pkg/config/credentials.go, pkg/metadata/doc.go, pkg/release/release_test.go
=> refactor: change root options

README.md, pkg/cli/mirror/catalog_images.go, pkg/cli/mirror/catalog_images_test.go, pkg/metadata/storage/registry.go, test/lib.sh
=> feat(publish): multi-arch catalog rebuilds

OWNERS
Added component to the OWNERS file
=> chore: add component to OWNERS file

README.md, pkg/cli/mirror/list/list.go, pkg/cli/mirror/list/operators.go
=> docs: README and examples update

pkg/cli/mirror/operator.go, pkg/cli/mirror/operator_test.go, pkg/cli/mirror/options.go
Added `--skip-missing` and `--continue-on-error` flags to allow mirroring as much content as possible.
Fixes #126
* Hardware:
* Toolchain:
* SDK:
=> feat(mirror): add --skip-missing and --continue-on-error

Dockerfile, rootfs/entrypoint.sh
Removed old multi-stage process and runtime-in-runtime bits as they're no longer necessary. Refactored a bit since complexity was a little out of hand, and updated verbiage where appropriate. Fixed bug-in-waiting via unversioned `sort` of version tags.
As the image is not currently used in CI systems, I performed a standard local development workflow style test by building the image and compiling the oc-mirror binary with it, as was previously documented in comments on the image.
```
docker build -f Dockerfile -t local/go-toolset .
docker run -it --rm --privileged -v ${PWD}:/build:z local/go-toolset
```
* OS: Fedora 35 Silverblue
* Hardware: x86_64
* Toolchain: `podman` w/ `podman-docker`
- Note that I don't believe the style guidelines cover this image, but I …
=> Cleaned up Dockerfile

pkg/cli/mirror/release.go, pkg/image/association.go
=> fix: add defer for file in get mapping and fix errors.As usage

pkg/cli/mirror/operator.go, pkg/config/v1alpha1/metadata_types.go, pkg/metadata/store.go
Remove unused fields that are not immediately/ever useful.
* Hardware:
* Toolchain:
* SDK:
=> chore(operator): remove unimplemented alternatives to `OperatorMetadata.ImagePin`

README.md, docs/usage.md
=> chore: docs/usage update

README.md, docs/examples/imageset-config-catalog-headsonly.yaml, docs/examples/imageset-config-filter-catalog.yaml, docs/examples/imageset-config-helm.yaml, docs/examples/imageset-config-okd.yaml, docs/examples/imageset-config-registry-backend.yaml, docs/examples/imageset-config-release.yaml
This PR adds an examples directory with example imageset configurations based on desired behaviors
Fixes #198
=> chore: add examples dir

pkg/metadata/storage/registry.go
Fixes quay compatibility with the registry backend.
Fixes #168 
=> fix: change solution checking for image metadata existence

pkg/cli/mirror/mirror.go, pkg/cli/mirror/options.go, pkg/cli/mirror/publish.go
=> feat(publish): Allow user to specify top-level namespace in target registry

.gitignore, README.md, docs/usage.md, pkg/archive/archive.go, pkg/archive/archive_test.go, pkg/cli/mirror/create.go, pkg/cli/mirror/list/updates.go, pkg/cli/mirror/mirror.go, pkg/cli/mirror/options.go, pkg/cli/mirror/publish.go, pkg/cli/mirror/publish_test.go, pkg/cli/options.go, pkg/config/v1alpha1/metadata_types.go, pkg/config/v1alpha1/storage_config_types.go, pkg/metadata/storage/local.go, pkg/metadata/storage/local_test.go, pkg/metadata/storage/registry.go, pkg/metadata/storage/registry_test.go, pkg/metadata/storage/storage.go, pkg/metadata/storage/storage_test.go, test/e2e-simple.sh, test/operator/setup-testdata.sh, test/operator/testdata/configs/latest/imageset-config-headsonly-backend-registry.yaml, test/operator/testdata/configs/latest/imageset-config-headsonly.yaml
Refactor backends and backend config to make the config more intuitive. Also decoupled the metadata on disk from the workspace.
Fixes #188 
Fixes #169 
Fixes #179 
- Unit tests added under storage package for #188 and #179 validation
- E2E tested edited for changes and validated #179
=> refactor(storage): local storage config refactor

docs/examples/imageset-config-filter-catalog.yaml, docs/imageset-config-ref.yaml, go.mod, pkg/cli/mirror/list/updates.go, pkg/cli/mirror/operator.go, pkg/config/v1alpha1/config_test.go, pkg/config/v1alpha1/config_types.go, pkg/config/v1alpha1/include_config.go, pkg/config/v1alpha1/testdata/config/valid.yaml, pkg/metadata/storage/local_test.go, pkg/metadata/storage/registry_test.go, test/operator/testdata/configs/latest/imageset-config-full.yaml, test/operator/testdata/configs/latest/imageset-config-headsonly-backend-registry.yaml, test/operator/testdata/configs/latest/imageset-config-headsonly.yaml
- `version/bundle []string -> startingVersion/startingBundle string`
- remove unused index handling keys, since these modes will not be supported
* Hardware:
* Toolchain:
* SDK:
=> fix(config): cleaned up config keys, made naming and defaults more intuitive

docs/usage.md, pkg/cli/mirror/catalog_images.go, pkg/cli/mirror/catalog_images_test.go, pkg/cli/mirror/manifests.go, pkg/cli/mirror/mirror.go, pkg/cli/mirror/publish.go, test/e2e-simple.sh
=> fix(catalogs): custom namespace catalog build fail

hack/e2e.sh, test/e2e-config.yaml, test/e2e-simple.sh, test/lib.sh, test/operator/setup-testdata.sh, test/operator/testdata/configs/latest/imageset-config-full.yaml, test/operator/testdata/configs/latest/imageset-config-headsonly-backend-registry.yaml, test/operator/testdata/configs/latest/imageset-config-headsonly.yaml, test/operator/testdata/indices/diff/index/index.yaml, test/operator/testdata/indices/latest/index/index.yaml
This PR adds the ability to run the e2e tests in a container
=> chore: temp e2e solution

test/lib.sh
Turn on vendor more when installing crane during e2e
Manually tested. Testing through CI.
=> chore: complete crane install in temp dir and turn off vendor mode

docs/examples/imageset-config-helm.yaml
This PR update the Helm example to remove an extra key causing decode errors.
Fixes #228 
I have tested the update config manually and will submit an issue to add an E2E test
=> fix: remove extra field on helm example config

pkg/cli/mirror/operator.go, pkg/config/v1alpha1/config_types.go, test/e2e-simple.sh, test/operator/testdata/configs/latest/imageset-config-skip-deps.yaml
This PR adds the SkipDependencies key when processing operators.
Fixes #221 
=> feat: change operator config schema to support skipping dependencies

pkg/cli/mirror/additional.go, pkg/cli/mirror/create.go, pkg/cli/mirror/create_test.go, pkg/cli/mirror/mirror.go, pkg/cli/mirror/mirror_test.go, pkg/cli/mirror/operator.go, pkg/cli/mirror/options.go, pkg/cli/mirror/release.go, pkg/cli/mirror/testdata/configs/test.yaml
This PR allows the dry-run option to run without failures due to image associations or creating an unwanted archive 
Partially fixes #206 
=> refactor(create): allow dry run option to run without failing

pkg/cli/mirror/describe/describe.go, pkg/cli/mirror/list/list.go, pkg/cli/mirror/list/operators.go, pkg/cli/mirror/list/releases.go, pkg/cli/mirror/mirror.go
Minor grammatical updates to help content.
Documentation change only
By generating the oc-mirror binary and running help commands.
=> Minor help text updates

docs/dev/getting-started.md, pkg/bundle/files_test.go, pkg/cincinnati/cincinnati_test.go, pkg/cincinnati/find_test.go, pkg/cli/mirror/create.go, pkg/cli/mirror/helm.go, pkg/cli/mirror/publish_test.go, pkg/cli/mirror/release.go, pkg/config/v1alpha1/metadata_types.go, pkg/image/association.go, pkg/metadata/storage/local.go, pkg/metadata/store.go
Signed-off-by: jpower432 <barnabei.jennifer@gmail.com>
This PR fixes some spelling and grammar found throughout the packages and adds check for two unhandled errors
N/A
* Hardware:
* Toolchain:
* SDK:
=> chore: spelling and grammar fixes in comments and docs

OWNERS
This PR updates the OWNERS file reviewers and approvers
=> chore: update OWNERS file

pkg/cli/mirror/publish.go, pkg/cli/mirror/publish_test.go
This PR adds a unit test for the `findBlobRepo` function in `publish.go`.
=> test: add unit tests for findBlobRepo function in publish.go

docs/usage.md
Docs updating oc-mirror vs oc mirror
Fixes #183
Docs only
=> Documenting oc-mirror vs oc mirror [183]

images/cli/Dockerfile.ci
This PR cherry-picks the commit from PR #289 to add to the `release-4.10` branch
=> chore: add Dockerfile for CI builds (#289)

Makefile
This PR adds sanity checks to the Makefile to ensure `go mod tidy` does not show any differences from what is committed on the branch
=> chore: add sanity check for tidy

OWNERS
This PR updates the OWNERS file to add `deejross` as a reviewer.
N/A
=> chore: adds deejross as reviewer in OWNERS file

pkg/cli/mirror/manifests.go
This PR fixes the API version on the generated Catalog Sources when processing operator catalogs.
=> fix: changes Catalog Source API version to v1alpha1

pkg/cli/mirror/release.go
Fixes #319
This PR moves release images to a new namespace apart from the release content to support use with OSUS.
=> fix: moves release images to a separate repo from release image content

Makefile, test/integration/Makefile
Temporary change to enable Prow to pick up some more verbose output in integration test rehearsals
This will be reverted in a rebase of #362
=> Added some extra output to help with CI rehearsals

pkg/cli/mirror/mirror.go, pkg/cli/mirror/publish.go
=> fix: adds context around sequence errors returned during publishing

pkg/api/v1alpha2/types_metadata.go, pkg/api/v1alpha2/types_platform.go, pkg/archive/archive_test.go, pkg/cincinnati/cincinnati.go, pkg/cincinnati/cincinnati_test.go, pkg/cincinnati/client.go, pkg/cincinnati/client_test.go, pkg/cincinnati/find.go, pkg/cli/mirror/list/releases.go, pkg/cli/mirror/list/releases_test.go, pkg/cli/mirror/list/updates.go, pkg/cli/mirror/list/updates_test.go, pkg/cli/mirror/mirror.go, pkg/cli/mirror/mirror_test.go, pkg/cli/mirror/options.go, pkg/cli/mirror/release.go, pkg/cli/mirror/release_test.go
This PR adds unit tests in the mirror package for `release.go` and `mirror.go` and cleans up some error handling bugs and comments errors found in `cincinnati.go`. This also alters the `archive_test.go` unit tests to conform to the standard in other packages.
Blocked by #411 
Unit tests added
=> test: adds unit tests in mirror package for release.go and mirror.go

docs/design/imageset-configuration.md
The information about duplicate catalog images
was out of date per PR #432.
Fixed some existing clarity issues
N/A
=> docs: cleanup and updates imageset-configuration.md

docs/design/imageset-configuration.md, docs/design/metadata-management.md, docs/design/overview.md, docs/design/workflows.md, docs/usage.md
This PR adds notes to about flags to the `usage.md` docs.
N/A
=> docs: add notes about flag usage to usage.md

pkg/cli/mirror/mirror.go, pkg/cli/mirror/operator.go, pkg/cli/mirror/util.go
The PR adds a `mapping.txt` output when publishing images from disk
=> feat(publish): adds mapping output after publishing operations

test/integration/requirements.yml
Bumped integration test collection to inherit the following bugfixes:
- Enable RHUI through arbitrary endpoints
- Pin collection dependencies more specifically to fix inherited dependency problems
- Fix for directory creation ordering in compile case
- Async mirror-registry installation to prevent timeouts in CI
`/test integration`
=> fix(ci) Update integration test collection to inherit bugfixes

docs/usage.md, go.mod, pkg/archive/archive.go, pkg/bundle/files.go, pkg/cincinnati/cincinnati.go, pkg/cli/log.go, pkg/cli/mirror/catalog_images.go, pkg/cli/mirror/cincinnati_graph_image.go, pkg/cli/mirror/create.go, pkg/cli/mirror/helm.go, pkg/cli/mirror/manifests.go, pkg/cli/mirror/mirror.go, pkg/cli/mirror/operator.go, pkg/cli/mirror/operator_test.go, pkg/cli/mirror/pack.go, pkg/cli/mirror/prune.go, pkg/cli/mirror/publish.go, pkg/cli/mirror/release.go, pkg/cli/options.go, pkg/image/builder/image_builder.go, pkg/image/convert.go, pkg/image/mapping.go, pkg/metadata/storage/local.go, pkg/metadata/storage/registry.go, pkg/metadata/storage/storage.go, pkg/metadata/store.go
This PR does some normalization after the migration from `logrus` to `klog` as the main logging solution.
=> chore(logging): Adds logrus setup back and changes klog verbosity levels

README.md
Inform users of pruning behavior and mode compat. also change meet freq
Docs/Readme
=> bug 2093957: [docs] Light readme maint

OWNERS
=> chore: remove jpower432 as approver

docs/design/metadata-management.md
Fix --ignore-history flag description
* Hardware:
* Toolchain:
* SDK:
=> Fix --ignore-hisotry description and some format adjustment

pkg/cli/mirror/copy.go, pkg/cli/mirror/copy_test.go, pkg/cli/mirror/mirror.go
This PR is simply to fix the final comments left by @soltysh on https://github.com/openshift/oc-mirror/pull/512
=> Pr 512 follow

OWNERS
Removes afflom from oc-mirror OWNERS.
=> remove afflom

docs/design/metadata-management.md
Updates information in metadata-management design documentation.
N/A, Docs only
=> docs: adds grammar fixes to metadata-management.md

go.mod, pkg/cli/mirror/copy.go, pkg/cli/mirror/copy_test.go, pkg/cli/mirror/mirror.go, pkg/cli/mirror/options.go, pkg/cli/mirror/testdata/configs/registries.conf, test/e2e/testcases.sh, vendor/github.com/containers/image/v5/pkg/cli/environment/environment.go, vendor/modules.txt
Fixes # OCPBUGS-2851
[x] Unit tests
[x] Non-regression: E2E tests
* Hardware:
* Toolchain:
* SDK:
=> OCPBUGS-2851: fix

pkg/cli/mirror/copy.go
This fixes the case where namespace or subnamespace may be empty, and mirroring was failing due to incorrect image reference (`//` in reference)
```
error: mirroring images "localhost:5000//multicluster-engine/mce-operator-bundle@sha256:e7519948bbcd521390d871ccd1489a49aa01d4de4c93c0b6972dfc61c92e0ca2" is not a valid image reference: invalid reference format
```
Fixes #OCPBUGS-4365
* Hardware:
* Toolchain:
* SDK:
=> OCPBUGS-4365: Fix cases where namespace or subnamespace may be empty

OWNERS
Luigi and Sherine are taking over the leadership and maintenance of the project, let's add them as new reviewers for the start.
=> New reviewers: Luigi Mario Zuccarelli, Sherine Khoury

.ci-operator.yaml, Dockerfile, go.mod, images/cli/Dockerfile.ci, test/e2e/lib/util.sh
Golang version being used was changed from version 1.18.6 to 1.19.5
make build
make verify
make test-unit
make test-e2e
* Hardware:
* Toolchain:
* SDK:
=> CFE-743: Update of golang version from 1.18.6 to 1.19.5

images/cli/Dockerfile.ci
* Hardware:
* Toolchain:
* SDK:
=> Upgrade base image for oc-mirror to 4.13

pkg/cli/mirror/fbc_operators.go, pkg/cli/mirror/fbc_operators_test.go
Implementation of filtering by channel for OCI catalog
`./bin/oc-mirror --config=/home/aguidi/Dev/git-repos/CFE/oc-mirror/oc-mirror/imstcfg.yaml --use-oci-feature --oci-feature-action=mirror --dest-skip-tls --dest-use-http docker://localhost:5000/`
```
storageConfig:
local:
path: /home/aguidi/Dev/git-repos/CFE/oc-mirror/oc-mirror/alex_local_storage
mirror:
operators:
- catalog: oci:///home/aguidi/Dev/git-repos/CFE/oc-mirror/oc-mirror/oci-catalog
originalRef: registry.redhat.io/redhat/redhat-operator-index:v4.12
packages:
#minVersion: 0.0.0
#maxVersion: 0.1.9
channels:
- name: stable-v0
- name: stable-v0.1
#minVersion: 0.0.0 …
```
=> CFE-658 - Implementation of filtering by channel for OCI catalog

pkg/cli/mirror/fbc_operators.go, pkg/cli/mirror/fbc_operators_test.go, pkg/cli/mirror/mirror.go, pkg/cli/mirror/operator.go
=> CFE-768 - FollowUp: Fix usage of registries.conf for OCI feature

OWNERS
Update OWNERS for CFE after our conversation with @dinhxuanvu
=> OCPBUGS-12437: Update OWNERS for CFE team

pkg/cli/mirror/fbc_operators.go, pkg/cli/mirror/fbc_operators_test.go, pkg/cli/mirror/operator.go, test/e2e/testcases.sh
Implementation of filtering by channel for OCI catalog
`./bin/oc-mirror --config=/home/aguidi/Dev/git-repos/CFE/oc-mirror/oc-mirror/imstcfg.yaml --use-oci-feature --oci-feature-action=mirror --dest-skip-tls --dest-use-http docker://localhost:5000/`
```
storageConfig:
local:
path: /home/aguidi/Dev/git-repos/CFE/oc-mirror/oc-mirror/alex_local_storage
mirror:
operators:
- catalog: oci:///home/aguidi/Dev/git-repos/CFE/oc-mirror/oc-mirror/oci-catalog
originalRef: registry.redhat.io/redhat/redhat-operator-index:v4.12
packages:
#minVersion: 0.0.0
#maxVersion: 0.1.9
channels:
- name: stable-v0
- name: stable-v0.1
#minVersion: 0.0.0 …
```
=> OCPBUGS-13116: Implementation of filtering by channel for OCI catalog

pkg/cli/mirror/mirror.go
* Fix OCPBUGS-2633
* Revert "Fix OCPBUGS-2633"
This reverts commit a1a3b82159f8a2d436a41cd10486e35250f77153.
* Fix OCPBUGS-2633 keeping scope of fix to MirrorToDisk only
---------
* Hardware:
* Toolchain:
* SDK:
=> [release-4.12] OCPBUGS-13432: Got the `file exists` error when different digest direct to the same tag

v2/pkg/cli/executor.go, v2/pkg/cli/executor_test.go, v2/tests/isc.yaml
=> CFE-904: [v2] Fix unit tests for local storage collector implementation

pkg/cli/options.go
When running `oc-mirror version` from a read-only file system the command creates a stacktrace. With this fix we will log to console that we disable logging to a file.
Fixes #659 
We have performed a local build and ran the code on a normal and read-only file system.
=> fixing `oc-mirror version` when run from read-only fs

OWNERS
Only a small change on owner file.
=> CFE-955: changes owner file

README.md
This PR simply updates the README: the team is not conducting any zoom meetings for the community office hours
=> NO-ISSUE: Cancel community office hours: none for the moment

.ci-operator.yaml, Dockerfile, images/cli/Dockerfile.ci
Fixes # [OCPBUGS-23550](https://issues.redhat.com/browse/OCPBUGS-23550)
Please describe the outcome expected from the tests
=> OCPBUGS-23550: - oc-mirror on RHEL9 Host with FIPS enabled

docs/enclave_support.md
This PR updates the documentation for EnclaveSupport to Dev Preview as suggested by @racedo
=> NO-ISSUE: Make EnclaveSupport a DevPreview

v2/pkg/archive/adder_common.go, v2/pkg/archive/archive.go, v2/pkg/archive/archive_test.go, v2/pkg/archive/const.go, v2/pkg/archive/interface.go, v2/pkg/archive/permissive_adder.go, v2/pkg/archive/permissive_adder_test.go, v2/pkg/archive/strict_adder.go, v2/pkg/archive/strict_adder_test.go, v2/pkg/archive/unarchive.go, v2/pkg/archive/unarchive_test.go, v2/pkg/cli/executor.go, v2/pkg/cli/executor_test.go, v2/pkg/mirror/options.go, v2/tests/archive-test-data/0000_03_config-operator_01_proxy.crd.yaml, v2/tests/archive-test-data/0000_03_marketplace-operator_01_operatorhub.crd.yaml, v2/tests/archive-test-data/0000_03_securityinternal-openshift_02_rangeallocation.crd.yaml, vendor/github.com/openshift/oc-mirror/v2/pkg/archive/adder_common.go, vendor/github.com/openshift/oc-mirror/v2/pkg/archive/archive.go, vendor/github.com/openshift/oc-mirror/v2/pkg/archive/const.go, vendor/github.com/openshift/oc-mirror/v2/pkg/archive/interface.go, vendor/github.com/openshift/oc-mirror/v2/pkg/archive/permissive_adder.go, vendor/github.com/openshift/oc-mirror/v2/pkg/archive/strict_adder.go, vendor/github.com/openshift/oc-mirror/v2/pkg/archive/unarchive.go, vendor/github.com/openshift/oc-mirror/v2/pkg/cli/executor.go, vendor/github.com/openshift/oc-mirror/v2/pkg/mirror/options.go
Supports use of  `archiveSize` (from the image set config) in order to set the maximum size per archive. 
Fixes # [CLID-22](https://issues.redhat.com//browse/CLID-22) + [CLID-21](https://issues.redhat.com//browse/CLID-21) 
With this imageSetConfig,
* perform a mirror to disk, 
* copy the tar files to a different folder
* then perform a disk to mirror from this new folder
Mirroring should pass
```yaml
archiveSize: 1
mirror:
operators:
packages:
- name: "gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0"
- name: "quay.io/cockroachdb/cockroach-helm-operator:6.0.0"
- name: …
```
=> CLID-9,CLID-21,CLID-22: Respect archive max size

docs/design/imageset-configuration.md, docs/examples/imageset-config-helm-repository.yaml, pkg/cli/mirror/additional.go, pkg/cli/mirror/helm.go, pkg/cli/mirror/helm_test.go, test/e2e/configs/imageset-config-helm-repository.yaml, test/e2e/lib/util.sh, test/e2e/lib/workflow.sh, test/e2e/testcases.sh
Please describe the outcome expected from the tests
=> HELM-518: Changes to support pulling charts from URL

v2/pkg/cli/executor.go, v2/pkg/cli/executor_test.go, vendor/github.com/openshift/oc-mirror/v2/pkg/cli/executor.go
Update to change string replacement with text/template
Standard unit tests
TestExecutorSetupLocalStorage - should pass
=> CLID-85: Change string replacement in registry config to use templates

v2/internal/pkg/batch/worker.go, vendor/github.com/openshift/oc-mirror/v2/internal/pkg/batch/worker.go
This PR generates a file with all the errors that happened during the mirroring process. In this way customers can audit their target registry to check if the errors really happened or they were only flake errors.
Using the following ImageSetConfiguration:
```
mirror:
platform:
channels:
- name: stable-4.13
minVersion: 4.13.10
maxVersion: 4.13.10
graph: true
operators:
- catalog: registry.redhat.io/redhat/redhat-operator-index:v4.15
packages:
- name: 3scale-operator
- name: …
```
=> OCPBUGS-33098: fix: generates a file with errors during mirroring

pkg/cli/mirror/release.go, v2/internal/pkg/release/cincinnati.go, vendor/github.com/openshift/oc-mirror/v2/internal/pkg/release/cincinnati.go
This addresses the issue when mirroring platform releases using the **eus** channel, oc-mirror does not yet implement `conditionalEdges` and as a result will not correctly select the version/s for a complete upgrade path.
A warning message will be displayed in the console when an eus channel with minor versions >= 2 are selected.
This applies to both v1 and v2 versions of oc-mirror
Addresses # [OCPSTRAT-1306](https://issues.redhat.com//browse/OCPSTRAT-1306)
To verify use the following imagesetconfig for v1 of oc-mirror
```
mirror:
platform:
graph: true # Required for the OSUS ooperator
architectures:
- amd64
channels:
- name: stable-4.12
minVersion: '4.12.28'
maxVersion: '4.12.28'
shortestPath: true
type: ocp
- name: …
```
=> CLID-135: Show warning in console when EUS & version conditions used

v2/internal/pkg/operator/local_stored_collector.go, vendor/github.com/openshift/oc-mirror/v2/internal/pkg/operator/local_stored_collector.go
This issue addresses the skip deletion of operator catalog image in delete feature when executing the delete functionality using the --generate flag in version v2 of oc-mirror.
Tested locally using the following flow
Use this ImageSetConfig to execute a mirrorToDisk workflow
```
mirror:
operators:
- catalog: registry.redhat.io/redhat/redhat-operator-index:v4.15
packages:
- name: windows-machine-config-operator
```
Execute the standard mirrorToDisk execution
Execute the standard diskToMirror using the resulting working-dir artifacts
Create a delete imagesetconfig yaml file
```
kind: DeleteImageSetConfiguration
delete:
operators:
- …
```
=> [v2] CLID-136: Skip deletion of operator catalog image in delete feature

v2/internal/pkg/release/local_stored_collector.go, vendor/github.com/openshift/oc-mirror/v2/internal/pkg/release/local_stored_collector.go
Before this fix quay was not recognizing the release images mirrored because the images were mirrored only by digest. As the tag is mandatory for quay, this PR adds tags to all release images.
Fixes # [OCPBUGS-36410](https://issues.redhat.com/browse/OCPBUGS-36410)
Step 1 - mirror To disk
```
[aguidi@fedora oc-mirror]$ ./bin/oc-mirror -c ./alex-tests/alex-isc/isc.yaml file:///home/aguidi/go/src/github.com/aguidirh/oc-mirror/alex-tests/ocpbugs-36410 --v2
2024/07/26 12:34:12  [WARN]   : ⚠️  --v2 flag identified, flow redirected to the oc-mirror v2 version. This is Tech Preview, it is still under development and it is not production ready.
2024/07/26 12:34:12  [INFO]   : 👋 Hello, welcome to oc-mirror
2024/07/26 12:34:12  [INFO]   : ⚙️  setting up …
```
=> [v2] OCPBUGS-36410: fix: creates tags for release images

v2/internal/pkg/operator/local_stored_collector.go, vendor/github.com/openshift/oc-mirror/v2/internal/pkg/operator/local_stored_collector.go
Before this bug fix there were some operator related images duplicated since they were included in more than one operator.
Fixes # [OCPBUGS-37861](https://issues.redhat.com/browse/OCPBUGS-37861)
```
mirror:
operators:
- catalog: registry.redhat.io/redhat/redhat-operator-index:v4.16
```
Run the following command:
```
./bin/oc-mirror -c ./alex-tests/alex-isc/isc.yaml file:///home/aguidi/go/src/github.com/aguidirh/oc-mirror/alex-tests/ocpbugs-37861 --v2
```
Only 947 operator images should be mirrored instead of 1209 as it was before the bug fix.
Log output:
```
2024/08/02 10:03:17  [INFO]   : 🚀 Start copying the images...
2024/08/02 …
```
=> OCPBUGS-37861: removes duplicated operator related images

v2/internal/pkg/imagebuilder/rebuild_catalog.go
The code in this PR adds a rebuild-error.log to help during troubleshooting when errors happen during the rebuild of catalog phase.
Fixes [CLID-263](https://issues.redhat.com/browse/CLID-263)
An invalid container file was provided in the rebuild_catalog.go
The rebuild-error.log must contain information about the error.
=> CLID-263: redirects the rebuild error to a rebuild-error.log

v2/internal/pkg/batch/concurrent_worker.go
This PR simply changes the log to use the emoji arrow
=> OCPBUGS-41331: Revert to arrow emoji when logging

v2/internal/pkg/batch/concurrent_worker.go
Fixes # [OCPBUGS-44449](https://issues.redhat.com/browse/OCPBUGS-44449)
Successfully run delete all the way
Success
=> OCPBUGS-44449: Fix batch info log for delete scenario

v2/internal/pkg/release/local_stored_collector.go
This bugfix addresses the issue when mirroring a release that use a digest rather than a tag
Fixes # It is based off OCPBUGS-44033
For some reason the cherry-pick (automated) missed some changes. This is a manual update of that
Use the following isc
```
mirror:
platform:
release:  registry.ci.openshift.org/ocp/release@sha256:81cdb94649f90fa1a6ccfc8827c55dcf7cfb7e0a6c7f05891476e78d022591ec
```
1. Execute a simple m2m command
```
bin/oc-mirror --config ocpbugs-44033.yaml --workspace file://ocpbugs-44033 docker://localhost:5000/ocpbugs-44033 --v2 --dest-tls-verify=false
```
2. Repeat for mirror to disk and then disk to mirror
Mirroring should pass for all scenarios
=> [release-4.18] OCPBUGS-45249: Failed to mirror ocp payload using digest

OWNERS
Add myself to the reviewers list.
=> no-jira: OWNERS: add myself to reviewers.

OWNERS
Updates the owner file for the branch release-4.17.
=> OCPBUGS-48543: [release-4.17] changes the owners file

OWNERS
Updates the owner file for the branch release-4.18.
=> OCPBUGS-48539: [release-4.18] changes the owners file

OWNERS
Updates the owner file for the branch release-4.16.
=> OCPBUGS-48544: [release-4.16] changes the owners file

OWNERS
Updates the owner file for the branch release-4.15.
=> OCPBUGS-48545: [release-4.15] changes the owners file

OWNERS
Updates the owner file for the branch release-4.14.
=> OCPBUGS-48546: [release-4.14] changes the owners file

OWNERS
Updates the owner file for the branch release-4.13.
=> OCPBUGS-48547: [release-4.13] changes the owners file

OWNERS
Updates the owner file for the branch release-4.12.
=> OCPBUGS-48549: [release-4.12] changes the owners file

v2/docs/delete-functionality.md, v2/internal/pkg/cli/delete.go, v2/internal/pkg/cli/delete_test.go, v2/internal/pkg/cli/executor.go, v2/internal/pkg/cli/executor_test.go, v2/internal/pkg/mirror/options.go
This is a manual cherry-pick of https://github.com/openshift/oc-mirror/pull/1035 + https://github.com/openshift/oc-mirror/pull/1041
=> [release-4.18] OCPBUGS-48842: CLID-301: add --cache-dir command line option

v2/.golangci.yaml
Some options have been deprecated for a while and have been moved to different sections.
=> no-jira: v2: update golangci-lint config

images/cli/Dockerfile.test
This image will be used in Prow to run the integration tests.
Github / Jira issue: [CLID-352](https://issues.redhat.com//browse/CLID-352)
See https://github.com/openshift/release/pull/63343/files
=> CLID-352: images: add integration tests image

go.mod, go.sum, go.work.sum, v2/go.mod, v2/go.sum
This is a manual backport of #1097 
Github / Jira issue: [OCPBUGS-51217](https://issues.redhat.com/browse/OCPBUGS-51217)
Automatic tests pass
=> [release-4.18] OCPBUGS-51217: Fix CVE-2025-27144

v2/internal/pkg/config/load.go, v2/internal/pkg/config/load_test.go
We should be able to accept the `delete` and `mirror` words in the configuration as long as they are not part of the config root keys. This should fix the issue with images making the config be rejected because they contain one of those keywords in their name.
Github / Jira issue:  OCPBUGS-56486
With the following ISC:
```yaml
mirror:
- name: delete.delete/delete/delete/delete1:delete
```
Config is not rejected just because it contains the words `mirror` or `delete`.
=> OCPBUGS-56486: v2/config: allow `delete` and `mirror` words

v2/internal/pkg/helm/local_stored_collector.go
This fix adds more context to error messages
Github / Jira issue:  OCPBUGS-54473
Tested locally using the following ics
```
mirror:
helm:
repositories:
- url: helm.invalid.io/invalid
name: invalid-helm-repository
charts:
- name: invalid-helm-chart
```
Error message should have more context i.e 
```
2025/06/03 14:01:22  [INFO]   : 👋 Goodbye, thank you for using oc-mirror
2025/06/04 14:49:43  [ERROR]  : [Executor] collection error: setting index downloader for invalid-helm-repository: could not find protocol handler
```
=> OCPBUGS-54473: Bug fix - incomplete error messages for helm charts

v2/Makefile, v2/go.mod, v2/go.sum
This will stop `go mod tidy` from removing this dep from go.mod
=> "NO-JIRA: v2: remove build-machinery-go as a go.mod dependency"

v2/internal/pkg/archive/unarchive.go, v2/internal/pkg/archive/unarchive_test.go, v2/internal/pkg/cli/executor_test.go
Manual cherry-pick of https://github.com/openshift/oc-mirror/pull/1207
=> OCPBUGS-59235: [release-4.18] v2/archive: error d2m when no tar files found
